import html
import streamlit as st

from core.recommendation_ai import get_ai_recommendation
from ui.components.cards import (
    recommendation_hero_card_html,
    recommendation_risk_alert_html,
    render_card_styles,
)


def render_recommendation_dashboard(user: str = None):
    """
    AI Recommendation Dashboard V2.
    Renders output ONLY from core.recommendation_ai.
    Zero recommendation calculations performed in UI.
    """
    render_card_styles()

    # 1. Page Title Header
    st.markdown(
        """
        <div style="background: linear-gradient(135deg, #0F172A, #1E3A8A, #2563EB); padding: 24px; border-radius: 20px; color: white; margin-bottom: 20px; box-shadow: 0 10px 28px rgba(37, 99, 235, 0.2);">
            <div style="display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 12px;">
                <div>
                    <h2 style="color: white; margin: 0; font-weight: 900; font-size: 1.8rem;">💡 AI Recommendation Engine V2</h2>
                    <p style="color: #93C5FD; margin: 6px 0 0 0; font-size: 0.95rem; font-weight: 600;">
                        Single Recommendation Authority for TNPSC Nova AI • Deterministic Priority Cascade
                    </p>
                </div>
                <div style="background: rgba(255, 255, 255, 0.15); backdrop-filter: blur(10px); padding: 8px 16px; border-radius: 999px; font-weight: 800; font-size: 0.88rem; border: 1px solid rgba(255, 255, 255, 0.2);">
                    ⭐ Master Recommendation
                </div>
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    # 2. Fetch Master Engine Output (STRICTLY FROM ENGINE)
    from core.user_context import UserContext
    ctx = UserContext.get_or_create(user)
    rec = get_ai_recommendation(user=user, context=ctx)


    mentor_msg = rec.get("mentor_message", "Focus on your primary recommendation today.")
    benefit = rec.get("estimated_benefit", {})
    current_act = rec.get("current_action", "Complete Recovery Set")
    next_act = rec.get("next_action", "Attempt PYQ")
    explanation = rec.get("explanation", "Reasoning generated by Learning Intelligence.")
    bottleneck = rec.get("learning_bottleneck", "General")

    # 3. Section 1 - 🧠 Mentor Banner
    st.markdown(
        f"""
        <div class="nova-glass-card" style="padding: 18px 22px; margin-bottom: 20px; background: linear-gradient(135deg, rgba(239, 246, 255, 0.95), rgba(243, 232, 255, 0.95)); border: 1px solid rgba(59, 130, 246, 0.3);">
            <div style="display: flex; align-items: center; gap: 14px;">
                <div style="font-size: 2.2rem; background: #2563EB; color: white; border-radius: 50%; width: 48px; height: 48px; display: grid; place-items: center; flex-shrink: 0; box-shadow: 0 6px 16px rgba(37, 99, 235, 0.3);">
                    🧠
                </div>
                <div>
                    <div style="color: #1E40AF; font-size: 0.8rem; font-weight: 900; text-transform: uppercase; letter-spacing: 0.5px;">AI Mentor Recommendation Directives</div>
                    <div style="color: #0F172A; font-size: 1.05rem; font-weight: 850; margin-top: 2px;">
                        "{html.escape(mentor_msg)}"
                    </div>
                </div>
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    # 4. Section 2 - ⭐ Primary Recommendation Hero Card
    st.html(recommendation_hero_card_html(rec).markup)

    # 5. Section 3 - ⚠ Risk Alert & Expected Benefit Grid
    col_left, col_right = st.columns([1, 1])

    with col_left:
        st.html(recommendation_risk_alert_html(rec).markup)

    with col_right:
        st.markdown(
            f"""
            <div class="nova-glass-card" style="padding: 20px;">
                <div style="font-size: 1.02rem; font-weight: 900; color: #0F172A; margin-bottom: 12px;">
                    📈 Estimated Learning Benefit
                </div>
                <div style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 10px;">
                    <div style="background: rgba(34, 197, 94, 0.08); padding: 10px; border-radius: 10px; border: 1px solid rgba(34, 197, 94, 0.2); text-align: center;">
                        <span style="color: #166534; font-size: 0.75rem; font-weight: 800; text-transform: uppercase; display: block;">Mastery Gain</span>
                        <span style="color: #16A34A; font-size: 1.5rem; font-weight: 950;">{html.escape(str(benefit.get('mastery', '+10%')))}</span>
                    </div>
                    <div style="background: rgba(245, 158, 11, 0.08); padding: 10px; border-radius: 10px; border: 1px solid rgba(245, 158, 11, 0.2); text-align: center;">
                        <span style="color: #B45309; font-size: 0.75rem; font-weight: 800; text-transform: uppercase; display: block;">XP Reward</span>
                        <span style="color: #D97706; font-size: 1.5rem; font-weight: 950;">{html.escape(str(benefit.get('xp', '+40 XP')))}</span>
                    </div>
                </div>
                <div style="margin-top: 10px; color: #475569; font-size: 0.84rem; font-weight: 750; background: rgba(248, 250, 252, 0.9); padding: 8px 12px; border-radius: 8px; border: 1px solid #E2E8F0;">
                    🛡️ <strong>Confidence Indicator:</strong> {html.escape(str(benefit.get('confidence', 'High Confidence')))}
                </div>
            </div>
            """,
            unsafe_allow_html=True,
        )

    st.write("")

    # 6. Section 4 - 🎯 Current Action & ➡ Next Action Flow
    act_col1, act_col2 = st.columns(2)

    with act_col1:
        st.markdown(
            f"""
            <div class="nova-glass-card" style="padding: 20px; border-left: 5px solid #2563EB;">
                <div style="color: #2563EB; font-size: 0.8rem; font-weight: 900; text-transform: uppercase; margin-bottom: 4px;">
                    🎯 Step 1: Current Best Action
                </div>
                <div style="color: #0F172A; font-size: 1.15rem; font-weight: 950; margin-bottom: 6px;">
                    {html.escape(current_act)}
                </div>
                <div style="color: #64748B; font-size: 0.85rem; font-weight: 750;">
                    Immediate recommended focus to address primary learning needs.
                </div>
            </div>
            """,
            unsafe_allow_html=True,
        )

    with act_col2:
        st.markdown(
            f"""
            <div class="nova-glass-card" style="padding: 20px; border-left: 5px solid #10B981;">
                <div style="color: #10B981; font-size: 0.8rem; font-weight: 900; text-transform: uppercase; margin-bottom: 4px;">
                    ➡ Step 2: Next Best Action
                </div>
                <div style="color: #0F172A; font-size: 1.15rem; font-weight: 950; margin-bottom: 6px;">
                    {html.escape(next_act)}
                </div>
                <div style="color: #64748B; font-size: 0.85rem; font-weight: 750;">
                    Follow-up step once current recommendation is completed.
                </div>
            </div>
            """,
            unsafe_allow_html=True,
        )

    st.write("")

    # 7. Section 5 - 📖 Why This Recommendation? (Explanation Card)
    st.markdown(
        f"""
        <div class="nova-glass-card" style="padding: 22px;">
            <div style="font-size: 1.05rem; font-weight: 900; color: #0F172A; margin-bottom: 10px; display: flex; align-items: center; gap: 8px;">
                <span>📖 Why Was This Recommendation Selected?</span>
            </div>
            <div style="color: #334155; font-size: 0.95rem; font-weight: 750; line-height: 1.5; background: rgba(248, 250, 252, 0.9); padding: 14px 18px; border-radius: 12px; border: 1px solid #E2E8F0; margin-bottom: 12px;">
                {html.escape(explanation)}
            </div>
            <div style="display: flex; align-items: center; gap: 8px; font-size: 0.85rem; color: #64748B; font-weight: 800;">
                <span>🔍 Identified Bottleneck:</span>
                <span style="background: rgba(37, 99, 235, 0.1); color: #2563EB; padding: 2px 10px; border-radius: 6px;">
                    {html.escape(bottleneck)}
                </span>
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )
