import json
import os

from generate_all_50 import questions, make_q

# --- 41 TO 50 ---
questions.append(make_q(
    "PRE_H_041", "Amendment + Basic Structure",
    "Why did the Supreme Court observe in S.R. Bommai (1994) and Kesavananda Bharati (1973) that the addition of 'Secular' and 'Socialist' by the 42nd Amendment in 1976 was merely 'declaratory' in nature?",
    "1976 இன் 42வது திருத்தத்தால் 'மதச்சார்பற்ற' மற்றும் 'சமதர்ம' ஆகிய வார்த்தைகள் சேர்க்கப்பட்டது வெறும் 'அறிவிப்பு' தன்மையுடையது மட்டுமே என்று எஸ்.ஆர். பொம்மை (1994) மற்றும் கேசவாநந்த பாரதி (1973) வழக்குகளில் உச்ச நீதிமன்றம் ஏன் குறிப்பிட்டது?",
    "Because Articles 25 to 28 already guaranteed equal religious freedom and Directive Principles (Articles 38-39) already mandated socio-economic justice since 1950; the 42nd Amendment merely made explicit what was already implicit.",
    "ஏனெனில் உறுப்புகள் 25 முதல் 28 வரை ஏற்கனவே சமமான மத சுதந்திரத்திற்கு உத்தரவாதம் அளித்திருந்தன மற்றும் வழிகாட்டு நெறிமுறைகள் (உறுப்புகள் 38-39) 1950 முதலே சமூக-பொருளாதார நீதிக்கு ஆணையிட்டிருந்தன; 42வது திருத்தம் ஏற்கனவே மறைமுகமாக இருந்ததை வெளிப்படையாக்கியது மட்டுமே.",
    "Because the 42nd Amendment was declared completely invalid by Parliament in 1978.",
    "ஏனெனில் 42வது திருத்தம் 1978 இல் பாராளுமன்றத்தால் முற்றிலும் செல்லாதது என அறிவிக்கப்பட்டதால்.",
    "Because the terms 'Secular' and 'Socialist' apply only to Union Territories and not to States.",
    "ஏனெனில் 'மதச்சார்பற்ற' மற்றும் 'சமதர்ம' ஆகிய சொற்கள் ஒன்றிய பிரதேசங்களுக்கு மட்டுமே பொருந்தும், மாநிலங்களுக்கு அல்ல என்பதால்.",
    "Because the Preamble was drafted by British legal experts who inserted these concepts secretly in 1950.",
    "ஏனெனில் முகவுரை பிரிட்டிஷ் சட்ட நிபுணர்களால் வரைவு செய்யப்பட்டது, அவர்கள் இந்தக் கருத்துக்களை 1950 இல் இரகசியமாகச் சேர்த்தனர் என்பதால்.",
    "A",
    "The Supreme Court observed that the 42nd Amendment Act 1976 did not introduce brand new concepts into Indian constitutionalism. Articles 25 to 28 had already embodied positive secularism, and Articles 38 and 39 had already embodied democratic socialism since January 26, 1950. The 42nd Amendment merely rendered explicit what was already embedded in the Constitution's Basic Structure.",
    "42வது திருத்தச் சட்டம் 1976 இந்திய அரசியலமைப்பில் புத்தம் புதிய கருத்துக்களை அறிமுகப்படுத்தவில்லை என்று உச்ச நீதிமன்றம் குறிப்பிட்டது. உறுப்புகள் 25 முதல் 28 வரை ஏற்கனவே நேர்மறை மதச்சார்பின்மையையும், உறுப்புகள் 38 மற்றும் 39 ஏற்கனவே ஜனநாயக சோசலிசத்தையும் 1950 ஜனவரி 26 முதலே உள்ளடக்கியிருந்தன.",
    "Correct. 42nd Amendment was declaratory—made explicit what was already implicit in Articles 25-28 and DPSP.", "சரி. 42வது திருத்தம் அறிவிப்புத் தன்மையுடையது - உறுப்புகள் 25-28 மற்றும் DPSP இல் ஏற்கனவே மறைமுகமாக இருந்ததை வெளிப்படையாக்கியது.",
    "Incorrect. 42nd Amendment Preamble changes remain fully valid.", "தவறு. 42வது திருத்த முகவுரை மாற்றங்கள் முழுமையாக செல்லுபடியாகும்.",
    "Incorrect. Applies uniformly across all States and Union Territories.", "தவறு. அனைத்து மாநிலங்கள் மற்றும் ஒன்றிய பிரதேசங்களுக்கும் சீராகப் பொருந்தும்.",
    "Incorrect. Drafted by Indian Constituent Assembly.", "தவறு. இந்திய அரசியலமைப்புச் சபையால் வரைவு செய்யப்பட்டது.",
    "42nd CAA 1976 Preamble addition = Declaratory. Secularism (Art 25-28) and Socialism (Art 38-39 DPSP) existed implicitly since 1950.",
    "42வது CAA 1976 முகவுரை சேர்க்கை = அறிவிப்புத் தன்மையுடையது. மதச்சார்பின்மை (உறுப்புகள் 25-28) மற்றும் சோசலிசம் (உறுப்புகள் 38-39 DPSP) 1950 முதலே மறைமுகமாக நிலவின.",
    "42nd Constitutional Amendment is also known as the 'Mini-Constitution' due to its comprehensive nature.",
    "42வது அரசியலமைப்பு திருத்தச் சட்டம் அதன் விரிவான தன்மை காரணமாக 'மினி-அரசியலமைப்பு' என்றும் அழைக்கப்படுகிறது.",
    ["Preamble", "42nd Amendment", "Declaratory Nature", "Implicit Secularism"]
))

questions.append(make_q(
    "PRE_H_042", "Amendment + Basic Structure",
    "What is the required parliamentary procedure under Article 368 to pass a Constitutional Amendment amending the Preamble?",
    "முகவுரையைத் திருத்தும் அரசியலமைப்பு திருத்தத்தை நிறைவேற்ற உறுப்பு 368 இன் கீழ் தேவையான நாடாளுமன்ற நடைமுறை யாது?",
    "Simple majority of members present and voting in Lok Sabha only.",
    "மக்களவையில் மட்டுமே வந்து வாக்களிக்கும் உறுப்பினர்களின் எளிய பெரும்பான்மை.",
    "Special majority in both Houses of Parliament under Article 368(2) (majority of total membership + 2/3rd present and voting in each House), without requiring state ratification unless federal proviso provisions are altered.",
    "அரசியலமைப்பின் கூட்டாட்சி அமைப்பில் மாற்றங்கள் செய்தால் ஒழிய, மாநிலங்களின் ஒப்புதல் இன்றி உறுப்பு 368(2) இன் கீழ் நாடாளுமன்றத்தின் இரு அவைகளிலும் சிறப்பு பெரும்பான்மை (மொத்த உறுப்பினர்களின் பெரும்பான்மை + ஒவ்வொரு அவையிலும் வந்து வாக்களிப்பவர்களில் 2/3 பங்கு).",
    "Unanimous resolution passed by Rajya Sabha followed by Presidential Ordinance.",
    "மாநிலங்களவையில் நிறைவேற்றப்பட்ட ஏகமனதான தீர்மானத்தைத் தொடர்ந்து குடியரசுத் தலைவரின் அவசரச்சட்டம்.",
    "Ratification by three-fourths of all Gram Sabhas across India.",
    "இந்தியா முழுவதிலும் உள்ள அனைத்து கிராம சபைகளிலும் முக்கால்வாசி பேரின் ஒப்புதல்.",
    "B",
    "Amending the Preamble requires a Constitutional Amendment Bill introduced under Article 368. It must be passed in each House of Parliament by a special majority (majority of total membership of that House AND a majority of not less than two-thirds of the members present and voting). Unless it alters federal features specified in Article 368(2) proviso, ratification by state legislatures is not required.",
    "முகவுரையைத் திருத்த உறுப்பு 368 இன் கீழ் அரசியலமைப்பு திருத்த மசோதா தேவை. இது நாடாளுமன்றத்தின் ஒவ்வொரு அவையிலும் சிறப்பு பெரும்பான்மையால் நிறைவேற்றப்பட வேண்டும்.",
    "Incorrect. Simple majority is insufficient for Art 368 constitutional amendments.", "தவறு. உறுப்பு 368 அரசியலமைப்பு திருத்தங்களுக்கு எளிய பெரும்பான்மை போதாது.",
    "Correct. Preamble amendment requires Art 368(2) Special Majority in both Houses of Parliament.", "சரி. முகவுரை திருத்தத்திற்கு இரு அவைகளிலும் உறுப்பு 368(2) சிறப்பு பெரும்பான்மை தேவை.",
    "Incorrect. Ordinances cannot amend the Constitution.", "தவறு. அவசரச்சட்டங்கள் அரசியலமைப்பைத் திருத்த முடியாது.",
    "Incorrect. Gram Sabha ratification is not part of Article 368.", "தவறு. கிராம சபை ஒப்புதல் உறுப்பு 368 இன் பகுதியல்ல.",
    "Amending Preamble Procedure = Article 368(2) Special Majority in BOTH Houses of Parliament.",
    "முகவுரை திருத்தும் நடைமுறை = நாடாளுமன்றத்தின் இரு அவைகளிலும் உறுப்பு 368(2) சிறப்பு பெரும்பான்மை.",
    "42nd Amendment Act 1976 was passed by Parliament using Article 368 special majority procedure.",
    "1976 இன் 42வது திருத்தச் சட்டம் உறுப்பு 368 சிறப்பு பெரும்பான்மை நடைமுறையைப் பயன்படுத்தி நாடாளுமன்றத்தால் நிறைவேற்றப்பட்டது.",
    ["Preamble", "Article 368 Procedure", "Special Majority", "Constitutional Amendment"]
))

questions.append(make_q(
    "PRE_H_043", "Application / Hypothetical",
    "A welfare statute enacted by a State Legislature contains ambiguous phrasing regarding worker pension eligibility. Two interpretations are possible: one restricts pension to a narrow class, while the other advances 'Social and Economic Justice'. How should the High Court apply the Preamble?",
    "ஒரு மாநில சட்டமன்றத்தால் இயற்றப்பட்ட நலத்திட்டச் சட்டம் தொழிலாளர் ஓய்வூதியத் தகுதி குறித்து தெளிவற்ற சொற்றொடரைக் கொண்டுள்ளது. இரு விளக்கங்கள் சாத்தியம்: ஒன்று ஓய்வூதியத்தை ஒரு குறுகிய வகுப்பிற்கு மட்டுமே கட்டுப்படுத்துகிறது, மற்றொன்று 'சமூக மற்றும் பொருளாதார நீதியை' முன்னேற்றுகிறது. உயர் நீதிமன்றம் முகவுரையை எவ்வாறு பயன்படுத்த வேண்டும்?",
    "The High Court must apply the restrictive interpretation to minimize state expenditure regardless of welfare intent.",
    "நலத்திட்ட நோக்கத்தைப் பொருட்படுத்தாமல் அரசுச் செலவைக் குறைக்க உயர் நீதிமன்றம் கட்டுப்பாடான விளக்கத்தைப் பயன்படுத்த வேண்டும்.",
    "The High Court must declare the entire statute unconstitutional and void for vagueness.",
    "தெளிவின்மைக்காக முழுச் சட்டமும் அரசியலமைப்புக்கு முரணானது மற்றும் செல்லாது என்று உயர் நீதிமன்றம் அறிவிக்க வேண்டும்.",
    "The High Court must adopt the interpretation that advances the Preamble's promise of 'Social and Economic Justice', using the Preamble as a guiding light to resolve statutory ambiguity.",
    "சட்டப்பூர்வ தெளிவின்மையைத் தீர்க்க முகவுரையை ஒரு வழிகாட்டும் ஒளியாகப் பயன்படுத்தி, முகவுரையின் 'சமூக மற்றும் பொருளாதார நீதி' வாக்குறுதியை முன்னேற்றும் விளக்கத்தை உயர் நீதிமன்றம் ஏற்க வேண்டும்.",
    "The High Court must refer the matter to the British Privy Council for final determination.",
    "இறுதித் தீர்மானத்திற்காக உயர் நீதிமன்றம் இந்த விவகாரத்தை பிரிட்டிஷ் பிரிவி கவுன்சிலுக்கு அனுப்ப வேண்டும்.",
    "C",
    "It is a well-settled canon of statutory interpretation that where the language of a statute is ambiguous, courts will adopt that interpretation which aligns with the noble objectives of the Preamble (such as Social and Economic Justice). The Preamble serves as an interpretive key to resolve statutory doubt in favor of constitutional values.",
    "சட்டத்தின் மொழி தெளிவற்றதாக இருக்கும் இடங்களில், முகவுரையின் உன்னதமான இலக்குகளுடன் (சமூக மற்றும் பொருளாதார நீதி போன்றவை) ஒத்துப் போகும் விளக்கத்தை நீதிமன்றங்கள் ஏற்கும் என்பது சட்ட விளக்கத்தின் நன்கு நிறுவப்பட்ட விதியாகும்.",
    "Incorrect. Courts favor welfare interpretations over restrictive ones when ambiguity exists.", "தவறு. தெளிவின்மை நிலவும் போது நீதிமன்றங்கள் நலத்திட்ட விளக்கங்களை ஆதரிக்கின்றன.",
    "Incorrect. Mere ambiguity does not render a welfare statute void if interpretive resolution exists.", "தவறு. விளக்கத் தீர்வு இருந்தால் வெறும் தெளிவின்மை ஒரு நலச்சட்டத்தை செல்லாததாக்காது.",
    "Correct. High Court uses Preamble as an interpretive key to choose the meaning advancing Social & Economic Justice.", "சரி. உயர் நீதிமன்றம் சமூக & பொருளாதார நீதியை முன்னேற்றும் பொருளைத் தேர்ந்தெடுக்க முகவுரையை ஒரு விளக்கச் சாவியாகப் பயன்படுத்துகிறது.",
    "Incorrect. Privy Council jurisdiction was abolished in 1949.", "தவறு. பிரிவி கவுன்சில் அதிகார வரம்பு 1949 இல் ரத்து செய்யப்பட்டது.",
    "Statutory Ambiguity -> Preamble acts as an interpretive compass. Courts choose the construction promoting Preamble values (Social/Economic Justice).",
    "சட்டப்பூர்வ தெளிவின்மை -> முகவுரை ஒரு விளக்க வழாட்டியாக செயல்படுகிறது. முகவுரை மதிப்புகளை ஊக்குவிக்கும் விளக்கத்தை நீதிமன்றங்கள் தேர்ந்தெடுக்கின்றன.",
    "Abolition of Privy Council Jurisdiction Act 1949 severed all judicial appeals to London.",
    "1949 இன் பிரிவி கவுன்சில் அதிகார வரம்பு ஒழிப்புச் சட்டம் லண்டனுக்கான அனைத்து நீதித்துறை மேல்முறையீடுகளையும் துண்டித்தது.",
    ["Preamble", "Statutory Interpretation", "Social Justice", "Ambiguity Resolution"]
))

questions.append(make_q(
    "PRE_H_044", "Application / Hypothetical",
    "Suppose India ratifies a binding international treaty on carbon emission limits. Opponents challenge the treaty in court arguing it compromises 'Sovereignty' under the Preamble. How will the Supreme Court evaluate this challenge?",
    "கார்பன் உமிழ்வு வரம்புகள் குறித்த பிணைப்புறுத்தும் சர்வதேச ஒப்பந்தத்தை இந்தியா அங்கீகரிக்கிறது என்று வைத்துக்கொள்வோம். இது முகவுரையின் கீழ் உள்ள 'இறையாண்மையை' சமரசம் செய்வதாகக் கூறி எதிர்ப்பாளர்கள் நீதிமன்றத்தில் சவால் விடுகின்றனர். உச்ச நீதிமன்றம் இந்தச் சவாலை எவ்வாறு மதிப்பிடும்?",
    "The Court will strike down the treaty because sovereignty prohibits entering into any international agreement.",
    "இறையாண்மை எந்தவொரு சர்வதேச ஒப்பந்தத்திலும் ஈடுபடுவதைத் தடுப்பதால் நீதிமன்றம் ஒப்பந்தத்தை ரத்து செய்யும்.",
    "The Court will declare India a dependency of the United Nations.",
    "இந்தியா ஐக்கிய நாடுகள் சபையின் கட்டுப்பாட்டில் உள்ள நாடு என்று நீதிமன்றம் அறிவிக்கும்.",
    "The Court will rule that entering into international treaties is a voluntary exercise of external sovereignty, not a surrender of supreme constitutional legal authority.",
    "சர்வதேச ஒப்பந்தங்களில் ஈடுபடுவது வெளி இறையாண்மையின் ஒரு தன்னார்வப் பயன்பாடாகும், இது உயர்ந்த அரசியலமைப்பு சட்ட அதிகாரத்தை ஒப்படைப்பதாகாது என்று நீதிமன்றம் தீர்ப்பளிக்கும்.",
    "The Court will order the abolition of the Preamble.",
    "முகவுரையை ஒழிக்க நீதிமன்றம் உத்தரவிடும்.",
    "D",
    "As established in constitutional law, entering into treaties and international obligations is an attribute of a Sovereign State. Exercising external sovereignty by voluntarily agreeing to international norms does NOT diminish domestic legal sovereignty, provided the treaty is implemented in accordance with Article 253.",
    "அரசியலமைப்புச் சட்டத்தில் நிறுவப்பட்டுள்ளபடி, ஒப்பந்தங்கள் மற்றும் சர்வதேச கடமைகளில் ஈடுபடுவது ஒரு இறையாண்மையுள்ள அரசின் பண்பாகும். சர்வதேச விதிகளுக்குத் தன்னார்வமாக உடன்படுவதன் மூலம் வெளி இறையாண்மையைப்பயன்படுத்துவது உள்நாட்டுச் சட்ட இறையாண்மையைக் குறைக்காது.",
    "Incorrect. Sovereign states routinely make treaties.", "தவறு. இறையாண்மையுள்ள அரசுகள் வழக்கமாக ஒப்பந்தங்களைச் செய்கின்றன.",
    "Incorrect. Treaty ratification does not turn India into a dependency.", "தவறு. ஒப்பந்த அங்கீகாரம் இந்தியாவை சார்புநாடாக மாற்றாது.",
    "Incorrect. Misidentifies the correct option position.", "தவறு. சரியான தேர்வை தவறாக அடையாளப்படுத்துகிறது.",
    "Correct. Voluntary international treaty execution = positive exercise of Sovereignty (NOT surrender of sovereignty).", "சரி. தன்னார்வ சர்வதேச ஒப்பந்த அமலாக்கம் = இறையாண்மையின் நேர்மறைப் பயன்பாடு.",
    "International Treaty Ratification = Exercise of External Sovereignty (NOT loss of sovereignty). Article 253 governs domestic enabling laws.",
    "சர்வதேச ஒப்பந்த அங்கீகாரம் = வெளி இறையாண்மையின் பயன்பாடு (இறையாண்மை இழப்பு அல்ல). உறுப்பு 253 உள்நாட்டுச் சட்டங்களை நிர்வகிக்கிறது.",
    "Article 253 empowers Parliament to make any law for implementing international treaties.",
    "உறுப்பு 253 சர்வதேச ஒப்பந்தங்களைச் செயல்படுத்துவதற்கான எந்தவொரு சட்டத்தையும் இயற்ற நாடாளுமன்றத்திற்கு அதிகாரம் அளிக்கிறது.",
    ["Preamble", "Sovereignty", "International Treaties", "Article 253"]
))

questions.append(make_q(
    "PRE_H_045", "Application / Hypothetical",
    "A State Government enacts a policy offering reserved quota in government supply contracts for socially backward artisans. A private contractor challenges it under 'Equality of Opportunity'. How will the constitutional court resolve this conflict?",
    "சமூக ரீதியாக பின்தங்கிய கைவினைஞர்களுக்கு அரசு விநியோக ஒப்பந்தங்களில் இடஒதுக்கீடு வழங்கும் கொள்கையை ஒரு மாநில அரசு இயற்றுகிறது. ஒரு தனியார் ஒப்பந்ததாரர் 'வாய்ப்பில் சமத்துவம்' என்பதன் கீழ் இதற்கு சவால் விடுகிறார். அரசியலமைப்பு நீதிமன்றம் இந்த மோதலை எவ்வாறு தீர்க்கும்?",
    "The Court will uphold the policy as an instrument achieving substantive equality of opportunity under the Preamble and Articles 15(4)/16(4), placing disadvantaged classes on equal footing.",
    "முகவுரை மற்றும் உறுப்புகள் 15(4)/16(4) இன் கீழ் பின்தங்கிய வகுப்பினரை சமமான நிலையில் வைப்பதன் மூலம் நடைமுறைச் சமத்துவத்தை அடையும் ஒரு கருவியாக நீதிமன்றம் கொள்கையை உறுதி செய்யும்.",
    "The Court will declare all reservations in commercial contracts unconstitutional per se.",
    "வணிக ஒப்பந்தங்களில் உள்ள அனைத்து இடஒதுக்கீடுகளும் அரசியலமைப்புக்கு முரணானவை என நீதிமன்றம் அறிவிக்கும்.",
    "The Court will rule that equality requires strict mathematical identity of opportunity regardless of historical social discrimination.",
    "வரலாற்றுச் சமூகப் பாகுபாட்டைப் பொருட்படுத்தாமல் சமத்துவத்திற்குக் கடுமையான கணிதச் சம வாய்ப்பு தேவை என்று நீதிமன்றம் தீர்ப்பளிக்கும்.",
    "The Court will refer the contractor to the International Court of Justice.",
    "நீதிமன்றம் ஒப்பந்ததாரரை சர்வதேச நீதிமன்றத்திற்கு அனுப்பும்.",
    "A",
    "Constitutional equality is substantive, not merely formal. Equality of status and opportunity in the Preamble, read with Articles 15(4), 16(4), and Directive Principles, permits the State to grant affirmative assistance (protective discrimination) to historically disadvantaged groups to enable them to compete on an equal footing.",
    "அரசியலமைப்பு சமத்துவம் நடைமுறைச் சார்ந்ததே தவிர வெறும் முறையானது அல்ல. உறுப்புகள் 15(4), 16(4) உடன் சேர்த்துப் படிக்கப்படும் முகவுரையில் உள்ள தகுதி மற்றும் வாய்ப்பில் சமத்துவம், பின்தங்கிய குழுக்களுக்கு நேர்மறை உதவியை வழங்க அரசை அனுமதிக்கிறது.",
    "Correct. Protective discrimination achieves substantive equality of opportunity contemplated by the Preamble.", "சரி. பாதுகாப்பு பாகுபாடு முகவுரையால் உத்தேசிக்கப்பட்ட நடைமுறைச் சமத்துவத்தை அடைகிறது.",
    "Incorrect. Affirmative action schemes have been upheld by Supreme Court when backed by social data.", "தவறு. சமூகத் தரவுகளின் ஆதரவுடன் நேர்மறை நடவடிக்கை திட்டங்கள் உச்ச நீதிமன்றத்தால் உறுதி செய்யப்பட்டுள்ளன.",
    "Incorrect. Formal identity of treatment perpetuates underlying inequality.", "தவறு. முறையான சிகிச்சை ஏற்றத்தாழ்வை நீடிக்கச் செய்கிறது.",
    "Incorrect. ICJ has no jurisdiction over domestic constitutional disputes.", "தவறு. உள்நாட்டு அரசியலமைப்பு வழக்குகளில் ICJ க்கு அதிகார வரம்பு இல்லை.",
    "Preamble Equality of Opportunity = Substantive Equality (Permits affirmative action/protective discrimination for backward classes).",
    "முகவுரை வாய்ப்பில் சமத்துவம் = நடைமுறைச் சமத்துவம் (பின்தங்கிய வகுப்பினருக்கான நேர்மறை நடவடிக்கையை அனுமதிக்கிறது).",
    "Indira Sawhney case (1992) established the 50% ceiling rule for reservations while upholding affirmative action.",
    "இந்திரா சாவ்னி வழக்கு (1992) நேர்மறை நடவடிக்கையை உறுதி செய்யும் அதே வேளையில் இடஒதுக்கீட்டிற்கான 50% உச்சவரம்பு விதியை நிறுவியது.",
    ["Preamble", "Equality of Opportunity", "Affirmative Action", "Substantive Equality"]
))

questions.append(make_q(
    "PRE_H_046", "Application / Hypothetical",
    "During a severe public health epidemic, a District Magistrate bans all large public religious gatherings. A religious group challenges the order claiming violation of the Preamble's promise of 'Liberty of Worship'. What will be the Court's verdict?",
    "ஒரு கடுமையான பொது சுகாதார நோய்த்தொற்றின் போது, ஒரு மாவட்ட ஆட்சியர் அனைத்து பெரிய பொது மதக் கூட்டங்களையும் தடை செய்கிறார். முகவுரையின் 'வழிபாட்டு சுதந்திரம்' வாக்குறுதியை மீறுவதாகக் கூறி ஒரு மதக் குழு இந்த உத்தரவைச் சவால் செய்கிறது. நீதிமன்றத்தின் தீர்ப்பு என்னவாக இருக்கும்?",
    "The Court will strike down the Magistrate's order because Preamble liberty of worship is absolute and unrestrictable.",
    "முகவுரை வழிபாட்டு சுதந்திரம் வரம்பற்றது என்பதால் ஆட்சியரின் உத்தரவை நீதிமன்றம் ரத்து செய்யும்.",
    "The Court will uphold the Magistrate's order because liberty of worship under Article 25(1) is explicitly subject to public order, morality, and health.",
    "உறுப்பு 25(1) இன் கீழ் வழிபாட்டு சுதந்திரம் பொது ஒழுங்கு, ஒழுக்கம் மற்றும் சுகாதாரத்திற்கு உட்பட்டது என்பதால் நீதிமன்றம் ஆட்சியரின் உத்தரவை உறுதி செய்யும்.",
    "The Court will abolish the office of District Magistrate for interfering with religion.",
    "மதத்தில் தலையிட்டதற்காக மாவட்ட ஆட்சியர் அலுவலகத்தை நீதிமன்றம் ஒழிக்கும்.",
    "The Court will declare the Preamble suspended during health emergencies.",
    "சுகாதார அவசரநிலைகளின் போது முகவுரை நிறுத்தி வைக்கப்பட்டுள்ளதாக நீதிமன்றம் அறிவிக்கும்.",
    "B",
    "Liberty of thought, expression, belief, faith and worship in the Preamble is operationalized through Article 25(1), which explicitly states that freedom of religion is 'subject to public order, morality and health'. Therefore, reasonable restrictions imposed by authorities to protect public health during an epidemic are constitutionally valid.",
    "முகவுரையில் உள்ள வழிபாட்டு சுதந்திரம் உறுப்பு 25(1) மூலம் நடைமுறைப்படுத்தப்படுகிறது, இது மத சுதந்திரம் 'பொது ஒழுங்கு, ஒழுக்கம் மற்றும் சுகாதாரத்திற்கு உட்பட்டது' என்று வெளிப்படையாகக் கூறுகிறது. எனவே, சுகாதாரத்தைப் பாதுகாக்க விதிக்கப்படும் நியாயமான கட்டுப்பாடுகள் அரசியலமைப்பு ரீதியாக செல்லுபடியாகும்.",
    "Incorrect. Preamble liberty is qualified, not absolute.", "தவறு. முகவுரை சுதந்திரம் வரம்பிற்குட்பட்டது.",
    "Correct. Liberty of worship under Art 25(1) is explicitly subject to Public Health, Order, and Morality.", "சரி. உறுப்பு 25(1) இன் கீழ் வழிபாட்டு சுதந்திரம் பொது சுகாதாரம், ஒழுங்கு மற்றும் ஒழுக்கத்திற்கு உட்பட்டது.",
    "Incorrect. DM acts within statutory powers under Epidemic Diseases Act / Disaster Management Act.", "தவறு. மாவட்ட ஆட்சியர் சட்டப்பூர்வ அதிகாரங்களுக்குள் செயல்படுகிறார்.",
    "Incorrect. Emergency procedures do not abolish the Preamble.", "தவறு. அவசரநிலை நடைமுறைகள் முகவுரையை ஒழிப்பதில்லை.",
    "Liberty of Worship in Preamble = Qualified right under Article 25(1), subject to Public Order, Morality, and Health.",
    "முகவுரையில் வழிபாட்டு சுதந்திரம் = உறுப்பு 25(1) இன் கீழ் தகுதியுள்ள உரிமை, பொது ஒழுங்கு, ஒழுக்கம் மற்றும் சுகாதாரத்திற்கு உட்பட்டது.",
    "Article 25(1) begins with the clause: 'Subject to public order, morality and health...'",
    "உறுப்பு 25(1) 'பொது ஒழுங்கு, ஒழுக்கம் மற்றும் சுகாதாரத்திற்கு உட்பட்டு...' என்ற விதியுடன் தொடங்குகிறது.",
    ["Preamble", "Liberty of Worship", "Article 25(1)", "Public Health Restrictions"]
))

questions.append(make_q(
    "PRE_H_047", "High-level TNPSC Trap",
    "Which of the following correctly identifies the precise constitutional distinction between November 26, 1949 and January 26, 1950?",
    "நவம்பர் 26, 1949 மற்றும் ஜனவரி 26, 1950 ஆகியவற்றுக்கு இடையேயான துல்லியமான அரசியலமைப்பு வேறுபாட்டை பின்வருவனவற்றில் எது சரியாக அடையாளம் காட்டுகிறது?",
    "November 26, 1949 is the date of commencement of the Constitution, whereas January 26, 1950 is the date of adoption recorded in the Preamble.",
    "நவம்பர் 26, 1949 என்பது அரசியலமைப்பு அமலுக்கு வந்த நாள், ஆனால் ஜனவரி 26, 1950 என்பது முகவுரையில் பதிவு செய்யப்பட்ட ஏற்றுக்கொள்ளப்பட்ட நாள்.",
    "November 26, 1949 is the date when the Objectives Resolution was moved by Nehru, whereas January 26, 1950 is the date of 42nd Amendment.",
    "நவம்பர் 26, 1949 என்பது நேரு குறிக்கோள் தீர்மானத்தை முன்மொழிந்த நாள், ஆனால் ஜனவரி 26, 1950 என்பது 42வது திருத்தத்தின் நாள்.",
    "November 26, 1949 is the date explicitly mentioned IN the Preamble as the date of adoption, enactment and self-giving of the Constitution, whereas January 26, 1950 is the date of commencement of the Constitution (Article 394).",
    "நவம்பர் 26, 1949 என்பது அரசியலமைப்பை ஏற்று, இயற்றி, நமக்கே அளித்துக் கொண்ட நாளாக முகவுரையிலேயே வெளிப்படையாகக் குறிப்பிடப்பட்டுள்ள நாள்; ஆனால் ஜனவரி 26, 1950 என்பது அரசியலமைப்பு அமலுக்கு வந்த நாளாகும் (உறுப்பு 394).",
    "Both dates represent identical legal milestones with no constitutional distinction.",
    "இரு நாட்களும் அரசியலமைப்பு வேறுபாடு ஏதுமின்றி ஒரே மாதிரியான சட்ட மைல்கற்களைப் பிரதிநிதித்துவப்படுத்துகின்றன.",
    "C",
    "The Preamble explicitly records: 'IN OUR CONSTITUENT ASSEMBLY this twenty-sixth day of November, 1949, do HEREBY ADOPT, ENACT AND GIVE TO OURSELVES THIS CONSTITUTION.' However, Article 394 specifies January 26, 1950 as the 'date of commencement' of the Constitution as a whole (though Articles 5, 6, 7, 8, 9, 60, 324, 366, 379, 380, 388, 391, 392, 393 came into force immediately on Nov 26, 1949).",
    "முகவுரை 26 நவம்பர் 1949 ஐ ஏற்றுக்கொள்ளப்பட்ட, இயற்றப்பட்ட நாளாக வெளிப்படையாகப் பதிவு செய்கிறது. இருப்பினும், உறுப்பு 394 ஜனவரி 26, 1950 ஐ அரசியலமைப்பு முழுமையாக அமலுக்கு வந்த நாளாகக் குறிப்பிடுகிறது.",
    "Incorrect. Reverses the two dates.", "தவறு. இரு நாட்களையும் தலைகீழாக மாற்றுகிறது.",
    "Incorrect. Objectives Resolution was moved on Dec 13, 1946; 42nd CAA was passed in 1976.", "தவறு. குறிக்கோள் தீர்மானம் முன்மொழியப்பட்டது டிசம்பர் 13, 1946.",
    "Correct. Nov 26, 1949 = Date in Preamble (Adoption/Enactment). Jan 26, 1950 = Date of Commencement (Art 394).", "சரி. 26 நவம்பர் 1949 = முகவுரையில் உள்ள நாள். 26 ஜனவரி 1950 = அமலுக்கு வந்த நாள்.",
    "Incorrect. The two dates represent distinct legal milestones under Article 394.", "தவறு. இரு நாட்களும் உறுப்பு 394 இன் கீழ் வேறுபட்ட சட்ட மைல்கற்களைக் குறிக்கின்றன.",
    "TNPSC Trap: Date IN Preamble = 26th November 1949 (Adoption & Enactment). Date of Commencement = 26th January 1950 (Article 394).",
    "TNPSC பொறி: முகவுரையில் உள்ள நாள் = 26 நவம்பர் 1949 (ஏற்றுக்கொள்ளப்பட்ட நாள்). அமலுக்கு வந்த நாள் = 26 ஜனவரி 1950 (உறுப்பு 394).",
    "Constitution Day (Samvidhan Divas) is celebrated in India on November 26 every year.",
    "இந்தியாவில் ஒவ்வொரு ஆண்டும் நவம்பர் 26 அன்று அரசியலமைப்பு தினம் (சம்விதான் திவாஸ்) கொண்டாடப்படுகிறது.",
    ["Preamble", "November 26 1949", "January 26 1950", "Date of Adoption", "Constitution Day"]
))

questions.append(make_q(
    "PRE_H_048", "High-level TNPSC Trap",
    "What is the exact text placement of the three words added to the Preamble by the 42nd Constitutional Amendment Act, 1976?",
    "1976 இன் 42வது அரசியலமைப்பு திருத்தச் சட்டத்தால் முகவுரையில் சேர்க்கப்பட்ட மூன்று சொற்களின் துல்லியமான உரை இடம் யாது?",
    "'Socialist' and 'Secular' were added after 'Republic', while 'Integrity' was added before 'Fraternity'.",
    "'சமதர்ம' மற்றும் 'மதச்சார்பற்ற' ஆகியவை 'குடியரசு' என்பதற்குப் பின் சேர்க்கப்பட்டன, அதே வேளையில் 'ஒருமைப்பாடு' என்பது 'சகோதரத்துவம்' என்பதற்கு முன் சேர்க்கப்பட்டது.",
    "'Socialist' and 'Secular' were added before 'Sovereign', while 'Integrity' replaced 'Unity'.",
    "'சமதர்ம' மற்றும் 'மதச்சார்பற்ற' ஆகியவை 'இறையாண்மை' என்பதற்கு முன் சேர்க்கப்பட்டன, அதே வேளையில் 'ஒருமைப்பாடு' என்பது 'ஒற்றுமை' என்பதற்குப் பதிலாக மாற்றப்பட்டது.",
    "'Socialist' replaced 'Democratic', 'Secular' replaced 'Republic', and 'Integrity' replaced 'Dignity'.",
    "'சமதர்ம' 'ஜனநாயக' என்பதற்குப் பதிலாக மாற்றப்பட்டது, 'மதச்சார்பற்ற' 'குடியரசு' என்பதற்குப் பதிலாக மாற்றப்பட்டது.",
    "'Socialist' and 'Secular' were inserted between 'Sovereign' and 'Democratic' (creating Sovereign Socialist Secular Democratic Republic), while 'and Integrity' was added after 'Unity' (creating Unity and Integrity of the Nation).",
    "'சமதர்ம' மற்றும் 'மதச்சார்பற்ற' ஆகியவை 'இறையாண்மை' மற்றும் 'ஜனநாயக' ஆகியவற்றிற்கு இடையில் செருகப்பட்டன, அதே வேளையில் 'மற்றும் ஒருமைப்பாடு' என்பது 'ஒற்றுமை' என்பதற்குப் பின் சேர்க்கப்பட்டது.",
    "D",
    "The 42nd Amendment Act 1976 made two precise textual insertions in the Preamble: (1) It substituted 'Sovereign Democratic Republic' with 'SOVEREIGN SOCIALIST SECULAR DEMOCRATIC REPUBLIC'. (2) It substituted 'unity of the Nation' with 'UNITY AND INTEGRITY OF THE NATION'.",
    "42வது திருத்தச் சட்டம் 1976 முகவுரையில் இரு துல்லியமான உரைச் செருகல்களைச் செய்தது: (1) 'இறையாண்மை ஜனநாயக குடியரசு' என்பதை 'இறையாண்மை சமதர்ம மதச்சார்பற்ற ஜனநாயக குடியரசு' என மாற்றியது. (2) 'நாட்டின் ஒற்றுமை' என்பதை 'நாட்டின் ஒற்றுமை மற்றும் ஒருமைப்பாடு' என மாற்றியது.",
    "Incorrect. Wrong textual placement.", "தவறு. தவறான உரை இடம்.",
    "Incorrect. Wrong textual placement.", "தவறு. தவறான உரை இடம்.",
    "Incorrect. Did not replace existing core terms.", "தவறு. நிலவும் முக்கிய சொற்களை மாற்றவில்லை.",
    "Correct. 'Socialist' and 'Secular' inserted between Sovereign & Democratic; 'and Integrity' inserted after Unity.", "சரி. 'சமதர்ம' & 'மதச்சார்பற்ற' இறையாண்மை & ஜனநாயக ஆகியவற்றிற்கு இடையில் செருகப்பட்டன.",
    "TNPSC Placement Trap: Sovereign -> SOCIALIST -> SECULAR -> Democratic -> Republic. Unity -> AND INTEGRITY -> of the Nation.",
    "TNPSC பொறி: இறையாண்மை -> சமதர்ம -> மதச்சார்பற்ற -> ஜனநாயக -> குடியரசு. ஒற்றுமை -> மற்றும் ஒருமைப்பாடு -> நாட்டின்.",
    "The 42nd Amendment Act 1976 was drafted based on the recommendations of Sardar Swaran Singh Committee.",
    "1976 இன் 42வது திருத்தச் சட்டம் சர்தார் ஸ்வரன் சிங் குழுவின் பரிந்துரைகளின் அடிப்படையில் வரைவு செய்யப்பட்டது.",
    ["Preamble", "42nd Amendment Placement", "Textual Structure", "S-S-S-D-R"]
))

questions.append(make_q(
    "PRE_H_049", "High-level TNPSC Trap",
    "Evaluate the truth value of the following assertion: 'Because the Preamble is non-justiciable, it possesses zero legal relevance in Indian courts and cannot be cited during constitutional litigation.'",
    "'முகவுரை நீதிமன்றத்தால் நிலைநிறுத்த முடியாதது என்பதால், அது இந்திய நீதிமன்றங்களில் சுழியம் சட்ட பொருத்தத்தைக் கொண்டுள்ளது மற்றும் அரசியலமைப்பு வழக்கின் போது மேற்கோள் காட்ட முடியாது' என்ற கூற்றின் உண்மை மதிப்பை மதிப்பிடுக:",
    "INCORRECT: While non-justiciable (meaning it cannot be independently enforced for a standalone remedy), the Preamble is legally relevant as an indispensable interpretive key to resolve ambiguities in constitutional and statutory provisions.",
    "தவறானது: நீதிமன்றத்தால் நிலைநிறுத்த முடியாதது என்றாலும், அரசியலமைப்பு மற்றும் சட்டப்பூர்வ விதிகளில் உள்ள தெளிவின்மைகளைத் தீர்க்க ஒரு இன்றியமையாத விளக்கச் சாவியாக முகவுரை சட்டப்பூர்வமாகப் பொருத்தமானது.",
    "CORRECT: Non-justiciable provisions are legally completely void and forbidden from being cited in court.",
    "சரியானது: நீதிமன்றத்தால் நிலைநிறுத்த முடியாத விதிகள் சட்டப்பூர்வமாக முற்றிலும் செல்லாதவை மற்றும் நீதிமன்றத்தில் மேற்கோள் காட்டத் தடை செய்யப்பட்டவை.",
    "CORRECT: The Supreme Court officially banned citing the Preamble in 1960.",
    "சரியானது: 1960 இல் முகவுரையை மேற்கோள் காட்டுவதை உச்ச நீதிமன்றம் உத்தியோகபூர்வமாகத் தடை செய்தது.",
    "INCORRECT: The Preamble is enforceable via Article 32 writs like any Fundamental Right.",
    "தவறானது: அடிப்படை உரிமையைப் போல உறுப்பு 32 பேராணைகள் மூலம் முகவுரை அமல்படுத்தக்கூடியது.",
    "A",
    "Non-justiciability means that a citizen cannot sue the State claiming a standalone right derived solely from the Preamble. However, non-justiciable does NOT mean legally irrelevant. As the Supreme Court affirmed in Kesavananda, Golaknath, and Bommai, the Preamble is of extreme interpretive value to decode framers' intent and clarify ambiguous statutes.",
    "நீதிமன்றத்தால் நிலைநிறுத்த முடியாதது என்பது முகவுரையிலிருந்து மட்டுமே பெறப்பட்ட ஒரு தனித்த உரிமையைக் கோரி ஒரு குடிமகன் அரசு மீது வழக்கு தொடர முடியாது என்பதாகும். இருப்பினும், அது சட்டப்பூர்வமாகப் பொருத்தமற்றது என்று பொருள் தராது.",
    "Correct. Non-justiciable != Legally Irrelevant. Preamble is an active interpretive guide.", "சரி. நீதிமன்றத்தால் நிலைநிறுத்த முடியாதது != சட்டப்பூர்வமாக பொருத்தமற்றது. முகவுரை ஒரு தீவிர விளக்க வழிகாட்டியாகும்.",
    "Incorrect. Non-justiciable text can guide judicial interpretation.", "தவறு. நிலைநிறுத்த முடியாத உரை நீதித்துறை விளக்கத்திற்கு வழிகாட்ட முடியும்.",
    "Incorrect. Citing the Preamble is standard constitutional practice.", "தவறு. முகவுரையை மேற்கோள் காட்டுவது நிலையான அரசியலமைப்பு நடைமுறையாகும்.",
    "Incorrect. Preamble is NOT enforceable via Article 32 writs directly.", "தவறு. முகவுரை உறுப்பு 32 பேராணைகள் மூலம் நேரடியாக அமல்படுத்த முடியாது.",
    "TNPSC Trap: Non-justiciable does NOT mean legally irrelevant. It CANNOT grant independent remedies, but IT CAN guide statutory/constitutional interpretation.",
    "TNPSC பொறி: நீதிமன்றத்தால் நிலைநிறுத்த முடியாதது என்பது சட்டப்பூர்வமாக பொருத்தமற்றது என்று பொருள் தராது. இது தனித்த தீர்வுகளை வழங்க முடியாது, ஆனால் சட்ட விளக்கத்திற்கு வழிகாட்ட முடியும்.",
    "Sir Alladi Krishnaswami Ayyar remarked: 'The Preamble to our Constitution expresses what we had thought or dreamed so long.'",
    "சர் அல்லாடி கிருஷ்ணசுவாமி அய்யர் குறிப்பிட்டார்: 'நமது அரசியலமைப்பின் முகவுரை நாம் இவ்வளவு காலமாக என்ன நினைத்தோம் அல்லது கனவு கண்டோம் என்பதை வெளிப்படுத்துகிறது.'",
    ["Preamble", "Non-Justiciable Trap", "Interpretive Value", "Legal Relevance"]
))

questions.append(make_q(
    "PRE_H_050", "High-level TNPSC Trap",
    "Which of the following correctly matches the EXACT sequential order of the Nature of the Indian State and the fundamental Objectives of the Constitution as set out in the Preamble?",
    "முகவுரையில் அமைக்கப்பட்டபடி இந்திய அரசின் தன்மையின் துல்லியமான வரிசையையும் அரசியலமைப்பின் அடிப்படை இலக்குகளையும் பின்வருவனவற்றில் எது சரியாகப் பொருத்துகிறது?",
    "Nature: Sovereign, Secular, Socialist, Republic, Democratic | Objectives: Liberty, Equality, Justice, Fraternity",
    "தன்மை: இறையாண்மை, மதச்சார்பற்ற, சமதர்ம, குடியரசு, ஜனநாயக | இலக்குகள்: சுதந்திரம், சமத்துவம், நீதி, சகோதரத்துவம்",
    "Nature: Sovereign, Socialist, Secular, Democratic, Republic (S-S-S-D-R) | Objectives: Justice, Liberty, Equality, Fraternity (J-L-E-F)",
    "தன்மை: இறையாண்மை, சமதர்ம, மதச்சார்பற்ற, ஜனநாயக, குடியரசு | இலக்குகள்: நீதி, சுதந்திரம், சமத்துவம், சகோதரத்துவம்",
    "Nature: Democratic, Republic, Sovereign, Socialist, Secular | Objectives: Equality, Liberty, Fraternity, Justice",
    "தன்மை: ஜனநாயக, குடியரசு, இறையாண்மை, சமதர்ம, மதச்சார்பற்ற | இலக்குகள்: சமத்துவம், சுதந்திரம், சகோதரத்துவம், நீதி",
    "Nature: Sovereign, Democratic, Republic, Socialist, Secular | Objectives: Fraternity, Justice, Liberty, Equality",
    "தன்மை: இறையாண்மை, ஜனநாயக, குடியரசு, சமதர்ம, மதச்சார்பற்ற | இலக்குகள்: சகோதரத்துவம், நீதி, சுதந்திரம், சமத்துவம்",
    "B",
    "The exact sequential order in the amended Preamble is: Nature of the State: SOVEREIGN SOCIALIST SECULAR DEMOCRATIC REPUBLIC (S-S-S-D-R). Fundamental Objectives: JUSTICE, LIBERTY, EQUALITY, FRATERNITY (J-L-E-F). Any alteration in this sequence is a standard TNPSC trap.",
    "திருத்தப்பட்ட முகவுரையில் துல்லியமான வரிசை: அரசின் தன்மை: இறையாண்மை சமதர்ம மதச்சார்பற்ற ஜனநாயக குடியரசு. அடிப்படை இலக்குகள்: நீதி, சுதந்திரம், சமத்துவம், சகோதரத்துவம்.",
    "Incorrect. Wrong order of terms.", "தவறு. சொற்களின் தவறான வரிசை.",
    "Correct. Nature = S-S-S-D-R; Objectives = J-L-E-F.", "சரி. தன்மை = இறையாண்மை சமதர்ம மதச்சார்பற்ற ஜனநாயக குடியரசு; இலக்குகள் = நீதி, சுதந்திரம், சமத்துவம், சகோதரத்துவம்.",
    "Incorrect. Permuted order.", "தவறு. மாற்றப்பட்ட வரிசை.",
    "Incorrect. Permuted order.", "தவறு. மாற்றப்பட்ட வரிசை.",
    "Gold Order Formula: Nature = S-S-S-D-R (Sovereign, Socialist, Secular, Democratic, Republic). Objectives = J-L-E-F (Justice, Liberty, Equality, Fraternity).",
    "தங்க வரிசை சூத்திரம்: தன்மை = S-S-S-D-R (இறையாண்மை, சமதர்ம, மதச்சார்பற்ற, ஜனநாயக, குடியரசு). இலக்குகள் = J-L-E-F (நீதி, சுதந்திரம், சமத்துவம், சகோதரத்துவம்).",
    "The Preamble contains 4 main ingredients: Source of Authority, Nature of Indian State, Objectives of Constitution, Date of Adoption.",
    "முகவுரையில் 4 முக்கிய கூறுகள் உள்ளன: அதிகார மூலம், இந்திய அரசின் தன்மை, அரசியலமைப்பின் இலக்குகள், ஏற்றுக்கொள்ளப்பட்ட நாள்.",
    ["Preamble", "Exact Order Trap", "S-S-S-D-R", "J-L-E-F", "Preamble Ingredients"]
))

output_path = "data/questions/polity/preamble_hard.json"
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(questions, f, ensure_ascii=False, indent=2)

print(f"✅ Successfully compiled exactly {len(questions)} questions into {output_path}")
