import json
import sys
from pathlib import Path

target_path = Path(r"c:\Users\Home\Desktop\tnpsc_ai\data\questions\polity\historical_background_hard.json")

def make_q(q_id, q_type, q_en, q_ta, opt_a_en, opt_a_ta, opt_b_en, opt_b_ta, opt_c_en, opt_c_ta, opt_d_en, opt_d_ta,
           correct_ans, exp_en, exp_ta, wno_a_en, wno_a_ta, wno_b_en, wno_b_ta, wno_c_en, wno_c_ta, wno_d_en, wno_d_ta,
           tip_en, tip_ta, rev_en, rev_ta, bloom, est_time, tags):
    opts = [
        {"id": "A", "en": opt_a_en, "ta": opt_a_ta},
        {"id": "B", "en": opt_b_en, "ta": opt_b_ta},
        {"id": "C", "en": opt_c_en, "ta": opt_c_ta},
        {"id": "D", "en": opt_d_en, "ta": opt_d_ta}
    ]
    opts_en = [opt_a_en, opt_b_en, opt_c_en, opt_d_en]
    opts_ta = [opt_a_ta, opt_b_ta, opt_c_ta, opt_d_ta]
    
    return {
        "id": q_id,
        "subject": "Polity",
        "topic": "Historical Background",
        "difficulty": "Hard",
        "question_type": q_type,
        "question": {"en": q_en, "ta": q_ta},
        "options": opts,
        "correct_answer": correct_ans,
        "explanation": {"en": exp_en, "ta": exp_ta},
        "why_not_others": {
            "A": {"en": wno_a_en, "ta": wno_a_ta},
            "B": {"en": wno_b_en, "ta": wno_b_ta},
            "C": {"en": wno_c_en, "ta": wno_c_ta},
            "D": {"en": wno_d_en, "ta": wno_d_ta}
        },
        "tnpsc_tip": {"en": tip_en, "ta": tip_ta},
        "revision_fact": {"en": rev_en, "ta": rev_ta},
        "source_reference": ["M. Laxmikanth - Indian Polity", "NCERT", "Samacheer Kalvi"],
        "bloom_level": bloom,
        "estimated_time_sec": est_time,
        "pyq_similarity": "High",
        "tags": tags,
        "question_en": q_en,
        "question_ta": q_ta,
        "options_en": opts_en,
        "options_ta": opts_ta,
        "answer": correct_ans.lower(),
        "explanation_en": exp_en,
        "explanation_ta": exp_ta
    }

questions = []

# --- 10 ADVANCED CONCEPTUAL QUESTIONS (HB_H_001 to HB_H_010) ---

questions.append(make_q(
    "HB_H_001", "Advanced Conceptual",
    "Under the Regulating Act of 1773, what was the precise legal relationship between the Supreme Court of Judicature at Fort William and the Governor-General in Council that resulted in administrative deadlock?",
    "1773 ஆம் ஆண்டின் ஒழுங்குமுறைச் சட்டத்தின் கீழ், கொல்கத்தா ஃபோர்ட் வில்லியமில் உள்ள உச்ச நீதிமன்றத்திற்கும் கவர்னர் ஜெனரல் கவுன்சிலுக்கும் இடையே நிர்வாக முட்டுக்கட்டையை ஏற்படுத்திய துல்லியமான சட்ட உறவு யாது?",
    "The Act failed to define the exact boundary of jurisdiction between the Supreme Court and the Governor-General in Council, and did not clarify whether Company servants were exempt for official acts.",
    "இச்சட்டம் உச்ச நீதிமன்றத்திற்கும் கவர்னர் ஜெனரல் கவுன்சிலுக்கும் இடையிலான அதிகார வரம்பின் துல்லியமான எல்லையை வரையறுக்கத் தவறியதுடன், கம்பெனி ஊழியர்கள் அதிகாரப்பூர்வப் பணிகளுக்கு விலக்கப்பட்டவர்களா என்பதைத் தெளிவுபடுத்தவில்லை.",
    "The Supreme Court was explicitly made superior to the Governor-General in Council in all military matters.",
    "உச்ச நீதிமன்றம் அனைத்து இராணுவ விவகாரங்களிலும் கவர்னர் ஜெனரல் கவுன்சிலை விட மேலானது என வெளிப்படையாக ஆக்கப்பட்டது.",
    "The Governor-General was given the absolute right to remove Supreme Court judges at will.",
    "கவர்னர் ஜெனரலுக்கு உச்ச நீதிமன்ற நீதிபதிகளை விரும்பியவாறு நீக்கும் முழுமையான உரிமை வழங்கப்பட்டது.",
    "The Supreme Court possessed exclusive law-making authority over the Presidencies of Bombay and Madras.",
    "பம்பாய் மற்றும் மதராஸ் மாகாணங்களின் மீது உச்ச நீதிமன்றம் மட்டுமே பிரத்யேக சட்டமியற்றும் அதிகாரத்தைக் கொண்டிருந்தது.",
    "A",
    "The 1773 Act created two parallel authorities without defining their jurisdictional boundary or whether executive revenue actions fell under Supreme Court jurisdiction. This ambiguity caused severe friction, leading to the Amending Act of 1781.",
    "1773 சட்டம் இரு இணை அதிகார அமைப்புகளை உருவாக்கியது, ஆனால் அவற்றின் அதிகார எல்லைகளையோ அல்லது வருவாய் நடவடிக்கைகள் நீதிமன்றக் கட்டுப்பாட்டில் வருமா என்பதையோ வரையறுக்கவில்லை. இதனால் ஏற்பட்ட மோதலே 1781 சமரசச் சட்டத்திற்கு வழிகோலியது.",
    "Correct. Overlapping jurisdiction and lack of clarity on official acts led to severe executive-judicial conflict.",
    "சரி. அதிகார வரம்பு தெளிவின்மையும் அதிகாரப்பூர்வ நடவடிக்கைகளுக்கான விலக்கு இன்மைமே நிர்வாக-நீதிமன்ற மோதலுக்குக் காரணமானது.",
    "Incorrect. Supreme Court had no jurisdiction over military matters.",
    "தவறு. உச்ச நீதிமன்றத்திற்கு இராணுவ விவகாரங்களில் அதிகார வரம்பு இல்லை.",
    "Incorrect. Judges could only be removed by the King-in-Council in London, not Governor-General.",
    "தவறு. நீதிபதிகளை லண்டனில் உள்ள மன்னர் மட்டுமே நீக்க முடியும், கவர்னர் ஜெனரல் அல்ல.",
    "Incorrect. Supreme Court was based in Calcutta and did not hold legislative power.",
    "தவறு. உச்ச நீதிமன்றம் கொல்கத்தாவில் அமைந்தது, அதற்கு சட்டமியற்றும் அதிகாரம் இல்லை.",
    "Key TNPSC distinction: 1773 created jurisdiction ambiguity -> 1781 Act of Settlement exempted revenue matters and official executive acts.",
    "முக்கிய TNPSC வேறுபாடு: 1773 அதிகார வரம்பு குழப்பத்தை உருவாக்கியது -> 1781 திருத்தச் சட்டம் வருவாய் மற்றும் அதிகாரப்பூர்வ பணிகளுக்கு விலக்களித்தது.",
    "Sir Elijah Impey was the first Chief Justice of the Calcutta Supreme Court established in 1774.",
    "1774 இல் அமைக்கப்பட்ட கொல்கத்தா உச்ச நீதிமன்றத்தின் முதல் தலைமை நீதிபதி சர் எலிஜா இம்பே ஆவார்.",
    "Analyze", 75, ["Polity", "Historical Background", "Regulating Act 1773", "Supreme Court Jurisdiction"]
))

questions.append(make_q(
    "HB_H_002", "Advanced Conceptual",
    "Which of the following constitutional mechanisms introduced by Pitt's India Act of 1784 ensured ultimate parliamentary supremacy of Great Britain over East India Company's Indian administration?",
    "1784 ஆம் ஆண்டின் பிட் இந்தியச் சட்டத்தால் அறிமுகப்படுத்தப்பட்ட எந்த அரசியலமைப்பு நுட்பம் கிழக்கிந்தியக் கம்பெனியின் இந்திய நிர்வாகத்தின் மீது பிரித்தானிய பாராளுமன்றத்தின் மேலாதிக்கத்தை உறுதி செய்தது?",
    "The Board of Control, comprising British Cabinet Ministers, was empowered to superintend, direct, and control all civil, military, and revenue operations of British possessions in India.",
    "பிரிட்டிஷ் அமைச்சரவை உறுப்பினர்களைக் கொண்ட கட்டுப்பாட்டு வாரியத்திற்கு, இந்தியாவில் உள்ள பிரிட்டிஷ் உடமைகளின் அனைத்து சிவில், இராணுவ மற்றும் வருவாய் நடவடிக்கைகளையும் மேற்பார்வையிடவும், வழிநடத்தவும், கட்டுப்படுத்தவும் அதிகாரம் அளிக்கப்பட்டது.",
    "The Court of Directors was made an elected body of Indian landlords.",
    "இயக்குநர்கள் அவை இந்திய நிலப்பிரபுக்களால் தேர்ந்தெடுக்கப்படும் அமைப்பாக மாற்றப்பட்டது.",
    "The British Parliament dissolved the East India Company's commercial Charter immediately.",
    "பிரிட்டிஷ் பாராளுமன்றம் கிழக்கிந்தியக் கம்பெனியின் வர்த்தக சாசனத்தை உடனடியாக ரத்து செய்தது.",
    "The Viceroy was directly appointed by the British House of Commons.",
    "வைஸ்ராய் நேரடியாக பிரிட்டிஷ் காமன்ஸ் சபையால் நியமிக்கப்பட்டார்.",
    "A",
    "Pitt's India Act 1784 established a 6-member Board of Control (including Chancellor of Exchequer and Secretary of State) giving the British Cabinet ultimate authority over Company political & military affairs in India.",
    "1784 பிட் இந்தியச் சட்டம் 6 உறுப்பினர்களைக் கொண்ட கட்டுப்பாட்டு வாரியத்தை அமைத்து பிரிட்டிஷ் அமைச்சரவைக்கு கம்பெனியின் அரசியல் மற்றும் இராணுவ விவகாரங்கள் மீது உச்ச அதிகாரத்தை வழங்கியது.",
    "Correct. Board of Control was a British government body created to control political & civil affairs.",
    "சரி. கட்டுப்பாட்டு வாரியம் என்பது பிரிட்டிஷ் அரசின் அமைப்பாகும், இது அரசியல் மற்றும் சிவில் விவகாரங்களைக் கட்டுப்படுத்த அமைந்தது.",
    "Incorrect. Court of Directors remained Company shareholders' body.",
    "தவறு. இயக்குநர்கள் அவை கம்பெனி பங்குதாரர்களின் அமைப்பாகவே இருந்தது.",
    "Incorrect. Commercial charter was not dissolved in 1784.",
    "தவறு. வர்த்தக சாசனம் 1784 இல் ரத்து செய்யப்படவில்லை.",
    "Incorrect. Viceroy post did not exist in 1784 (came in 1858).",
    "தவறு. வைஸ்ராய் பதவி 1784 இல் இல்லை (1858 இல் வந்தது).",
    "1784 Act called Company territories 'British possessions in India' for the first time, establishing Crown's supreme control.",
    "1784 சட்டம் முதன்முறையாக கம்பெனி பகுதிகளை 'இந்தியாவில் உள்ள பிரிட்டிஷ் உடமைகள்' என அழைத்து அரசின் மேலாதிக்கத்தை நிறுவியது.",
    "Pitt's India Act 1784 reduced Governor-General's Council membership from 4 to 3.",
    "1784 பிட் இந்தியச் சட்டம் கவர்னர் ஜெனரல் கவுன்சில் உறுப்பினர்களின் எண்ணிக்கையை 4 லிருந்து 3 ஆகக் குறைத்தது.",
    "Analyze", 75, ["Polity", "Historical Background", "Pitt's India Act 1784", "Board of Control"]
))

questions.append(make_q(
    "HB_H_003", "Advanced Conceptual",
    "The Charter Act of 1833 transformed the East India Company from a commercial trading body into a purely administrative body. What was the constitutional status of Company's territorial holdings under this Act?",
    "1833 ஆம் ஆண்டின் சாசனச் சட்டம் கிழக்கிந்தியக் கம்பெனியை ஒரு வர்த்தக அமைப்பிலிருந்து தூய நிர்வாக அமைப்பாக மாற்றியது. இச்சட்டத்தின் கீழ் கம்பெனியின் நிலப்பரப்பு உடமைகளின் அரசியலமைப்பு அந்தஸ்து என்னவாக இருந்தது?",
    "The Company held Indian territories 'in trust for His Majesty, His Heirs and Successors'.",
    "கம்பெனி இந்திய நிலப்பரப்புகளை 'பிரிட்டிஷ் மன்னர், அவரது வாரிசுகள் மற்றும் பின்வருபவர்களின் நம்பிக்கைப் பொறுப்பில் (trust)' மட்டுமே வைத்திருந்தது.",
    "The territories were declared an independent empire under the Governor-General.",
    "நிலப்பரப்புகள் கவர்னர் ஜெனரலின் கீழ் ஒரு சுதந்திர பேரரசாக அறிவிக்கப்பட்டன.",
    "The Company's territories were sold to the French Government.",
    "கம்பெனியின் பகுதிகள் பிரெஞ்சு அரசாங்கத்திற்கு விற்கப்பட்டன.",
    "The territories were directly divided among Indian Princely States.",
    "நிலப்பரப்புகள் நேரடியாக இந்திய சுதேச சமஸ்தானங்களுக்கு இடையே பிரிக்கப்பட்டன.",
    "A",
    "The Charter Act 1833 completely ended Company's commercial monopoly (including tea and China trade) and stated that Company's territorial holdings were held in trust for the British Crown.",
    "1833 சாசனச் சட்டம் கம்பெனியின் வர்த்தகப் பணிகளை முற்றிலும் முடித்து, இந்திய நிலப்பரப்புகள் பிரிட்டிஷ் மன்னரின் நம்பிக்கைப் பொறுப்பில் (trust) வைக்கப்பட்டுள்ளதாக அறிவித்தது.",
    "Correct. Expressed that territories were held 'in trust for His Majesty'.",
    "சரி. நிலப்பரப்புகள் பிரிட்டிஷ் மன்னரின் நம்பிக்கைப் பொறுப்பில் வைக்கப்பட்டுள்ளதாக இச்சட்டம் கூறியது.",
    "Incorrect. It did not create an independent empire.",
    "தவறு. இது சுதந்திர பேரரசை உருவாக்கவில்லை.",
    "Incorrect. No territories were sold to French.",
    "தவறு. பிரெஞ்சு அரசிற்கு எந்தப் பகுதியும் விற்கப்படவில்லை.",
    "Incorrect. Princely states were separate entities.",
    "தவறு. சுதேச சமஸ்தானங்கள் தனி அமைப்புகளாக இருந்தன.",
    "1833 Charter Act ended ALL commercial activities of EIC; 1813 ended monopoly EXCEPT Tea and China trade.",
    "1833 சட்டம் கம்பெனியின் அனைத்து வர்த்தக நடவடிக்கைகளையும் முடித்தது; 1813 சட்டம் தேயிலை, சீனா தவிர மற்றவற்றை முடித்தது.",
    "Charter Act 1833 redesignated Governor-General of Bengal as Governor-General of India (Lord William Bentinck).",
    "1833 சாசனச் சட்டம் வங்காள கவர்னர் ஜெனரலை இந்திய கவர்னர் ஜெனரலாக (வில்லியம் பென்டிங்க்) உயர்த்தியது.",
    "Analyze", 75, ["Polity", "Historical Background", "Charter Act 1833", "Trustee Status"]
))

questions.append(make_q(
    "HB_H_004", "Advanced Conceptual",
    "How did the Charter Act of 1853 introduce the seed of parliamentary democracy and institutional division of powers in India?",
    "1853 ஆம் ஆண்டின் சாசனச் சட்டம் இந்தியாவில் நாடாளுமன்ற ஜனநாயகம் மற்றும் நிறுவன அதிகாரப் பகிர்வின் விதையை எவ்வாறு விதைத்தது?",
    "It separated the legislative and executive functions of the Governor-General's Council and created a 6-member Legislative Council that adopted British parliamentary procedure for passing bills.",
    "இது கவர்னர் ஜெனரல் கவுன்சிலின் சட்டமன்ற மற்றும் நிர்வாகப் பணிகளைப் பிரித்ததுடன், மசோதாக்களை நிறைவேற்ற பிரிட்டிஷ் நாடாளுமன்ற நடைமுறையைப் பின்பற்றும் 6 உறுப்பினர்களைக் கொண்ட சட்டமன்ற கவுன்சிலை உருவாக்கியது.",
    "It established direct elections for all members of the Central Executive Council.",
    "இது மத்திய நிர்வாக கவுன்சில் உறுப்பினர்கள் அனைவருக்கும் நேரடித் தேர்தலை நிறுவியது.",
    "It granted universal adult franchise to all Indian subjects.",
    "இது அனைத்து இந்திய குடிமக்களுக்கும் உலகளாவிய வயதுவந்தோர் வாக்குரிமையை வழங்கியது.",
    "It abolished the office of Governor-General and replaced it with a Prime Minister.",
    "இது கவர்னர் ஜெனரல் பதவியை ஒழித்து அதற்குப் பதிலாக பிரதமரை நியமித்தது.",
    "A",
    "Charter Act 1853 added 6 new legislative members to GG's council, forming the Indian Legislative Council (Mini-Parliament). For the first time, law-making was conducted using parliamentary debate and committee procedures.",
    "1853 சாசனச் சட்டம் 6 புதிய சட்டமன்ற உறுப்பினர்களைச் சேர்த்து இந்திய சட்டமன்ற கவுன்சிலை ('மினி-பாராளுமன்றம்') உருவாக்கியது. முதன்முறையாக நாடாளுமன்ற விவாதம் மற்றும் குழு நடைமுறைகளுடன் சட்டமியற்றல் நடந்தது.",
    "Correct. Separated legislative and executive functions and formed the Indian Legislative Council (Mini-Parliament).",
    "சரி. சட்டமன்ற மற்றும் நிர்வாகப் பணிகளைப் பிரித்து இந்திய சட்டமன்ற கவுன்சிலை உருவாக்கியது.",
    "Incorrect. Direct elections were not introduced in 1853.",
    "தவறு. 1853 இல் நேரடித் தேர்தல் வரவில்லை.",
    "Incorrect. Adult franchise was introduced only in 1950 Constitution.",
    "தவறு. வயதுவந்தோர் வாக்குரிமை 1950 அரசியலமைப்பிலேயே வந்தது.",
    "Incorrect. Governor-General post continued.",
    "தவறு. கவர்னர் ஜெனரல் பதவி தொடர்ந்தது.",
    "The 1853 Act introduced local representation in Central Legislative Council: 4 of 6 members were nominated by provincial governments of Madras, Bombay, Bengal, and Agra.",
    "1853 சட்டம் மத்திய சட்டமன்ற கவுன்சிலில் உள்ளூர் பிரதிநிதித்துவத்தை (மதராஸ், பம்பாய், வங்காளம், ஆக்ரா) அறிமுகப்படுத்தியது.",
    "Macaulay Committee on Indian Civil Service was appointed in 1854 following Charter Act 1853.",
    "1853 சாசனச் சட்டத்தைத் தொடர்ந்து 1854 இல் இந்திய குடிமைப் பணிக்கான மெக்காலே குழு அமைக்கப்பட்டது.",
    "Analyze", 75, ["Polity", "Historical Background", "Charter Act 1853", "Mini Parliament"]
))

questions.append(make_q(
    "HB_H_005", "Advanced Conceptual",
    "What was the core constitutional rationale behind liquidating East India Company rule and passing the Government of India Act 1858?",
    "கிழக்கிந்தியக் கம்பெனி ஆட்சியை ஒழித்து 1858 இந்திய அரசுச் சட்டத்தை இயற்றியதன் மைய அரசியலமைப்புத் தர்க்கம் யாது?",
    "The Revolt of 1857 proved that a commercial trading company could no longer maintain political stability or command legitimacy over a vast empire, requiring direct sovereign governance by the Crown.",
    "1857 ஆம் ஆண்டின் புரட்சி, ஒரு வர்த்தக நிறுவனம் இனி அரசியல் ஸ்திரத்தன்மையையோ அல்லது பரந்த பேரரசின் மீதான ஆட்சிகொண்ட உரிமையையோ பராமரிக்க முடியாது என்பதை நிருபித்தது. இதனால் பிரிட்டிஷ் முடிஅரசின் நேரடி ஆட்சி அவசியமானது.",
    "The East India Company voluntarily surrendered all powers to avoid taxes.",
    "கிழக்கிந்தியக் கம்பெனி வரிகளைத் தவிர்க்க தனது அதிகாரங்களைத் தாமாக முன்வந்து துறந்தது.",
    "The Indian National Congress passed a resolution demanding direct Crown Rule.",
    "இந்திய தேசிய காங்கிரஸ் நேரடி பிரிட்டிஷ் ஆட்சியை வலியுறுத்தி தீர்மானம் நிறைவேற்றியது.",
    "The British Parliament wanted to hand over governance to Indian princely states.",
    "பிரிட்டிஷ் பாராளுமன்றம் நிர்வாகத்தை இந்திய சுதேச சமஸ்தானங்களிடம் ஒப்படைக்க விரும்பியது.",
    "A",
    "The 1857 Revolt shattered the dual government model of EIC and Board of Control. Parliament enacted GOI Act 1858 ('Act for Good Government of India') to place India directly under the British Crown via Secretary of State & Viceroy.",
    "1857 புரட்சி கம்பெனியின் இரட்டை ஆட்சியைச் சிதைத்தது. பிரிட்டிஷ் பாராளுமன்றம் 1858 அரசுச் சட்டத்தை இயற்றி இந்தியாவை நேரடியாக பிரிட்டிஷ் அரசின் கீழ் கொண்டு வந்தது.",
    "Correct. 1857 revolt proved Company rule inadequate for governing India, prompting direct Crown Takeover.",
    "சரி. 1857 கிளர்ச்சி கம்பெனி ஆட்சியின் போதாமையை நிரூபித்ததால் முடிஅரசு நேரடி ஆட்சியை ஏற்றது.",
    "Incorrect. Surrender was compulsory by British legislation, not voluntary.",
    "தவறு. அதிகாரம் சட்டத்தின் மூலம் பறிக்கப்பட்டது, தாமாகத் துறக்கப்படவில்லை.",
    "Incorrect. INC was formed in 1885, long after 1858.",
    "தவறு. காங்கிரஸ் 1885 இல் அமைந்தது, 1858 க்குப் பின்னரே.",
    "Incorrect. Parliament took control for Britain, not to hand to princely states.",
    "தவறு. அதிகாரத்தை பிரிட்டன் எடுத்ததே தவிர சுதேச சமஸ்தானங்களுக்குத் தரவில்லை.",
    "GOI Act 1858 created Secretary of State for India (Cabinet Minister in London) assisted by 15-member Council of India.",
    "1858 சட்டம் இந்திய அரசுச் செயலாளரையும் (லண்டன் அமைச்சரவை) 15 உறுப்பினர்கள் கொண்ட இந்திய கவுன்சிலையும் உருவாக்கியது.",
    "Lord Canning was the Governor-General during 1857 revolt and became first Viceroy under 1858 Act.",
    "1857 புரட்சியின் போது கவர்னர் ஜெனரலாக இருந்த கேனிங் பிரபு 1858 சட்டத்தில் முதல் வைஸ்ராயானார்.",
    "Understand", 75, ["Polity", "Historical Background", "Government of India Act 1858", "Crown Takeover"]
))

questions.append(make_q(
    "HB_H_006", "Advanced Conceptual",
    "The Indian Councils Act of 1861 is described as a constitutional watershed. Which of the following features accurately marks its role as the turning point of legislative decentralization?",
    "1861 ஆம் ஆண்டின் இந்தியக் கவுன்சில்கள் சட்டம் ஒரு அரசியலமைப்பு நீர்முனை என விவரிக்கப்படுகிறது. பின்வரும் அம்சங்களில் எது சட்டமன்ற பரவலாக்கலின் திருப்புமுனையாக அதன் பங்கைக் துல்லியமாகக் குறிக்கிறது?",
    "It reversed the centralization introduced by Charter Act 1833 by restoring law-making powers to Bombay and Madras Presidencies and providing for new councils in Bengal, NWFP, and Punjab.",
    "இது 1833 சாசனச் சட்டத்தால் கொண்டுவரப்பட்ட மத்தியமயமாக்கலைத் தலைகீழாக மாற்றி, பம்பாய் மற்றும் மதராஸ் மாகாணங்களுக்கு சட்ட அதிகாரங்களை மீண்டும் வழங்கியதுடன் வங்காளம், வடமேற்கு எல்லைப்புற மாகாணம், பஞ்சாப் ஆகியவற்றிற்கு புதிய கவுன்சில்களை அமைத்தது.",
    "It transferred full financial independence to municipal corporations.",
    "இது நகராட்சி மன்றங்களுக்கு முழு நிதிச் சுதந்திரத்தை மாற்றியது.",
    "It abolished the legislative powers of the Governor-General in Council.",
    "இது கவர்னர் ஜெனரல் கவுன்சிலின் சட்டமியற்றும் அதிகாரங்களை ஒழித்தது.",
    "It introduced direct election of provincial governors by the people.",
    "இது மக்களால் மாகாண ஆளுநர்கள் நேரடியாகத் தேர்ந்தெடுக்கப்படுவதை அறிமுகப்படுத்தியது.",
    "A",
    "Indian Councils Act 1861 reversed the centralizing trend of 1833 Act by restoring legislative powers to Bombay and Madras Presidencies, thereby initiating legislative decentralization that culminated in Provincial Autonomy under 1935 Act.",
    "1861 சட்டம் 1833 இன் மத்தியமயமாக்கல் போக்கைத் தலைகீழாக்கி பம்பாய், மதராஸின் சட்ட அதிகாரங்களை மீட்டு பரவலாக்கலைத் தொடங்கியது. இதுவே 1935 மாகாண தன்னாட்சியில் முடிவடைந்தது.",
    "Correct. Restored legislative powers to Bombay & Madras Presidencies, initiating legislative decentralization.",
    "சரி. பம்பாய் மற்றும் மதராஸ் மாகாணங்களின் சட்ட அதிகாரங்களை மீட்டு சட்டமன்ற பரவலாக்கலைத் தொடங்கியது.",
    "Incorrect. Municipal financial independence came much later.",
    "தவறு. நகராட்சி நிதி தன்னாட்சி பிற்காலத்தில் வந்தது.",
    "Incorrect. GG council legislative powers were retained and expanded.",
    "தவறு. GG கவுன்சில் சட்ட அதிகாரங்கள் தக்கவைக்கப்பட்டன.",
    "Incorrect. Provincial governors were appointed by British Crown.",
    "தவறு. மாகாண கவர்னர்கள் பிரிட்டிஷ் அரசால் நியமிக்கப்பட்டனர்.",
    "1861 Act legalized Lord Canning's Portfolio system (1859) and gave Viceroy Ordinance-making powers (valid 6 months).",
    "1861 சட்டம் கேனிங்கின் துறை ஒதுக்கீடு முறையை அங்கீகரித்ததுடன் வைஸ்ராய்க்கு அவசரச் சட்ட அதிகாரத்தை (6 மாதங்கள்) அளித்தது.",
    "1862: Lord Canning nominated Raja of Benares, Maharaja of Patiala, and Sir Dinkar Rao to Central Legislative Council.",
    "1862 இல் கேனிங் பிரபு காசி ராஜா, பாட்டியாலா மகாராஜா, சர் தினகர் ராவ் ஆகியோரை மத்திய கவுன்சிலுக்கு நியமித்தார்.",
    "Analyze", 75, ["Polity", "Historical Background", "Indian Councils Act 1861", "Decentralization Watershed"]
))

questions.append(make_q(
    "HB_H_007", "Advanced Conceptual",
    "What was the institutional mechanism by which the Indian Councils Act 1909 (Morley-Minto Reforms) institutionalized communalism in the Indian electoral framework?",
    "1909 ஆம் ஆண்டின் இந்தியக் கவுன்சில்கள் சட்டம் (மோர்லே-மிண்டோ சீர்திருத்தங்கள்) எந்த நிறுவன நுட்பத்தின் மூலம் இந்திய தேர்தல் கட்டமைப்பில் வகுப்புவாதத்தை சட்டப்பூர்வமாக்கியது?",
    "By establishing separate electorates for Muslims, wherein Muslim candidates were elected exclusively by Muslim voters, legally embedding religious identity into representation.",
    "முஸ்லிம்களுக்குத் தனித் தொகுதிகளை நிறுவியதன் மூலம், முஸ்லிம் வேட்பாளர்கள் முஸ்லிம் வாக்காளர்களால் மட்டுமே தேர்ந்தெடுக்கப்பட்டனர், இதன் மூலம் மத அடையாளத்தைப் பிரதிநிதித்துவத்தில் சட்டப்பூர்வமாகப் பதித்தது.",
    "By mandating equal seats for all religions in every constituency without separate voting.",
    "தனி வாக்களிப்பு இன்றி ஒவ்வொரு தொகுதியிலும் அனைத்து மதங்களுக்கும் சமமான இடங்களைக் கட்டாயமாக்கியதன் மூலம்.",
    "By reserving 100% of executive council seats for non-Hindus.",
    "நிர்வாகக் குழு இடங்களின் 100% ஐ இந்துக்கள் அல்லாதவர்களுக்கு ஒதுக்கியதன் மூலம்.",
    "By banning all political parties based on religion.",
    "மதத்தை அடிப்படையாகக் கொண்ட அனைத்து அரசியல் கட்சிகளையும் தடை செய்ததன் மூலம்.",
    "A",
    "Morley-Minto Reforms 1909 introduced 'separate electorates' for Muslims. This meant Muslim members were to be elected only by Muslim voters, creating communal representation and leading Lord Minto to be called 'Father of Communal Electorate'.",
    "1909 மோர்லே-மிண்டோ சீர்திருத்தங்கள் முஸ்லிம்களுக்குத் தனித் தொகுதிகளை அறிமுகப்படுத்தின. முஸ்லிம் வாக்காளர்கள் மட்டுமே முஸ்லிம் உறுப்பினர்களைத் தேர்ந்தெடுக்க முடிந்தது. இதனால் லார்ட் மிண்டோ 'வகுப்புவாதத் தொகுதிகளின் தந்தை' எனப்பட்டார்.",
    "Correct. Separate electorates created religious segregation in voting, institutionalizing communalism.",
    "சரி. தனித் தொகுதிகள் வாக்களிப்பில் மதப் பிரிவினையை உண்டாக்கி வகுப்புவாதத்தைச் சட்டப்பூர்வமாக்கின.",
    "Incorrect. Voting was separate, not joint or equal seats.",
    "தவறு. வாக்களிப்பு தனியாக இருந்தது, கூட்டுத் தொகுதி அல்ல.",
    "Incorrect. Executive council had 1 Indian (S.P. Sinha as Law Member), not 100% non-Hindu reservation.",
    "தவறு. நிர்வாகக் குழுவில் 1 இந்தியர் (எஸ்.பி. சின்ஹா) மட்டுமே நியமிக்கப்பட்டார்.",
    "Incorrect. Religion-based parties were not banned; they were fostered.",
    "தவறு. மதக் கட்சிகள் தடை செய்யப்படவில்லை, ஊக்குவிக்கப்பட்டன.",
    "Morley-Minto Reforms 1909 allowed non-official majority in Provincial Legislative Councils, but retained official majority in Central Council.",
    "1909 சட்டம் மாகாண கவுன்சில்களில் அரசுசாரா பெரும்பான்மையை அனுமதித்தது, ஆனால் மத்திய கவுன்சிலில் அரசு அதிகாரிகளின் பெரும்பான்மையைத் தக்கவைத்தது.",
    "Satyendra Prasad Sinha was the first Indian appointed to the Viceroy's Executive Council (as Law Member).",
    "சத்யேந்திர பிரசாத் சின்ஹா வைஸ்ராயின் நிர்வாகக் குழுவில் நியமிக்கப்பட்ட முதல் இந்தியர் (சட்ட உறுப்பினர்) ஆவார்.",
    "Analyze", 75, ["Polity", "Historical Background", "Indian Councils Act 1909", "Communal Electorate"]
))

questions.append(make_q(
    "HB_H_008", "Advanced Conceptual",
    "Why did the system of Dyarchy introduced at the provincial level by the Government of India Act 1919 prove functionally unworkable in practice?",
    "1919 ஆம் ஆண்டின் இந்திய அரசுச் சட்டத்தால் மாகாண மட்டத்தில் அறிமுகப்படுத்தப்பட்ட இரட்டை ஆட்சி முறை நடைமுறையில் ஏன் செயல்பட முடியாததாக மாறின?",
    "Because critical portfolios like Law & Order and Finance were classified as 'Reserved' under the non-responsible Governor's Executive Council, leaving elected Indian Ministers with 'Transferred' subjects devoid of funds and control.",
    "ஏனெனில் சட்டம்-ஒழுங்கு மற்றும் நிதி போன்ற முக்கியமான துறைகள் கவர்னரின் பொறுப்பற்ற நிர்வாகக் குழுவின் கீழ் 'ஒதுக்கப்பட்டவை' என வகைப்படுத்தப்பட்டதால், தேர்ந்தெடுக்கப்பட்ட இந்திய அமைச்சர்கள் நிதி ஆதாரங்கள் மற்றும் கட்டுப்பாடற்ற 'மாற்றப்பட்ட' துறைகளுடன் விடப்பட்டனர்.",
    "Because all provincial ministers were appointed directly by the British Prime Minister.",
    "ஏனெனில் அனைத்து மாகாண அமைச்சர்களும் நேரடியாக பிரிட்டிஷ் பிரதமரால் நியமிக்கப்பட்டனர்.",
    "Because Dyarchy applied only to Princely States and not to British Indian Presidencies.",
    "ஏனெனில் இரட்டை ஆட்சி சுதேச சமஸ்தானங்களுக்கு மட்டுமே பொருந்தியது, பிரிட்டிஷ் இந்திய மாகாணங்களுக்கு அல்ல.",
    "Because the Transferred subjects included Defense and Foreign Affairs which ministers refused to handle.",
    "ஏனெனில் மாற்றப்பட்ட துறைகளில் பாதுகாப்பு மற்றும் வெளியுறவுத்துறை இருந்தன, அவற்றை அமைச்சர்கள் கையாள மறுத்துவிட்டனர்.",
    "A",
    "GOI Act 1919 divided provincial subjects into Reserved (Finance, Land Revenue, Police - under Governor and Executive Council) and Transferred (Education, Health, Local Govt - under elected Ministers). Ministers could not execute policies in Transferred subjects because Finance was under Reserved control.",
    "1919 சட்டம் மாகாணத் துறைகளை ஒதுக்கப்பட்டவை (நிதி, காவல் - கவர்னர்/கவுன்சில்) மற்றும் மாற்றப்பட்டவை (கல்வி, சுகாதாரம் - அமைச்சர்கள்) எனப் பிரிக்கப்பட்டது. நிதி ஒதுக்கப்பட்ட துறையில் இருந்ததால் அமைச்சர்களால் செயல்பட முடியவில்லை.",
    "Correct. Division of subjects leaving Finance under Reserved control crippled Indian Ministers in Transferred subjects.",
    "சரி. நிதியை ஒதுக்கப்பட்ட பட்டியலில் வைத்திருந்தமை மாற்றப்பட்ட துறை அமைச்சர்களின் செயல்பாட்டை முடக்கியது.",
    "Incorrect. Ministers were appointed by Provincial Governor from elected legislators.",
    "தவறு. அமைச்சர்கள் மாகாண கவர்னரால் சட்டமன்ற உறுப்பினர்களிலிருந்து நியமிக்கப்பட்டனர்.",
    "Incorrect. Dyarchy applied to 8 British Indian Provinces, not Princely States.",
    "தவறு. இரட்டை ஆட்சி 8 பிரிட்டிஷ் இந்திய மாகாணங்களில் அமலானது, சுதேச சமஸ்தானங்களில் அல்ல.",
    "Incorrect. Defense and External Affairs were Central subjects, not provincial transferred subjects.",
    "தவறு. பாதுகாப்பு மற்றும் வெளியுறவு மத்தியத் துறைகளாக இருந்தன.",
    "1919 Act introduced Bicameralism at Centre (Council of State & Legislative Assembly) and set up Central PSC in 1926.",
    "1919 சட்டம் மத்திய சட்டமன்றத்தில் ஈரவை முறையைக் கொண்டு வந்ததுடன் 1926 இல் மத்திய பொதுச் சேவை ஆணையத்தை அமைத்தது.",
    "GOI Act 1919 separated Provincial Budgets from the Central Budget for the first time.",
    "1919 அரசுச் சட்டம் முதன்முறையாக மாகாண வரவு செலவுத் திட்டத்தை மத்திய வரவு செலவுத் திட்டத்திலிருந்து பிரித்தது.",
    "Analyze", 75, ["Polity", "Historical Background", "Government of India Act 1919", "Dyarchy Failure"]
))

questions.append(make_q(
    "HB_H_009", "Advanced Conceptual",
    "How did the Government of India Act 1935 restructure the division of legislative powers and pave the way for the 7th Schedule of the present Indian Constitution?",
    "1935 ஆம் ஆண்டின் இந்திய அரசுச் சட்டம் எவ்வாறு சட்ட அதிகாரப் பகிர்வை மறுசீரமைத்து தற்போதைய இந்திய அரசியலமைப்பின் 7வது அட்டவணைக்கு வழியமைத்தது?",
    "It divided powers into three distinct lists: Federal List (59 items), Provincial List (54 items), and Concurrent List (36 items), while vesting residuary powers personally in the Governor-General.",
    "இது அதிகாரங்களை மூன்று தனித்துவமான பட்டியல்களாகப் பிரித்தது: கூட்டாட்சிப் பட்டியல் (59), மாகாணப் பட்டியல் (54), மற்றும் இணைப்புப் பட்டியல் (36); அதே வேளையில் எஞ்சிய அதிகாரங்களை கவர்னர் ஜெனரலிடம் தனிப்பட்ட முறையில் ஒப்படைத்தது.",
    "It abolished all provincial law-making powers and concentrated 100% legislative authority in the Central Parliament.",
    "இது அனைத்து மாகாண சட்டமியற்றும் அதிகாரங்களையும் ஒழித்து 100% சட்ட அதிகாரத்தையும் மத்திய பாராளுமன்றத்தில் குவித்தது.",
    "It gave absolute legislative powers to the Federal Court to frame all statutes.",
    "இது அனைத்து சட்டங்களையும் வரைவு செய்ய கூட்டாட்சி நீதிமன்றத்திற்கு முழுமையான சட்ட அதிகாரங்களை வழங்கியது.",
    "It created a single unified list managed jointly by Princely States and the British Crown.",
    "இது சுதேச சமஸ்தானங்கள் மற்றும் பிரிட்டிஷ் முடிஅரசால் கூட்டாக நிர்வகிக்கப்படும் ஒற்றை ஒருங்கிணைக்கப்பட்ட பட்டியலை உருவாக்கியது.",
    "A",
    "GOI Act 1935 created a 3-tier distribution of powers: Federal List (59), Provincial List (54), and Concurrent List (36). Residuary powers were given to Viceroy (GG). This exact 3-list structure formed the basis of 7th Schedule in 1950 Constitution.",
    "1935 சட்டம் அதிகாரங்களை 3 பட்டியல்களாகப் பிரித்தது: கூட்டாட்சி (59), மாகாணம் (54), இணைப்பு (36). எஞ்சிய அதிகாரம் வைஸ்ராயிடம் இருந்தது. இக்கட்டமைப்பே 1950 அரசியலமைப்பின் 7வது அட்டவணைக்கு அடிப்படையானது.",
    "Correct. Divided legislative subjects into Federal, Provincial, and Concurrent lists with Residuary to GG.",
    "சரி. அதிகாரங்களை கூட்டாட்சி, மாகாணம், இணைப்பு எனப் பிரித்து எஞ்சிய அதிகாரத்தை கவர்னர் ஜெனரலிடம் அளித்தது.",
    "Incorrect. Provincial autonomy granted full legislative power over Provincial list to provinces.",
    "தவறு. மாகாண தன்னாட்சி மாகாணப் பட்டியலின் மீது முழு சட்ட அதிகாரத்தை மாகாணங்களுக்கு வழங்கியது.",
    "Incorrect. Federal Court was judicial, not legislative.",
    "தவறு. கூட்டாட்சி நீதிமன்றம் நீதித்துறை அமைப்பாகும்.",
    "Incorrect. It created three lists, not a single unified list.",
    "தவறு. இது மூன்று பட்டியல்களை உருவாக்கியது, ஒற்றைப் பட்டியலை அல்ல.",
    "TNPSC Trap: In 1935 Act, Residuary Powers were with Viceroy (GG). In 1950 Indian Constitution, Residuary Powers belong to Parliament (Article 248).",
    "TNPSC பொறி: 1935 சட்டத்தில் எஞ்சிய அதிகாரங்கள் வைஸ்ராயிடம் இருந்தன. 1950 அரசியலமைப்பில் எஞ்சிய அதிகாரங்கள் பாராளுமன்றத்திடம் உள்ளன (பிரிவு 248).",
    "Government of India Act 1935 established Federal Court in 1937 and Reserve Bank of India in 1935.",
    "1935 இந்திய அரசுச் சட்டம் 1937 இல் கூட்டாட்சி நீதிமன்றத்தையும் 1935 இல் ரிசர்வ் வங்கியையும் நிறுவியது.",
    "Analyze", 75, ["Polity", "Historical Background", "Government of India Act 1935", "3 Lists Division"]
))

questions.append(make_q(
    "HB_H_010", "Advanced Conceptual",
    "What was the specific statutory provision of the Indian Independence Act of 1947 that established the absolute sovereignty of the Constituent Assembly of India?",
    "இந்திய அரசியலமைப்பு சபையின் முழுமையான இறையாண்மையை நிறுவிய 1947 ஆம் ஆண்டின் இந்திய சுதந்திரச் சட்டத்தின் குறிப்பிட்ட சட்டப்பூர்வப் பிரிவு யாது?",
    "Section 6 of the Act declared that the Constituent Assembly had full power to make laws for the Dominion, alter or repeal any Act of British Parliament applying to India, and that no British Act passed after August 15, 1947 would extend to India.",
    "இச்சட்டத்தின் பிரிவு 6, அரசியலமைப்பு சபை டொமினியனுக்கான சட்டங்களை இயற்றவும், இந்தியாவில் பொருந்தும் எந்தவொரு பிரிட்டிஷ் சட்டத்தையும் மாற்றவும் அல்லது ரத்து செய்யவும் முழு அதிகாரம் கொண்டது என்றும், ஆகஸ்ட் 15, 1947க்கு பிறகு நிறைவேற்றப்பட்ட எந்த பிரிட்டிஷ் சட்டமும் இந்தியாவிற்குப் பொருந்தாது என்றும் அறிவித்தது.",
    "The Act declared the British Sovereign as the permanent hereditary Monarch of India.",
    "இச்சட்டம் பிரிட்டிஷ் மன்னரை இந்தியாவின் நிரந்தர பரம்பரை மன்னராக அறிவித்தது.",
    "The Act mandated that all Indian laws must be ratified by the House of Commons.",
    "இந்தியச் சட்டங்கள் அனைத்தும் காமன்ஸ் சபையால் அங்கீகரிக்கப்பட வேண்டும் என்று இச்சட்டம் கட்டாயப்படுத்தியது.",
    "The Act abolished the Constituent Assembly and transferred sovereignty to the Privy Council.",
    "இச்சட்டம் அரசியலமைப்பு சபையைக் கலைத்து இறையாண்மையை பிரிவி கவுன்சிலுக்கு மாற்றியது.",
    "A",
    "Section 6 of the Indian Independence Act 1947 granted total legislative sovereignty to the Constituent Assembly, empowering it to frame any Constitution and repeal any British Parliamentary Act (including Independence Act itself).",
    "1947 இந்திய சுதந்திரச் சட்டத்தின் பிரிவு 6 அரசியலமைப்பு சபைக்கு முழு சட்ட இறையாண்மையை வழங்கியது. சுதந்திரச் சட்டம் உட்பட எந்தவொரு பிரிட்டிஷ் சட்டத்தையும் ரத்து செய்யும் அதிகாரம் சபைக்குக் கிடைத்தது.",
    "Correct. Section 6 conferred total sovereignty and power to repeal British Acts on the Constituent Assembly.",
    "சரி. பிரிவு 6 அரசியலமைப்பு சபைக்கு முழு இறையாண்மையையும் பிரிட்டிஷ் சட்டங்களை ரத்து செய்யும் அதிகாரத்தையும் வழங்கியது.",
    "Incorrect. Monarchical rule ended on August 15, 1947.",
    "தவறு. முடியாட்சி ஆகஸ்ட் 15, 1947 இல் முடிந்தது.",
    "Incorrect. Ratification by House of Commons was abolished.",
    "தவறு. காமன்ஸ் சபை ஒப்புதல் ரத்து செய்யப்பட்டது.",
    "Incorrect. Constituent Assembly became the sovereign law-making body.",
    "தவறு. அரசியலமைப்பு சபை இறையாண்மை பெற்ற சட்ட அமைப்பானது.",
    "Indian Independence Act 1947 abolished the offices of Viceroy and Secretary of State for India.",
    "1947 இந்திய சுதந்திரச் சட்டம் வைஸ்ராய் மற்றும் இந்திய அரசுச் செயலாளர் பதவிகளை ரத்து செய்தது.",
    "Under 1947 Act, the Assembly performed dual roles: Constituent (headed by Dr. Rajendra Prasad) and Legislative (headed by G.V. Mavlankar).",
    "1947 சட்டப்படி சபை அரசியலமைப்பு உருவாக்கம் (தலைவர்: ராஜேந்திர பிரசாத்) மற்றும் சட்டமன்றப் பணி (தலைவர்: ஜி.வி. மாவ்லங்கர்) ஆகிய இரு பணிகளைச் செய்தது.",
    "Analyze", 75, ["Polity", "Historical Background", "Indian Independence Act 1947", "Sovereign Assembly"]
))

# Save checkpoint
with open(target_path, "w", encoding="utf-8") as f:
    json.dump(questions, f, ensure_ascii=False, indent=2)

print(f"Added {len(questions)} conceptual questions.")
