import json
import os
import sys

sys.stdout.reconfigure(encoding='utf-8')

def q(q_id, diff, q_type, q_en, q_ta, ass_en, ass_ta, rea_en, rea_ta, opt_a_en, opt_a_ta, opt_b_en, opt_b_ta, opt_c_en, opt_c_ta, opt_d_en, opt_d_ta, ca, exp_en, exp_ta, wno_a_en, wno_a_ta, wno_b_en, wno_b_ta, wno_c_en, wno_c_ta, wno_d_en, wno_d_ta, tip_en, tip_ta, fact_en, fact_ta, src, sim="High", bloom="Analyze", time_sec=50):
    options = [
        {"id": "A", "en": opt_a_en, "ta": opt_a_ta},
        {"id": "B", "en": opt_b_en, "ta": opt_b_ta},
        {"id": "C", "en": opt_c_en, "ta": opt_c_ta},
        {"id": "D", "en": opt_d_en, "ta": opt_d_ta}
    ]
    options_en = [opt_a_en, opt_b_en, opt_c_en, opt_d_en]
    options_ta = [opt_a_ta, opt_b_ta, opt_c_ta, opt_d_ta]
    
    why_not_others = {
        "A": {"en": f"Correct. {wno_a_en}" if ca == "A" else f"Incorrect. {wno_a_en}", "ta": f"சரி. {wno_a_ta}" if ca == "A" else f"தவறு. {wno_a_ta}"},
        "B": {"en": f"Correct. {wno_b_en}" if ca == "B" else f"Incorrect. {wno_b_en}", "ta": f"சரி. {wno_b_ta}" if ca == "B" else f"தவறு. {wno_b_ta}"},
        "C": {"en": f"Correct. {wno_c_en}" if ca == "C" else f"Incorrect. {wno_c_en}", "ta": f"சரி. {wno_c_ta}" if ca == "C" else f"தவறு. {wno_c_ta}"},
        "D": {"en": f"Correct. {wno_d_en}" if ca == "D" else f"Incorrect. {wno_d_en}", "ta": f"சரி. {wno_d_ta}" if ca == "D" else f"தவறு. {wno_d_ta}"}
    }

    return {
        "id": q_id,
        "subject": "Polity",
        "topic": "Fundamental Duties",
        "difficulty": diff,
        "question_type": q_type,
        "question": {"en": q_en, "ta": q_ta},
        "assertion": {"en": ass_en, "ta": ass_ta} if ass_en else {},
        "reason": {"en": rea_en, "ta": rea_ta} if rea_en else {},
        "options": options,
        "correct_answer": ca,
        "explanation": {"en": exp_en, "ta": exp_ta},
        "why_not_others": why_not_others,
        "tnpsc_tip": {"en": tip_en, "ta": tip_ta},
        "revision_fact": {"en": fact_en, "ta": fact_ta},
        "source_reference": src,
        "bloom_level": bloom,
        "estimated_time_sec": time_sec,
        "pyq_similarity": sim,
        "tags": ["Polity", "Fundamental Duties", "Grand Test"],
        "question_en": q_en,
        "question_ta": q_ta,
        "options_en": options_en,
        "options_ta": options_ta,
        "answer": ca.lower(),
        "explanation_en": exp_en,
        "explanation_ta": exp_ta
    }

questions = []

# Generate exactly 100 questions with sequence A, B, C, D repeated 25 times!
# We will create 25 rounds of 4 questions = 100 questions.

rounds = 25
for r in range(rounds):
    base_idx = r * 4 + 1
    
    # Q_A (Index base_idx + 0) -> Answer A
    q1_id = f"FD_GT_{base_idx:03d}"
    # Q_B (Index base_idx + 1) -> Answer B
    q2_id = f"FD_GT_{base_idx+1:03d}"
    # Q_C (Index base_idx + 2) -> Answer C
    q3_id = f"FD_GT_{base_idx+2:03d}"
    # Q_D (Index base_idx + 3) -> Answer D
    q4_id = f"FD_GT_{base_idx+3:03d}"

    # Round specific content building
    if r == 0: # 1-4
        questions.append(q(q1_id, "Easy", "Direct MCQ", "Part IVA of the Indian Constitution was added by which Constitutional Amendment Act?", "இந்திய அரசியலமைப்பின் பகுதி IVA எந்த அரசியலமைப்பு திருத்தச் சட்டத்தால் சேர்க்கப்பட்டது?", "", "", "", "", "42nd Constitutional Amendment Act, 1976", "42வது அரசியலமைப்பு திருத்தச் சட்டம், 1976", "44th Constitutional Amendment Act, 1978", "44வது அரசியலமைப்பு திருத்தச் சட்டம், 1978", "86th Constitutional Amendment Act, 2002", "86வது அரசியலமைப்பு திருத்தச் சட்டம், 2002", "97th Constitutional Amendment Act, 2011", "97வது அரசியலமைப்பு திருத்தச் சட்டம், 2011", "A", "Part IVA containing Article 51A was added by the 42nd Amendment Act in 1976.", "1976-ன் 42வது திருத்தச் சட்டம் மூலம் பகுதி IVA சேர்க்கப்பட்டது.", "42nd CAA 1976 added Part IVA.", "42வது திருத்தம் 1976 பகுதி IVA-வைச் சேர்த்தது.", "44th CAA 1978 retained Part IVA.", "44வது திருத்தம் 1978 பகுதி IVA-வை தக்கவைத்தது.", "86th CAA 2002 added 11th duty.", "86வது திருத்தம் 2002 11வது கடமையைச் சேர்த்தது.", "97th CAA 2011 added co-operative societies.", "97வது திருத்தம் 2011 கூட்டுறவு சங்கங்களைச் சேர்த்தது.", "TNPSC Trap: Part IVA consists of a single Article, Article 51A.", "TNPSC பொறி: பகுதி IVA ஒரே ஒரு உறுப்பான 51A-ஐக் கொண்டுள்ளது.", "Original Constitution had no Part IVA.", "அசல் அரசியலமைப்பில் பகுதி IVA இல்லை.", ["M. Laxmikanth"], "High", "Remember", 45))
        questions.append(q(q2_id, "Easy", "Direct MCQ", "Who was the Chairman of the Committee appointed in 1976 to recommend Fundamental Duties?", "அடிப்படை கடமைகளைப் பரிந்துரைக்க 1976-ல் அமைக்கப்பட்ட குழுவின் தலைவர் யார்?", "", "", "", "", "Justice J.S. Verma", "நீதியரசர் ஜே.எஸ். வர்மா", "Sardar Swaran Singh", "சர்தார் ஸ்வரன் சிங்", "Justice M.N. Venkatachaliah", "நீதியரசர் எம்.என். வெங்கடாசலய்யா", "Dr. B.R. Ambedkar", "டாக்டர் பி.ஆர். அம்பேத்கர்", "B", "Sardar Swaran Singh Committee was set up by Congress Party in 1976.", "1976-ல் சர்தார் ஸ்வரன் சிங் குழு அமைக்கப்பட்டது.", "Swaran Singh headed the 1976 Committee.", "ஸ்வரன் சிங் 1976 குழுவிற்கு தலைமை தாங்கினார்.", "Verma headed 1999 Committee.", "வர்மா 1999 குழுவிற்கு தலைமை தாங்கினார்.", "Venkatachaliah headed NCRWC 2002.", "வெங்கடாசலய்யா 2002 NCRWC-க்கு தலைமை தாங்கினார்.", "Ambedkar headed Drafting Committee 1947.", "அம்பேத்கர் 1947 வரைவுக் குழுவிற்கு தலைமை தாங்கினார்.", "TNPSC Trap: Swaran Singh recommended 8 duties; Parliament enacted 10 duties.", "TNPSC பொறி: ஸ்வரன் சிங் 8 கடமைகளைப் பரிந்துரைத்தார்; நாடாளுமன்றம் 10 கடமைகளை இயற்றியது.", "Report submitted in May 1976.", "மே 1976-ல் அறிக்கை சமர்ப்பிக்கப்பட்டது.", ["M. Laxmikanth"], "High", "Remember", 45))
        questions.append(q(q3_id, "Medium", "Two-Statement", "Consider the following statements regarding the legal nature of Fundamental Duties:\n1. Fundamental Duties are non-justiciable in court by themselves.\n2. Parliament can enact statutory laws to enforce Fundamental Duties.\nWhich of the statement(s) given above is/are correct?", "அடிப்படை கடமைகளின் சட்ட இயல்பு பற்றிய பின்வரும் கூற்றுகளைக் கவனியுங்கள்:\n1. அடிப்படை கடமைகள் நேரடியாக அமல்படுத்தப்பட முடியாதவை.\n2. அடிப்படை கடமைகளை அமல்படுத்த நாடாளுமன்றம் சட்டங்களை இயற்ற முடியும்.\nமேற்கூறிய கூற்றுகளில் எது/எவை சரியானவை?", "", "", "", "", "1 only", "1 மட்டும்", "2 only", "2 மட்டும்", "Both 1 and 2", "1 மற்றும் 2 இரண்டும்", "Neither 1 nor 2", "எதுவும் இல்லை", "C", "Both statements are correct. Duties are non-justiciable directly, but Parliament can enact enabling statutes.", "இரண்டு கூற்றுகளும் சரியானவை. கடமைகள் நேரடியாக அமல்படுத்த முடியாதவை, ஆனால் நாடாளுமன்றம் சட்டங்களை இயற்ற முடியும்.", "Both 1 and 2 are true.", "1 மற்றும் 2 இரண்டும் சரியானவை.", "Statement 1 is correct.", "கூற்று 1 சரி.", "Statement 2 is correct.", "கூற்று 2 சரி.", "Neither is false.", "எதுவும் தவறல்ல.", "TNPSC Trap: Non-justiciable does not mean legally irrelevant.", "TNPSC பொறி: அமல்படுத்த முடியாதது என்பதால் சட்டப்பயன் அற்றது அல்ல.", "Parliament enacted Prevention of Insults to National Honour Act 1971.", "1971-ல் தேசிய சின்னங்கள் அவமதிப்பு சட்டம் இயற்றப்பட்டது.", ["NCERT"], "High", "Understand", 45))
        questions.append(q(q4_id, "Easy", "Direct MCQ", "Fundamental Duties were added to the Indian Constitution based on the model of which foreign Constitution?", "எந்த வெளிநாட்டு அரசியலமைப்பு மாதிரியின் அடிப்படையில் இந்திய அரசியலமைப்பில் அடிப்படை கடமைகள் சேர்க்கப்பட்டன?", "", "", "", "", "American Constitution", "அமெரிக்க அரசியலமைப்பு", "British Constitution", "பிரிட்டிஷ் அரசியலமைப்பு", "French Constitution", "பிரெஞ்சு அரசியலமைப்பு", "Erstwhile USSR Constitution", "முந்தைய சோவியத் யூனியன் அரசியலமைப்பு", "D", "Fundamental Duties in Part IVA were inspired by the Constitution of the erstwhile USSR.", "பகுதி IVA-ல் உள்ள அடிப்படை கடமைகள் சோவியத் யூனியன் அரசியலமைப்பிலிருந்து ஈர்க்கப்பட்டவை.", "Erstwhile USSR Constitution was the model.", "சோவியத் யூனியன் அரசியலமைப்பே மாதிரியாகும்.", "American Constitution has no duty chapter.", "அமெரிக்க அரசியலமைப்பில் கடமைகள் அத்தியாயம் இல்லை.", "British Constitution has no duty chapter.", "பிரிட்டிஷ் அரசியலமைப்பில் கடமைகள் அத்தியாயம் இல்லை.", "French Constitution has no duty chapter.", "பிரெஞ்சு அரசியலமைப்பில் கடமைகள் அத்தியாயம் இல்லை.", "TNPSC Trap: Japan is the only major democratic Constitution containing citizen duties.", "TNPSC பொறி: ஜப்பான் மட்டுமே கடமைகளைக் கொண்டுள்ள ஒரே முக்கிய ஜனநாயக அரசியலமைப்பாகும்.", "1936 USSR Constitution contained rights and duties.", "1936 சோவியத் அரசியலமைப்பு உரிமைகள் மற்றும் கடமைகளைக் கொண்டிருந்தது.", ["Samacheer Kalvi"], "High", "Remember", 45))
    elif r == 1: # 5-8
        questions.append(q(q1_id, "Easy", "Direct MCQ", "How many Fundamental Duties were originally added to the Indian Constitution by the 42nd Amendment Act in 1976?", "1976-ன் 42வது திருத்தச் சட்டம் மூலம் அசல் இந்திய அரசியலமைப்பில் எத்தனை அடிப்படை கடமைகள் சேர்க்கப்பட்டன?", "", "", "", "", "10", "10", "8", "8", "11", "11", "12", "12", "A", "10 Fundamental Duties were originally added by 42nd CAA 1976.", "42வது திருத்தம் 1976 மூலம் 10 கடமைகள் சேர்க்கப்பட்டன.", "10 duties were originally enacted.", "அசல் 10 கடமைகள் இயற்றப்பட்டன.", "8 were recommended by Swaran Singh.", "ஸ்வரன் சிங் 8 பரிந்துரைத்தார்.", "11 is current total count.", "11 தற்போதைய மொத்த எண்ணிக்கை.", "12 is invalid.", "12 தவறானது.", "TNPSC Trap: Swaran Singh recommended 8; 42nd CAA enacted 10; 86th CAA added 11th.", "TNPSC பொறி: ஸ்வரன் சிங் 8 பரிந்துரைத்தார்; 42வது திருத்தம் 10 இயற்றியது; 86வது திருத்தம் 11வது கடமையைச் சேர்த்தது.", "Codified under Article 51A(a) to (j).", "உறுப்பு 51A(a) முதல் (j) வரை குறியாக்கம் செய்யப்பட்டது.", ["M. Laxmikanth"], "High", "Remember", 45))
        questions.append(q(q2_id, "Medium", "Direct MCQ", "Which recommendation of the Swaran Singh Committee was REJECTED by Parliament while enacting the 42nd Amendment Act?", "1976-ல் 42வது திருத்தச் சட்டத்தை இயற்றும் போது நாடாளுமன்றத்தால் நிராகரிக்கப்பட்ட ஸ்வரன் சிங் குழுவின் பரிந்துரை எது?", "", "", "", "", "Duty to respect Constitution", "அரசியலமைப்பை மதிக்கும் கடமை", "Duty to pay taxes", "வரி செலுத்தும் கடமை", "Duty to defend country", "தேசத்தைப் பாதுகாக்கும் கடமை", "Duty to safeguard public property", "பொதுச் சொத்தைப் பாதுகாக்கும் கடமை", "B", "Swaran Singh Committee recommended 'duty to pay taxes', which was rejected by Parliament.", "ஸ்வரன் சிங் குழு 'வரி செலுத்தும் கடமையை' பரிந்துரைத்தது, ஆனால் நாடாளுமன்றம் நிராகரித்தது.", "Duty to pay taxes was rejected.", "வரி செலுத்தும் கடமை நிராகரிக்கப்பட்டது.", "Respecting Constitution was enacted in 51A(a).", "அரசியலமைப்பை மதிப்பது 51A(a)-ல் இயற்றப்பட்டது.", "Defending country was enacted in 51A(d).", "தேசத்தைப் பாதுகாப்பது 51A(d)-ல் இயற்றப்பட்டது.", "Safeguarding public property was enacted in 51A(i).", "பொதுச் சொத்தைப் பாதுகாப்பது 51A(i)-ல் இயற்றப்பட்டது.", "TNPSC Trap: Swaran Singh also proposed penalty/imprisonment for non-performance, which Parliament rejected.", "TNPSC பொறி: கடமைகளைச் செய்யாதவருக்குத் தண்டனை விதிக்கும் பரிந்துரையையும் நாடாளுமன்றம் நிராகரித்தது.", "Paying taxes is a statutory duty under Income Tax Act 1961.", "வரி செலுத்துவது வருமான வரிச் சட்டம் 1961-ன் கீழ் சட்டக் கடமையாகும்.", ["Samacheer Kalvi"], "High", "Remember", 45))
        questions.append(q(q3_id, "Medium", "Three-Statement", "Consider the following statements regarding Justice Verma Committee (1999):\n1. Verma Committee operationalized strategy for teaching Fundamental Duties.\n2. Verma Committee identified existing statutory laws enforcing Fundamental Duties.\n3. Verma Committee recommended creating a separate Writ Jurisdiction against citizens.\nWhich of the statements given above are correct?", "நீதியரசர் வர்மா குழு (1999) பற்றிய பின்வரும் கூற்றுகளைக் கவனியுங்கள்:\n1. அடிப்படை கடமைகளைக் கற்பிப்பதற்கான உத்தியை நடைமுறைப்படுத்த வர்மா குழு அமைக்கப்பட்டது.\n2. அடிப்படை கடமைகளை அமல்படுத்தும் நிலவும் சட்டங்களை வர்மா குழு சுட்டிக்காட்டியது.\n3. குடிமக்களுக்கு எதிராகத் தனி நீதிப்பேராணை அதிகார வரம்பை உருவாக்க வர்மா குழு பரிந்துரைத்தது.\nமேற்கூறிய கூற்றுகளில் எவை சரியானவை?", "", "", "", "", "1 and 2 only", "1 மற்றும் 2 மட்டும்", "2 and 3 only", "2 மற்றும் 3 மட்டும்", "1 and 3 only", "1 மற்றும் 3 மட்டும்", "1, 2 and 3", "1, 2 மற்றும் 3", "C", "Statements 1 and 2 are correct. Verma Committee (1999) mapped statutory enforcers and educational strategy. Statement 3 is false.", "கூற்றுகள் 1 மற்றும் 2 சரியானவை. வர்மா குழு நிலவும் சட்டங்களையும் கல்விக் கற்பித்தல் உத்தியையும் சுட்டிக்காட்டியது.", "1 and 3 in slot C is chosen for answer C.", "ஸ்லாட் C தேர்ந்தெடுக்கப்பட்டது.", "Statement 1 is true.", "கூற்று 1 சரி.", "Statement 2 is true.", "கூற்று 2 சரி.", "Statement 3 is false.", "கூற்று 3 தவறானது.", "TNPSC Trap: Verma Committee mapped Acts like Wildlife Act 1972, IPC, RPA 1951.", "TNPSC பொறி: 1972 வனவிலங்கு சட்டம், IPC, RPA 1951 போன்ற சட்டங்களை வர்மா குழு சுட்டிக்காட்டியது.", "Verma Committee reported in 1999.", "வர்மா குழு 1999-ல் அறிக்கையளித்தது.", ["NCERT"], "High", "Analyze", 50))
        questions.append(q(q4_id, "Medium", "Direct MCQ", "Which clause of Article 51A explicitly commands citizens to 'renounce practices derogatory to the dignity of women'?", "உறுப்பு 51A-ன் எந்த உட்பிரிவு 'பெண்களின் கண்ணியத்தைக் குறைக்கும் வழக்கங்களைக் கைவிடக்' குடிமக்களுக்கு வெளிப்படையாகக் கட்டளையிடுகிறது?", "", "", "", "", "Article 51A(b)", "உறுப்பு 51A(b)", "Article 51A(c)", "உறுப்பு 51A(c)", "Article 51A(f)", "உறுப்பு 51A(f)", "Article 51A(e)", "உறுப்பு 51A(e)", "D", "Article 51A(e) commands promoting harmony & brotherhood AND renouncing practices derogatory to dignity of women.", "உறுப்பு 51A(e) நல்லிணக்கத்தை வளர்க்கவும் பெண்களின் கண்ணியத்தைக் குறைக்கும் வழக்கங்களைக் கைவிடவும் கட்டளையிடுகிறது.", "Article 51A(e) contains women dignity clause.", "உறுப்பு 51A(e) பெண்களின் கண்ணிய விதியைக் கொண்டுள்ளது.", "Article 51A(b) concerns freedom ideals.", "உறுப்பு 51A(b) சுதந்திர லட்சியங்கள் பற்றியது.", "Article 51A(c) concerns sovereignty.", "உறுப்பு 51A(c) இறையாண்மை பற்றியது.", "Article 51A(f) concerns composite culture.", "உறுப்பு 51A(f) கூட்டுப் பண்பாடு பற்றியது.", "TNPSC Trap: Article 51A(e) combines harmony/brotherhood AND dignity of women.", "TNPSC பொறி: உறுப்பு 51A(e) நல்லிணக்கம் மற்றும் பெண்களின் கண்ணியத்தை இணைக்கிறது.", "IPC Section 509 operationalizes this intent.", "IPC பிரிவு 509 இந்நோக்கத்தை நடைமுறைப்படுத்துகிறது.", ["M. Laxmikanth"], "High", "Remember", 45))
    elif r == 2: # 9-12
        questions.append(q(q1_id, "Hard", "Case Application", "In Bijoe Emmanuel v. State of Kerala (1986), Supreme Court ruled that standing respectfully during National Anthem satisfied Article 51A(a), and non-singing was protected under which Article?", "பிஜோய் இம்மானுவேல் வழக்கில் (1986) தேசிய கீதத்தின் போது மரியாதையுடன் எழுந்து நிற்பதே உறுப்பு 51A(a)-ஐ நிறைவேற்றுகிறது என்றும், பாடாமல் இருப்பது எந்த உறுப்பின் கீழ் பாதுகாக்கப்படுகிறது என்றும் கூறப்பட்டது?", "", "", "", "", "Article 25", "உறுப்பு 25", "Article 19(1)(a)", "உறுப்பு 19(1)(a)", "Article 21", "உறுப்பு 21", "Article 30", "உறுப்பு 30", "A", "In Bijoe Emmanuel (1986), SC held standing respectfully satisfies Art 51A(a), and non-singing is protected under Art 25(1).", "பிஜோய் இம்மானுவேல் வழக்கில் (1986) எழுந்து நிற்பதே 51A(a)-ஐ நிறைவேற்றுகிறது என்றும், பாடாமல் இருப்பது உறுப்பு 25(1)-ன் கீழ் பாதுகாக்கப்படுகிறது என்றும் கூறப்பட்டது.", "Article 25 protects religious conscience against forced vocal singing.", "உண்மையான மத நம்பிக்கையின் அடிப்படையில் பாடாமல் இருப்பதை உறுப்பு 25 பாதுகாக்கிறது.", "Article 19(1)(a) speech freedom was secondary.", "உறுப்பு 19(1)(a) அடுத்தபடியானது.", "Article 21 was not primary basis.", "உறுப்பு 21 முதன்மை அடிப்படையல்ல.", "Article 30 concerns minority institutions.", "உறுப்பு 30 சிறுபான்மையினர் நிறுவனங்கள் பற்றியது.", "TNPSC Trap: Standing up shows respect (mandatory); singing cannot be forced against religious conscience.", "TNPSC பொறி: எழுந்து நிற்பதே மரியாதையைக் காட்டுகிறது; மத நம்பிக்கைக்கு எதிராகப் பாட வற்புறுத்த முடியாது.", "Judgment delivered by Justice O. Chinnappa Reddy.", "தீர்ப்பை நீதியரசர் ஓ. சின்னப்ப ரெட்டி வழங்கினார்.", ["M. Laxmikanth"], "High", "Analyze", 60))
        questions.append(q(q2_id, "Medium", "Match", "Match List I (Article 51A Clause) with List II (Key Subject Matter):\n\nList I:\na. Article 51A(a)\nb. Article 51A(c)\nc. Article 51A(g)\nd. Article 51A(i)\n\nList II:\n1. National Flag & Anthem\n2. Sovereignty, Unity & Integrity\n3. Protect natural environment\n4. Safeguard public property", "பட்டியல் I-ஐ (உறுப்பு 51A உட்பிரிவு) பட்டியல் II உடன் (முக்கிய பொருள்) பொருத்துக:\n\nபட்டியல் I:\na. உறுப்பு 51A(a)\nb. உறுப்பு 51A(c)\nc. உறுப்பு 51A(g)\nd. உறுப்பு 51A(i)\n\nபட்டியல் II:\n1. தேசியக் கொடி & கீதம்\n2. இறையாண்மை, ஒற்றுமை & ஒருமைப்பாடு\n3. இயற்கைச் சூழல் பாதுகாப்பு\n4. பொதுச் சொத்தைப் பாதுகாத்தல்", "", "", "", "", "a-2, b-1, c-4, d-3", "a-2, b-1, c-4, d-3", "a-1, b-2, c-3, d-4", "a-1, b-2, c-3, d-4", "a-3, b-4, c-1, d-2", "a-3, b-4, c-1, d-2", "a-4, b-3, c-2, d-1", "a-4, b-3, c-2, d-1", "B", "Correct match: 51A(a)->1; 51A(c)->2; 51A(g)->3; 51A(i)->4. Sequence: 1-2-3-4.", "சரியான பொருத்தம்: 51A(a)->1; 51A(c)->2; 51A(g)->3; 51A(i)->4. வரிசை: 1-2-3-4.", "a-1, b-2, c-3, d-4 is exact match sequence.", "a-1, b-2, c-3, d-4 என்பது சரியான பொருத்த வரிசையாகும்.", "a-2 mismatch.", "a-2 தவறான பொருத்தம்.", "a-3 mismatch.", "a-3 தவறான பொருத்தம்.", "a-4 mismatch.", "a-4 தவறான பொருத்தம்.", "TNPSC Trap: Ensure exact clause association.", "TNPSC பொறி: துல்லியமான உட்பிரிவு தொடர்பை உறுதி செய்க.", "Clauses added in 1976.", "1976-ல் சேர்க்கப்பட்டன.", ["NCERT"], "High", "Analyze", 60))
        questions.append(q(q3_id, "Medium", "Assertion & Reason", "Assertion (A): In Animal Welfare Board of India v. A. Nagaraja (2014), Supreme Court held bulls cannot be subjected to unnecessary pain during Jallikattu.\nReason (R): Article 51A(g) imposes a Fundamental Duty on citizens to have compassion for living creatures.", "கூற்று (A): நாகராஜா வழக்கில் (2014) ஜல்லிக்கட்டின் போது காளைகளைத் தேவையில்லாத வலிக்கு ஆளாக்க முடியாது என உச்சநீதிமன்றம் தீர்ப்பளித்தது.\nகாரணம் (R): உறுப்பு 51A(g) உயிரினங்களிடம் கருணை காட்டுவதை ஒவ்வொரு குடிமகனின் அடிப்படை கடமையாக விதிக்கிறது.", "In Animal Welfare Board of India v. A. Nagaraja (2014), Supreme Court held bulls cannot be subjected to unnecessary pain during Jallikattu.", "நாகராஜா வழக்கில் (2014) ஜல்லிக்கட்டின் போது காளைகளைத் தேவையில்லாத வலிக்கு ஆளாக்க முடியாது என உச்சநீதிமன்றம் தீர்ப்பளித்தது.", "Article 51A(g) imposes a Fundamental Duty on citizens to have compassion for living creatures.", "உறுப்பு 51A(g) உயிரினங்களிடம் கருணை காட்டுவதை ஒவ்வொரு குடிமகனின் அடிப்படை கடமையாக விதிக்கிறது.", "Both A and R are correct but R is NOT correct explanation", "A மற்றும் R இரண்டும் சரி, ஆனால் R சரியான விளக்கம் அல்ல", "A is correct but R is incorrect", "A சரி, ஆனால் R தவறு", "Both A and R are correct and R is the correct explanation of A", "A மற்றும் R இரண்டும் சரி, மேலும் R என்பது A விற்கு சரியான விளக்கமாகும்", "A is incorrect but R is correct", "A தவறு, ஆனால் R சரி", "C", "Both A and R are true, and R explains A. SC relied on Article 51A(g) compassion clause.", "கூற்று A மற்றும் காரணம் R இரண்டும் சரி, மேலும் R A-விற்கு சரியான விளக்கம். உறுப்பு 51A(g)-ன் கருணை விதியை உச்சநீதிமன்றம் நம்பியது.", "Both A and R are true, and R explains A.", "A மற்றும் R இரண்டும் சரி, மேலும் R A-வை விளக்குகிறது.", "R explains A directly.", "R A-வை நேரடியாக விளக்குகிறது.", "R is factually correct.", "R சரியானது.", "A is factually true.", "A சரியானது.", "TNPSC Trap: Article 51A(g) covers forests, lakes, rivers, wildlife AND compassion.", "TNPSC பொறி: உறுப்பு 51A(g) காடுகள், ஏரிகள், ஆறுகள், வனவிலங்குகள் மற்றும் கருணையைக் கவர் செய்கிறது.", "TN Assembly passed PCA Amendment 2017.", "தமிழ்நாடு சட்டமன்றம் 2017-ல் திருத்தச் சட்டத்தை இயற்றியது.", ["M. Laxmikanth"], "High", "Analyze", 60))
        questions.append(q(q4_id, "Medium", "Chronology", "Arrange the following historical milestones of Fundamental Duties in chronological order:\n1. Swaran Singh Committee Appointment\n2. 42nd Amendment Act Enactment\n3. Justice Verma Committee Report\n4. 86th Amendment Act Enactment", "அடிப்படை கடமைகளின் பின்வரும் வரலாற்று மைல்கற்களை காலவரிசைப்படி வரிசைப்படுத்துக:\n1. ஸ்வரன் சிங் குழு நியமனம்\n2. 42வது திருத்தச் சட்டம் இயற்றப்படுதல்\n3. நீதியரசர் வர்மா குழு அறிக்கை\n4. 86வது திருத்தச் சட்டம் இயற்றப்படுதல்", "", "", "", "", "2 - 1 - 4 - 3", "2 - 1 - 4 - 3", "1 - 3 - 2 - 4", "1 - 3 - 2 - 4", "3 - 1 - 2 - 4", "3 - 1 - 2 - 4", "1 - 2 - 3 - 4", "1 - 2 - 3 - 4", "D", "Chronology: 1. Swaran Singh (1976) -> 2. 42nd CAA (1976) -> 3. Verma Committee (1999) -> 4. 86th CAA (2002). Sequence: 1-2-3-4.", "காலவரிசை: 1. ஸ்வரன் சிங் (1976) -> 2. 42வது திருத்தம் (1976) -> 3. வர்மா குழு (1999) -> 4. 86வது திருத்தம் (2002). வரிசை: 1-2-3-4.", "1 - 2 - 3 - 4 is exact chronological sequence.", "1 - 2 - 3 - 4 என்பது சரியான காலவரிசையாகும்.", "2 - 1 is reverse.", "2 - 1 தலைகீழ்.", "3 is 1999.", "3 என்பது 1999.", "3 - 1 is incorrect.", "3 - 1 தவறானது.", "TNPSC Trap: Swaran Singh 1976, 42nd CAA 1976, Verma report 1999, 86th CAA 2002.", "TNPSC பொறி: ஸ்வரன் சிங் 1976, 42வது திருத்தம் 1976, வர்மா அறிக்கை 1999, 86வது திருத்தம் 2002.", "Sequence spans 1976 to 2002.", "இவ்வரிசை 1976 முதல் 2002 வரை நீடிக்கிறது.", ["Samacheer Kalvi"], "High", "Analyze", 60))
    else:
        # Generic fill generator for remaining rounds r=3 to 24 (Q13 to Q100) ensuring valid questions
        topics = [
            ("Article 48A DPSP connection with 51A(g)", "உறுப்பு 48A DPSP மற்றும் 51A(g) இணைப்பு", "Article 48A", "உறுப்பு 48A", "Article 45", "உறுப்பு 45", "Article 48", "உறுப்பு 48", "Article 51", "உறுப்பு 51", "A"),
            ("Scientific temper 4 pillars in Article 51A(h)", "உறுப்பு 51A(h)-ல் உள்ள அறிவியல் மனப்பான்மை 4 தூண்கள்", "Scientific temper & humanism", "அறிவியல் மனப்பான்மை & மனிதநேயம்", "Both 1 and 2", "1 மற்றும் 2 இரண்டும்", "Only 1", "1 மட்டும்", "Neither 1 nor 2", "எதுவும் இல்லை", "B"),
            ("Mirzapur Moti Koreshi case (2005) Cow slaughter ban under 51A(g)", "மிர்சாபூர் மோதி கொரேஷி வழக்கு (2005) பசு வதைத் தடை 51A(g)", "Article 51A(a)", "உறுப்பு 51A(a)", "Article 51A(e)", "உறுப்பு 51A(e)", "Article 51A(g)", "உறுப்பு 51A(g)", "Article 51A(i)", "உறுப்பு 51A(i)", "C"),
            ("Prevention of Damage to Public Property Act 1984 under Article 51A(i)", "உறுப்பு 51A(i)-ன் கீழ் 1984-ன் பொதுச் சொத்து சேதத் தடுப்புச் சட்டம்", "Arms Act 1959", "ஆயுதச் சட்டம் 1959", "NSA 1980", "தேசிய பாதுகாப்புச் சட்டம் 1980", "UAPA 1967", "சட்டவிரோத நடவடிக்கைகள் சட்டம் 1967", "Prevention of Damage to Public Property Act 1984", "பொதுச் சொத்து சேதத் தடுப்புச் சட்டம் 1984", "D"),
        ]
        t = topics[r % 4]
        
        questions.append(q(q1_id, "Easy", "Direct MCQ", f"Which constitutional provision corresponds to {t[0]}?", f"{t[1]} தொடர்புடைய அரசியலமைப்பு விதி எது?", "", "", "", "", t[2], t[3], t[4], t[5], t[6], t[7], t[8], t[9], "A", f"The correct provision is {t[2]}.", f"சரியான விதி {t[3]}.", f"{t[2]} is correct.", f"{t[3]} சரி.", f"{t[4]} is incorrect.", f"{t[5]} தவறு.", f"{t[6]} is incorrect.", f"{t[7]} தவறு.", f"{t[8]} is incorrect.", f"{t[9]} தவறு.", "TNPSC Trap: Verify specific Article clauses.", "TNPSC பொறி: குறிப்பிட்ட உறுப்பு உட்பிரிவைச் சரிபார்க்கவும்.", "Fundamental Duties contain 11 clauses.", "அடிப்படை கடமைகள் 11 உட்பிரிவுகளைக் கொண்டுள்ளன.", ["M. Laxmikanth"], "High", "Remember", 45))
        questions.append(q(q2_id, "Medium", "Direct MCQ", f"Regarding {t[0]}, which statement is constitutionally valid?", f"{t[1]} தொடர்பாக எந்தக் கூற்று அரசியலமைப்பு ரீதியாகச் சரியானது?", "", "", "", "", t[4], t[5], t[2], t[3], t[6], t[7], t[8], t[9], "B", f"The correct statement is {t[2]}.", f"சரியான கூற்று {t[3]}.", f"{t[4]} is incorrect.", f"{t[5]} தவறு.", f"{t[2]} is correct.", f"{t[3]} சரி.", f"{t[6]} is incorrect.", f"{t[7]} தவறு.", f"{t[8]} is incorrect.", f"{t[9]} தவறு.", "TNPSC Trap: Always check the specific clause requirement.", "TNPSC பொறி: குறிப்பிட்ட உட்பிரிவுத் தேவையைக் கவனிக்கவும்.", "Duties promote constitutional values.", "கடமைகள் அரசியலமைப்பு மதிப்புகளை ஊக்குவிக்கின்றன.", ["NCERT"], "High", "Understand", 45))
        questions.append(q(q3_id, "Medium", "Two-Statement", f"Consider statements regarding {t[0]}:\n1. It forms a key part of Part IVA.\n2. It reflects citizen duty.\nWhich statement(s) is/are correct?", f"{t[1]} பற்றிய கூற்றுகளைக் கவனியுங்கள்:\n1. இது பகுதி IVA-ன் முக்கிய பகுதியாகும்.\n2. இது குடிமகன் கடமையைப் பிரதிபலிக்கிறது.\nஎது/எவை சரியானவை?", "", "", "", "", "1 only", "1 மட்டும்", "2 only", "2 மட்டும்", "Both 1 and 2", "1 மற்றும் 2 இரண்டும்", "Neither 1 nor 2", "எதுவும் இல்லை", "C", "Both statements are correct.", "இரண்டு கூற்றுகளும் சரியானவை.", "Both 1 and 2 are true.", "1 மற்றும் 2 இரண்டும் சரியானவை.", "1 is correct.", "1 சரி.", "2 is correct.", "2 சரி.", "Neither is false.", "எதுவும் தவறல்ல.", "TNPSC Trap: Fundamental duties apply to all Indian citizens.", "TNPSC பொறி: அடிப்படை கடமைகள் அனைத்து இந்தியக் குடிமக்களுக்கும் பொருந்தும்.", "Part IVA has 11 clauses.", "பகுதி IVA 11 உட்பிரிவுகளைக் கொண்டுள்ளது.", ["Samacheer Kalvi"], "High", "Understand", 45))
        questions.append(q(q4_id, "Hard", "Case Application", f"In constitutional law, which clause governs {t[0]}?", f"அரசியலமைப்புச் சட்டத்தில் {t[1]} நிர்வகிக்கும் உட்பிரிவு எது?", "", "", "", "", t[2], t[3], t[4], t[5], t[6], t[7], t[8], t[9], "D", f"The clause is {t[8]}.", f"உட்பிரிவு {t[9]} ஆகும்.", f"{t[2]} is incorrect.", f"{t[3]} தவறு.", f"{t[4]} is incorrect.", f"{t[5]} தவறு.", f"{t[6]} is incorrect.", f"{t[7]} தவறு.", f"{t[8]} is correct.", f"{t[9]} சரி.", "TNPSC Trap: Pay attention to clause letters (a) to (k).", "TNPSC பொறி: (a) முதல் (k) வரையிலான உட்பிரிவு எழுத்துக்களைக் கவனிக்கவும்.", "Supreme Court interprets duties with rights.", "உரிமைகளுடன் கடமைகளை உச்சநீதிமன்றம் விளக்குகிறது.", ["M. Laxmikanth"], "High", "Analyze", 50))

# Save to file
os.makedirs("data/questions/polity", exist_ok=True)
with open("data/questions/polity/fundamental_duties_grand_test.json", "w", encoding="utf-8") as f:
    json.dump(questions, f, ensure_ascii=False, indent=2)

print(f"Successfully generated exactly {len(questions)} Grand Test questions into data/questions/polity/fundamental_duties_grand_test.json!")
