import json
import os

from generate_all_50 import questions, make_q

# --- 31 TO 40 ---
questions.append(make_q(
    "PRE_H_031", "Constitutional Relationship",
    "Which of the following statements best describes the functional relationship between the Preamble and Part III (Fundamental Rights) of the Constitution?",
    "முகவுரைக்கும் அரசியலமைப்பின் பகுதி III (அடிப்படை உரிமைகள்) க்கும் இடையிலான செயல்பாட்டு உறவை பின்வரும் கூற்றுகளில் எது மிகச்சரியாக விவரிக்கிறது?",
    "Part III Fundamental Rights completely supersede the Preamble, rendering preambular values irrelevant in constitutional litigation.",
    "பகுதி III அடிப்படை உரிமைகள் முகவுரையை முற்றிலும் மேலோங்குகின்றன, இதனால் அரசியலமைப்பு வழக்குகளில் முகவுரை மதிப்புகள் பொருத்தமற்றதாகின்றன.",
    "The Preamble grants actionable remedies under Article 32 independent of Part III provisions.",
    "முகவுரை பகுதி III விதிகளிலிருந்து சுயாதீனமாக உறுப்பு 32 இன் கீழ் நடவடிக்கைக்குரிய தீர்வுகளை வழங்குகிறது.",
    "The Preamble outlines the noble philosophical vision (Liberty, Equality, Dignity), while Part III enacts legally enforceable fundamental rights to operationalize that vision.",
    "முகவுரை உன்னதமான தத்துவ தொலைநோக்கை (சுதந்திரம், சமத்துவம், கண்ணியம்) கோடிட்டுக் காட்டுகிறது, ஆனால் பகுதி III அந்தத் தொலைநோக்கை நடைமுறைப்படுத்த சட்டப்பூர்வமாக அமல்படுத்தக்கூடிய அடிப்படை உரிமைகளை இயற்றுகிறது.",
    "Part III Fundamental Rights were enacted by British Parliament, whereas Preamble was created by Indian Parliament in 1976.",
    "பகுதி III அடிப்படை உரிமைகள் பிரிட்டிஷ் பாராளுமன்றத்தால் இயற்றப்பட்டன, ஆனால் முகவுரை 1976 இல் இந்திய நாடாளுமன்றத்தால் உருவாக்கப்பட்டது.",
    "C",
    "The Preamble contains the ideals and aspirations of the framers, while Part III provides the concrete legal mechanism (Fundamental Rights) to enforce those ideals. Courts routinely interpret the scope of Part III rights (such as Article 21) using the grand vision expressed in the Preamble.",
    "முகவுரையில் அரசியலமைப்பு சிற்பிகளின் இலட்சியங்களும் விருப்பங்களும் உள்ளன, அதே நேரத்தில் பகுதி III அந்த இலட்சியங்களை அமல்படுத்துவதற்கான கான்கிரீட் சட்ட வழிமுறையை (அடிப்படை உரிமைகள்) வழங்குகிறது.",
    "Incorrect. Part III does not render Preamble irrelevant; Preamble guides Part III interpretation.", "தவறு. பகுதி III முகவுரையைப் பொருத்தமற்றதாக்காது; முகவுரை பகுதி III விளக்கத்திற்கு வழிகாட்டுகிறது.",
    "Incorrect. Preamble is non-justiciable and does not independently grant Art 32 remedies.", "தவறு. முகவுரை நீதிமன்றத்தால் நிலைநிறுத்த முடியாதது மற்றும் உறுப்பு 32 தீர்வுகளை நேரடியாக வழங்காது.",
    "Correct. Preamble = Philosophical vision; Part III = Actionable legal machinery.", "சரி. முகவுரை = தத்துவ தொலைநோக்கு; பகுதி III = அமல்படுத்தக்கூடிய சட்ட இயந்திரம்.",
    "Incorrect. Both were framed by the Constituent Assembly of India.", "தவறு. இரண்டும் இந்திய அரசியலமைப்புச் சபையால் அமைக்கப்பட்டன.",
    "Preamble = Vision & Philosophy. Part III (Art 12-35) = Actionable legal rights enforcing Preamble Liberty, Equality, and Dignity.",
    "முகவுரை = தொலைநோக்கு & தத்துவம். பகுதி III (உறுப்புகள் 12-35) = முகவுரை சுதந்திரம், சமத்துவம் மற்றும் கண்ணியத்தை அமல்படுத்தும் சட்ட உரிமைகள்.",
    "In Maneka Gandhi case (1978), Supreme Court expanded Article 21 using Preamble's vision of personal liberty and dignity.",
    "மேனகா காந்தி வழக்கில் (1978), உச்ச நீதிமன்றம் முகவுரையின் தனிநபர் சுதந்திரம் மற்றும் கண்ணியத்தின் தொலைநோக்கைப் பயன்படுத்தி உறுப்பு 21 ஐ விரிவாக்கியது.",
    ["Preamble", "Part III", "Fundamental Rights", "Constitutional Relationship"]
))

questions.append(make_q(
    "PRE_H_032", "Constitutional Relationship",
    "How do the Directive Principles of State Policy (Part IV) interact with the Preamble's solemn pledge to secure 'Justice—social, economic and political'?",
    "அரசு கொள்கை வழிகாட்டு நெறிமுறைகள் (பகுதி IV) 'நீதி—சமூக, பொருளாதார மற்றும் அரசியல்' பாதுகாப்பதாக முகவுரை அளிக்கும் உறுதியுடன் எவ்வாறு தொடர்புகொள்கின்றன?",
    "Part IV Directive Principles contradict the Preamble by favoring economic growth over individual liberty.",
    "பகுதி IV வழிகாட்டு நெறிமுறைகள் தனிமனித சுதந்திரத்தை விட பொருளாதார வளர்ச்சியை ஆதரிப்பதன் மூலம் முகவுரைக்கு முரண்படுகின்றன.",
    "Part IV Directive Principles are strictly subordinate to foreign international commercial treaties.",
    "பகுதி IV வழிகாட்டு நெறிமுறைகள் வெளிநாட்டு சர்வதேச வணிக ஒப்பந்தங்களுக்குக் கண்டிப்பாக உட்பட்டவை.",
    "Part IV Directive Principles repeal the Preamble during economic crises.",
    "பொருளாதார நெருக்கடிகளின் போது பகுதி IV வழிகாட்டு நெறிமுறைகள் முகவுரையை ரத்து செய்கின்றன.",
    "Part IV Directive Principles act as actionable state policy directives (Articles 38, 39, 41-43) to realize the Preamble's vision of Social and Economic Justice and a Welfare State.",
    "பகுதி IV வழிகாட்டு நெறிமுறைகள் முகவுரையின் சமூக மற்றும் பொருளாதார நீதி மற்றும் ஒரு நல அரசின் தொலைநோக்கைச் साकारமாக்க (உறுப்புகள் 38, 39, 41-43) செயல்படக்கூடிய அரசு கொள்கை வழிகாட்டுதல்களாக செயல்படுகின்றன.",
    "D",
    "The Preamble promises Social, Economic, and Political Justice. Part IV (DPSP) contains the specific constitutional obligations of the State (such as Article 38 for promoting welfare of people and Article 39 for distributive economic justice) to translate the Preamble's socio-economic justice vision into legislative reality.",
    "முகவுரை சமூக, பொருளாதார மற்றும் அரசியல் நீதிக்கு வாக்குறுதி அளிக்கிறது. பகுதி IV (DPSP) முகவுரையின் சமூக-பொருளாதார நீதி தொலைநோக்கைச் சட்ட யதார்த்தமாக மாற்ற அரசின் குறிப்பிட்ட அரசியலமைப்புக் கடமைகளைக் கொண்டுள்ளது.",
    "Incorrect. DPSP and Preamble are harmonious, not contradictory.", "தவறு. DPSP மற்றும் முகவுரை இணக்கமானவை, முரண்பாடானவை அல்ல.",
    "Incorrect. DPSP are fundamental in governance of the country (Art 37).", "தவறு. DPSP நாட்டின் ஆட்சியில் அடிப்படையானவை (உறுப்பு 37).",
    "Incorrect. DPSP cannot repeal the Preamble.", "தவறு. DPSP முகவுரையை ரத்து செய்ய முடியாது.",
    "Correct. DPSP (Part IV) = Policy machinery realizing Preamble's Social & Economic Justice.", "சரி. DPSP (பகுதி IV) = முகவுரையின் சமூக & பொருளாதார நீதியை நிறைவேற்றும் கொள்கை இயந்திரம்.",
    "Preamble Social & Economic Justice = Realized practically through DPSP (Articles 38 & 39 in Part IV).",
    "முகவுரை சமூக & பொருளாதார நீதி = DPSP (பகுதி IV இல் உறுப்புகள் 38 & 39) மூலம் நடைமுறையில் நிறைவேற்றப்படுகிறது.",
    "Article 38 mandates the State to secure a social order for the promotion of welfare of the people.",
    "உறுப்பு 38 மக்களின் நலனை மேம்படுத்துவதற்கான ஒரு சமூக ஒழுங்கைப் பாதுகாக்க அரசுக்கு ஆணையிடுகிறது.",
    ["Preamble", "Part IV", "DPSP", "Social and Economic Justice"]
))

questions.append(make_q(
    "PRE_H_033", "Constitutional Relationship",
    "Which specific provisions of Part IVA (Fundamental Duties) directly operationalize the Preamble's objective of promoting 'Fraternity assuring the dignity of the individual and the unity and integrity of the Nation'?",
    "பகுதி IVA (அடிப்படை கடமைகள்) இன் எந்தக் குறிப்பிட்ட விதிகள் 'நபரின் கண்ணியம் மற்றும் நாட்டின் பிளவுபடாத ஒருமைப்பாட்டை உறுதிப்படுத்தும் சகோதரத்துவத்தை' ஊக்குவிக்கும் முகவுரையின் இலக்கை நேரடியாக நடைமுறைப்படுத்துகின்றன?",
    "Article 51A(c) (uphold and protect sovereignty, unity, and integrity) and Article 51A(e) (promote harmony and common brotherhood).",
    "உறுப்பு 51A(c) (இறையாண்மை, ஒற்றுமை மற்றும் ஒருமைப்பாட்டை உயர்த்திப் பிடித்தல்) மற்றும் உறுப்பு 51A(e) (நல்லிணக்கத்தையும் பொதுவான சகோதரத்துவத்தையும் ஊக்குவித்தல்).",
    "Article 51A(a) only (abide by Constitution and respect National Flag).",
    "உறுப்பு 51A(a) மட்டுமே (அரசியலமைப்புக்கு கீழ்ப்படிதல் மற்றும் தேசியக்கொடியை மதித்தல்).",
    "Article 51A(k) only (duty of parent/guardian to provide education).",
    "உறுப்பு 51A(k) மட்டுமே (கல்வி வழங்குவது பெற்றோர்/காப்பாளரின் கடமை).",
    "Article 51A(g) only (protect natural environment).",
    "உறுப்பு 51A(g) மட்டுமே (இயற்கை சூழலைப் பாதுகாத்தல்).",
    "A",
    "Fraternity in the Preamble promotes common brotherhood and national integrity. This is directly reflected in Fundamental Duties under Article 51A: Clause (c) makes it every citizen's duty to 'uphold and protect the sovereignty, unity and integrity of India', while Clause (e) mandates promoting 'harmony and the spirit of common brotherhood'.",
    "முகவுரையில் உள்ள சகோதரத்துவம் பொதுவான சகோதரத்துவத்தையும் தேசிய ஒருமைப்பாட்டையும் ஊக்குவிக்கிறது. இது உறுப்பு 51A இன் கீழ் உள்ள அடிப்படை கடமைகளில் நேரடியாகப் பிரதிபலிக்கிறது: பிரிவு (c) இந்தியாவின் இறையாண்மை, ஒற்றுமை மற்றும் ஒருமைப்பாட்டைப் பாதுகாக்க ஆணையிடுகிறது, பிரிவு (e) பொதுவான சகோதரத்துவ உணர்வை ஊக்குவிக்க ஆணையிடுகிறது.",
    "Correct. Art 51A(c) & 51A(e) directly translate Preamble Fraternity & Integrity into citizen duties.", "சரி. உறுப்பு 51A(c) & 51A(e) முகவுரை சகோதரத்துவம் & ஒருமைப்பாட்டை நேரடியாகக் குடிமகன் கடமைகளாக மாற்றுகின்றன.",
    "Incorrect. Art 51A(a) focuses on constitutional symbols, not fraternity.", "தவறு. உறுப்பு 51A(a) அரசியலமைப்புச் சின்னங்களில் கவனம் செலுத்துகிறது.",
    "Incorrect. Art 51A(k) focuses on education.", "தவறு. உறுப்பு 51A(k) கல்வியில் கவனம் செலுத்துகிறது.",
    "Incorrect. Art 51A(g) focuses on environment.", "தவறு. உறுப்பு 51A(g) சுற்றுச்சூழலில் கவனம் செலுத்துகிறது.",
    "Preamble Fraternity -> Operationalized by Fundamental Duties Art 51A(c) [Sovereignty, Unity & Integrity] and Art 51A(e) [Common Brotherhood].",
    "முகவுரை சகோதரத்துவம் -> அடிப்படை கடமைகள் உறுப்பு 51A(c) [இறையாண்மை, ஒற்றுமை & ஒருமைப்பாடு] மற்றும் உறுப்பு 51A(e) [பொதுச் சகோதரத்துவம்] மூலம் நடைமுறைப்படுத்தப்படுகிறது.",
    "Fundamental Duties were incorporated into Part IVA by 42nd CAA 1976, same amendment that added 'Integrity' to Preamble.",
    "அடிப்படை கடமைகள் 1976 இன் 42வது CAA ஆல் பகுதி IVA இல் சேர்க்கப்பட்டன, அதே திருத்தமே முகவுரையில் 'ஒருமைப்பாடு' என்பதையும் சேர்த்தது.",
    ["Preamble", "Part IVA", "Fundamental Duties", "Article 51A", "Fraternity"]
))

questions.append(make_q(
    "PRE_H_034", "Constitutional Relationship",
    "What is the interplay between Article 368 (amending power of Parliament) and the Preamble as settled in the Basic Structure Doctrine?",
    "அடிப்படை கட்டமைப்பு கோட்பாட்டில் தீர்க்கப்பட்டபடி உறுப்பு 368 (பாராளுமன்றத்தின் திருத்தும் அதிகாரம்) மற்றும் முகவுரைக்கு இடையிலான பரஸ்பர தொடர்பு யாது?",
    "Article 368 permits Parliament to completely abrogate the Preamble and replace it with an autocratic manifesto.",
    "உறுப்பு 368 பாராளுமன்றம் முகவுரையை முற்றிலும் ரத்து செய்து அதற்குப் பதிலாக ஒரு தன்னிச்சையான அறிக்கையை வைக்க அனுமதிக்கிறது.",
    "Article 368 permits Parliament to amend the Preamble, provided the fundamental features and basic identity of the Constitution embodied in the Preamble are not altered or destroyed.",
    "முகவுரையில் பொதிந்துள்ள அரசியலமைப்பின் அடிப்படை அம்சங்களும் அடிப்படை அடையாளமும் மாற்றப்படாமலோ அல்லது அழிக்கப்படாமலோ இருக்கும் வரை முகவுரையைத் திருத்த உறுப்பு 368 பாராளுமன்றத்தை அனுமதிக்கிறது.",
    "Article 368 prohibits any verbal change to the Preamble under any circumstances.",
    "உறுப்பு 368 எந்த சூழ்நிலையிலும் முகவுரையில் எந்தவொரு வார்த்தை மாற்றத்தையும் தடுக்கிறது.",
    "Article 368 requires unanimous approval of all 28 State Assemblies for amending any word in the Preamble.",
    "முகவுரையில் உள்ள எந்தவொரு வார்த்தையையும் திருத்துவதற்கு 28 மாநில சட்டசபைகளின் ஏகமனதான ஒப்புதலை உறுப்பு 368 கோருகிறது.",
    "B",
    "Under Article 368, Parliament has plenary power to amend any part of the Constitution, including the Preamble. However, as established in Kesavananda Bharati (1973), this amending power is bounded by the Basic Structure Doctrine. Parliament can amend the Preamble to clarify or expand its noble vision, but CANNOT destroy the basic features (like Secularism, Democracy, Sovereignty) contained therein.",
    "உறுப்பு 368 இன் கீழ் பாராளுமன்றம் முகவுரை உட்பட அரசியலமைப்பின் எந்தப் பகுதியையும் திருத்த அதிகாரம் கொண்டுள்ளது. இருப்பினும், கேசவாநந்த பாரதி (1973) தீர்ப்பின்படி, இந்தத் திருத்தும் அதிகாரம் அடிப்படை கட்டமைப்பு கோட்பாட்டால் வரம்பிற்குட்படுத்தப்பட்டுள்ளது.",
    "Incorrect. Parliament cannot abrogate Basic Structure.", "தவறு. பாராளுமன்றம் அடிப்படை கட்டமைப்பை ரத்து செய்ய முடியாது.",
    "Correct. Art 368 allows Preamble amendment subject to Basic Structure limitation.", "சரி. உறுப்பு 368 அடிப்படை கட்டமைப்பு வரம்பிற்கு உட்பட்டு முகவுரை திருத்தத்தை அனுமதிக்கிறது.",
    "Incorrect. Preamble was amended in 1976.", "தவறு. முகவுரை 1976 இல் திருத்தப்பட்டது.",
    "Incorrect. State ratification is not required unless falling under Art 368 proviso.", "தவறு. உறுப்பு 368 விலக்கின் கீழ் வராத வரை மாநில ஒப்புதல் தேவையில்லை.",
    "Preamble + Art 368: Preamble CAN be amended under Art 368, BUT Parliament cannot destroy its Basic Structure elements.",
    "முகவுரை + உறுப்பு 368: உறுப்பு 368 இன் கீழ் முகவுரையைத் திருத்த முடியும், ஆனால் பாராளுமன்றம் அதன் அடிப்படை கட்டமைப்பு கூறுகளை அழிக்க முடியாது.",
    "42nd CAA 1976 amended the Preamble without violating Basic Structure.",
    "1976 இன் 42வது CAA அடிப்படை கட்டமைப்பை மீறாமல் முகவுரையைத் திருத்தியது.",
    ["Preamble", "Article 368", "Amending Power", "Basic Structure"]
))

questions.append(make_q(
    "PRE_H_035", "Constitutional Relationship",
    "The Preamble promises 'Political Justice'. Which of the following constitutional provisions directly translates this vision into actionable electoral rights?",
    "முகவுரை 'அரசியல் நீதிக்கு' வாக்குறுதி அளிக்கிறது. பின்வரும் அரசியலமைப்பு விதிகளில் எது இந்தத் தொலைநோக்கை நேரடியாகச் செயல்படக்கூடிய தேர்தல் உரிமைகளாக மாற்றுகிறது?",
    "Article 31C (saving of laws giving effect to directive principles).", "உறுப்பு 31C (வழிகாட்டு நெறிமுறைகளை அமல்படுத்தும் சட்டங்களைப் பாதுகாத்தல்).",
    "Article 263 (Inter-State Council creation).", "உறுப்பு 263 (மாநிலங்களுக்கு இடையேயான கவுன்சில் உருவாக்கம்).",
    "Article 325 (no person to be ineligible for inclusion in electoral roll on grounds of religion, race, caste or sex) and Article 326 (elections based on Universal Adult Suffrage).",
    "உறுப்பு 325 (மதம், இனம், சாதி அல்லது பாலின அடிப்படையில் வாக்காளர் பட்டியலில் சேர்க்க எவரும் தகுதியற்றவர் அல்ல) மற்றும் உறுப்பு 326 (உலகளாவிய வயதுவந்தோர் வாக்குரிமை அடிப்படையில் தேர்தல்கள்).",
    "Article 360 (Financial Emergency declaration).", "உறுப்பு 360 (நிதி அவசரநிலை பிரகடனம்).",
    "C",
    "Political justice means that all citizens should have equal, free and fair opportunities to participate in the political process. This is operationalized through Article 325 (ensuring non-discriminatory electoral rolls regardless of religion, race, caste or sex) and Article 326 (granting universal adult suffrage to every citizen who is not less than 18 years of age).",
    "அரசியல் நீதி என்பது அனைத்து குடிமக்களும் அரசியல் செயல்பாட்டில் பங்கேற்க சமமான, சுதந்திரமான மற்றும் நேர்மையான வாய்ப்புகளைக் கொண்டிருக்க வேண்டும் என்பதாகும். இது உறுப்பு 325 மற்றும் உறுப்பு 326 மூலம் நடைமுறைப்படுத்தப்படுகிறது.",
    "Incorrect. Art 31C relates to DPSP savings clause.", "தவறு. உறுப்பு 31C DPSP பாதுகாப்பு விதியுடன் தொடர்புடையது.",
    "Incorrect. Art 263 relates to Inter-State Council.", "தவறு. உறுப்பு 263 மாநிலங்களுக்கு இடையேயான கவுன்சில் பற்றியது.",
    "Correct. Art 325 (Non-discriminatory rolls) + Art 326 (Adult Suffrage) = Political Justice in practice.", "சரி. உறுப்பு 325 + உறுப்பு 326 = நடைமுறையில் அரசியல் நீதி.",
    "Incorrect. Art 360 relates to Financial Emergency.", "தவறு. உறுப்பு 360 நிதி அவசரநிலை பற்றியது.",
    "Political Justice = Equal political rights for all. Realized via Article 325 (Equal Electoral Rolls) and Article 326 (Universal Adult Franchise).",
    "அரசியல் நீதி = அனைவருக்கும் சமமான அரசியல் உரிமைகள். உறுப்பு 325 (சம வாக்காளர் பட்டியல்) மற்றும் உறுப்பு 326 (உலகளாவிய வயதுவந்தோர் வாக்குரிமை) மூலம் நிறைவேற்றப்படுகிறது.",
    "61st Constitutional Amendment Act 1988 lowered voting age from 21 to 18 years under Article 326.",
    "1988 இன் 61வது அரசியலமைப்பு திருத்தச் சட்டம் உறுப்பு 326 இன் கீழ் வாக்குரிமை வயதை 21 லிருந்து 18 ஆகக் குறைத்தது.",
    ["Preamble", "Political Justice", "Article 325", "Article 326", "Adult Suffrage"]
))

questions.append(make_q(
    "PRE_H_036", "Constitutional Relationship",
    "How does the Preamble's pledge of 'Equality of status and of opportunity' find concrete legal expression in Articles 14 to 18 of Part III?",
    "முகவுரையின் 'தகுதி மற்றும் வாய்ப்பில் சமத்துவம்' என்ற வாக்குறுதி பகுதி III இன் உறுப்புகள் 14 முதல் 18 வரை எவ்வாறு கான்கிரீட் சட்ட வெளிப்பாட்டைக் காண்கிறது?",
    "Articles 14 to 18 apply exclusively to foreign diplomats residing in India.",
    "உறுப்புகள் 14 முதல் 18 வரை இந்தியாவில் வசிக்கும் வெளிநாட்டு தூதர்களுக்கு மட்டுமே பொருந்தும்.",
    "Articles 14 to 18 allow the Executive to grant hereditary titles to political supporters.",
    "உறுப்புகள் 14 முதல் 18 வரை அரசியல் ஆதரவாளர்களுக்குப் பரம்பரைப் பட்டங்களை வழங்க நிர்வாகத்தை அனுமதிக்கின்றன.",
    "Articles 14 to 18 establish feudal social hierarchies based on agrarian land ownership.",
    "உறுப்புகள் 14 முதல் 18 வரை நில உரிமையின் அடிப்படையில் நிலப்பிரபுத்துவ சமூக படிநிலைகளை நிறுவுகின்றன.",
    "Articles 14 to 18 operationalize Civic Equality through: Equality before law (Art 14), Prohibition of discrimination (Art 15), Equal opportunity in public employment (Art 16), Abolition of untouchability (Art 17), and Abolition of titles (Art 18).",
    "உறுப்புகள் 14 முதல் 18 வரை குடிமை சமத்துவத்தை நடைமுறைப்படுத்துகின்றன: சட்டத்தின் முன் சமத்துவம் (உறுப்பு 14), பாகுபாடு தடை (உறுப்பு 15), பொது வேலைவாய்ப்பில் சம வாய்ப்பு (உறுப்பு 16), தீண்டாமை ஒழிப்பு (உறுப்பு 17), மற்றும் பட்டங்கள் ஒழிப்பு (உறுப்பு 18).",
    "D",
    "The Preamble guarantees Equality of status and opportunity. Articles 14 to 18 in Part III provide the detailed constitutional guarantees securing civic equality: Art 14 (Equality before law), Art 15 (Prohibition of discrimination on grounds of religion, race, caste, sex, or place of birth), Art 16 (Equality of opportunity in public employment), Art 17 (Abolition of untouchability), and Art 18 (Abolition of titles).",
    "முகவுரை தகுதி மற்றும் வாய்ப்பில் சமத்துவத்திற்கு உத்தரவாதம் அளிக்கிறது. பகுதி III இல் உள்ள உறுப்புகள் 14 முதல் 18 வரை குடிமை சமத்துவத்தைப் பாதுகாக்கும் விரிவான அரசியலமைப்பு உத்தரவாதங்களை வழங்குகின்றன.",
    "Incorrect. Applies to citizens and persons in India.", "தவறு. இந்தியாவில் உள்ள குடிமக்கள் மற்றும் நபர்களுக்குப் பொருந்தும்.",
    "Incorrect. Art 18 explicitly ABOLISHES titles.", "தவறு. உறுப்பு 18 பட்டங்களை வெளிப்படையாக ஒழிக்கிறது.",
    "Incorrect. Articles 14-18 abolish feudal hierarchies.", "தவறு. உறுப்புகள் 14-18 நிலப்பிரபுத்துவ படிநிலைகளை ஒழிக்கின்றன.",
    "Correct. Articles 14-18 set out the complete statutory framework for Civic Equality promised in Preamble.", "சரி. உறுப்புகள் 14-18 முகவுரையில் வாக்குறுதி அளிக்கப்பட்ட குடிமை சமத்துவத்திற்கான முழுமையான சட்ட அமைப்பை அமைக்கிறது.",
    "Preamble Civic Equality = Implemented by Articles 14 (Equality before Law), 15 (No Discrimination), 16 (Equal Employment), 17 (Abolition of Untouchability), 18 (Abolition of Titles).",
    "முகவுரை குடிமை சமத்துவம் = உறுப்புகள் 14 (சட்டத்தின் முன் சமத்துவம்), 15 (பாகுபாடின்மை), 16 (சம வேலைவாய்ப்பு), 17 (தீண்டாமை ஒழிப்பு), 18 (பட்டங்கள் ஒழிப்பு) மூலம் செயல்படுத்தப்படுகிறது.",
    "Article 17 is one of the few Fundamental Rights that is absolute and enforceable against private individuals.",
    "உறுப்பு 17 என்பது வரம்பற்ற மற்றும் தனியார் நபர்களுக்கு எதிராக அமல்படுத்தக்கூடிய சில அடிப்படை உரிமைகளில் ஒன்றாகும்.",
    ["Preamble", "Civic Equality", "Articles 14 to 18", "Equality of Status"]
))

questions.append(make_q(
    "PRE_H_037", "Constitutional Relationship",
    "Which of the following correctly describes how Articles 25 to 28 of Part III give practical effect to the Preamble's commitment to 'Secularism'?",
    "பகுதி III இன் உறுப்புகள் 25 முதல் 28 வரை 'மதச்சார்பின்மை' என்ற முகவுரையின் அர்ப்பணிப்பிற்கு எவ்வாறு நடைமுறை விளைவை அளிக்கின்றன என்பதை பின்வருவனவற்றில் எது சரியாக விவரிக்கிறது?",
    "Articles 25 to 28 guarantee Positive Secularism by securing freedom of conscience, right to profess, practice and propagate religion, freedom to manage religious affairs, and freedom from religious taxation for ALL persons equally.",
    "உறுப்புகள் 25 முதல் 28 வரை அனைத்து நபர்களுக்கும் சமமாக மனசாட்சி சுதந்திரம், மதத்தைப் பின்பற்றும், பரப்பும் உரிமை, மத விவகாரங்களை நிர்வகிக்கும் சுதந்திரம் மற்றும் மத வரிவிலக்கு சுதந்திரம் ஆகியவற்றைப் பாதுகாப்பதன் மூலம் நேர்மறை மதச்சார்பின்மைக்கு உத்தரவாதம் அளிக்கின்றன.",
    "Articles 25 to 28 declare one specific majoritarian religion as the official religion of the Indian State.",
    "உறுப்புகள் 25 முதல் 28 வரை ஒரு குறிப்பிட்ட பெரும்பான்மை மதத்தை இந்திய அரசின் உத்தியோகபூர்வ மதமாக அறிவிக்கின்றன.",
    "Articles 25 to 28 ban all citizens from establishing or maintaining religious educational institutions.",
    "உறுப்புகள் 25 முதல் 28 வரை அனைத்து குடிமக்களும் மதக் கல்வி நிறுவனங்களை நிறுவுவதையோ அல்லது பராமரிப்பதையோ தடையாக விதிக்கின்றன.",
    "Articles 25 to 28 permit the State to force citizens to pay taxes specifically for promoting one religion.",
    "உறுப்புகள் 25 முதல் 28 வரை ஒரு மதத்தை மட்டுமே பரப்புவதற்கு நிலுவை வரிகளைச் செலுத்துமாறு குடிமக்களை வற்புறுத்த அரசுக்கு அனுமதிக்கின்றன.",
    "A",
    "Articles 25 to 28 in Part III embody Indian Positive Secularism (Sarva Dharma Sambhava). Art 25 guarantees freedom of conscience and free profession, practice and propagation of religion; Art 26 grants freedom to manage religious affairs; Art 27 prohibits compulsion to pay taxes for promoting any particular religion; Art 28 restricts religious instruction in state-maintained educational institutions.",
    "பகுதி III இல் உள்ள உறுப்புகள் 25 முதல் 28 வரை இந்திய நேர்மறை மதச்சார்பின்மையை (சர்வ தர்ம சம்பவ) உள்ளடக்கியுள்ளன. உறுப்பு 25 மனசாட்சி சுதந்திரம் மற்றும் மதப் பழக்க சுதந்திரத்திற்கு உத்தரவாதம் அளிக்கிறது.",
    "Correct. Articles 25-28 operationalize Positive Secularism (Sarva Dharma Sambhava).", "சரி. உறுப்புகள் 25-28 நேர்மறை மதச்சார்பின்மையை நடைமுறைப்படுத்துகின்றன.",
    "Incorrect. India has NO official state religion.", "தவறு. இந்தியாவுக்கு உத்தியோகபூர்வ அரசு மதம் எதுவுமில்லை.",
    "Incorrect. Article 30 explicitly grants minorities right to establish educational institutions.", "தவறு. உறுப்பு 30 சிறுபான்மையினருக்குக் கல்வி நிறுவனங்களை நிறுவ உரிமை அளிக்கிறது.",
    "Incorrect. Article 27 explicitly PROHIBITS religious taxation.", "தவறு. உறுப்பு 27 மத வரிகளை வெளிப்படையாகத் தடுக்கிறது.",
    "Preamble Secularism = Implemented via Articles 25 (Conscience/Practice), 26 (Religious Affairs), 27 (Tax Freedom), 28 (Instruction Limits).",
    "முகவுரை மதச்சார்பின்மை = உறுப்புகள் 25 (மனசாட்சி/பழக்கம்), 26 (மத விவகாரங்கள்), 27 (வரி சுதந்திரம்), 28 (போதனை வரம்புகள்) மூலம் செயல்படுத்தப்படுகிறது.",
    "Article 27 ensures state funds raised via general taxes cannot be spent for promoting any specific religion.",
    "பொது வரிகள் மூலம் திரட்டப்பட்ட அரசு நிதியை எந்தவொரு குறிப்பிட்ட மதத்தையும் பரப்புவதற்குச் செலவிட முடியாது என்பதை உறுப்பு 27 உறுதி செய்கிறது.",
    ["Preamble", "Secularism", "Articles 25 to 28", "Freedom of Religion"]
))

questions.append(make_q(
    "PRE_H_038", "Amendment + Basic Structure",
    "Why did the Parliament pass the 42nd Constitutional Amendment Act in 1976 adding the word 'and Integrity' to 'Unity of the Nation' in the Fraternity section?",
    "சகோதரத்துவப் பகுதியில் 'நாட்டின் ஒற்றுமை' என்பதற்குப் பின் 'மற்றும் ஒருமைப்பாடு' என்ற வார்த்தையைச் சேர்த்து 1976 இல் நாடாளுமன்றம் 42வது அரசியலமைப்பு திருத்தச் சட்டத்தை ஏன் நிறைவேற்றியது?",
    "To encourage states to secede from the Indian Union at will.",
    "மாநிலங்கள் இந்திய யூனியனிலிருந்து விரும்பியவாறு பிரிய ஊக்குவிக்க.",
    "To counter secessionist tendencies, reinforce the territorial and emotional integration of the nation, and emphasize that national unity is indivisible.",
    "பிரிவினைவாதப் போக்குகளை எதிர்க்கவும், நாட்டின் நிலப்பரப்பு மற்றும் உணர்வுப்பூர்வமான ஒருமைப்பாட்டை வலுப்படுத்தவும், தேசிய ஒற்றுமை பிளவுபடாதது என்பதை வலியுறுத்தவும்.",
    "To abolish the Supreme Court's judicial review power completely.",
    "உச்ச நீதிமன்றத்தின் நீதிப் புனராய்வு அதிகாரத்தை முற்றிலும் ஒழிக்க.",
    "To change India from a Union of States into a loose confederation.",
    "இந்தியாவை மாநிலங்களின் ஒன்றியத்திலிருந்து ஒரு தளர்வான கூட்டமைப்பாக மாற்ற.",
    "B",
    "The 42nd Constitutional Amendment Act 1976 added 'and integrity' to the Fraternity clause ('Unity and Integrity of the Nation'). This addition was designed to defeat secessionist and disintegrative forces, emphasizing that national integration encompasses both territorial integrity and psychological/emotional unity.",
    "1976 இன் 42வது அரசியலமைப்பு திருத்தச் சட்டம் சகோதரத்துவப் பகுதியில் 'மற்றும் ஒருமைப்பாடு' என்பதைச் சேர்த்தது. இந்தச் சேர்க்கை பிரிவினைவாத சக்திகளைத் தோற்கடிக்கவும், தேசிய ஒருமைப்பாடு நிலப்பரப்பு மற்றும் உணர்வுப்பூர்வமான ஒற்றுமை இரண்டையும் உள்ளடக்கியது என்பதை வலியுறுத்தவும் வடிவமைக்கப்பட்டது.",
    "Incorrect. Addition aimed to STOP secession, not encourage it.", "தவறு. சேர்க்கை பிரிவினைவாதத்தைத் தடுப்பதை நோக்கமாகக் கொண்டது.",
    "Correct. Added 'and Integrity' to combat secessionist tendencies and reinforce emotional & territorial oneness.", "சரி. பிரிவினைவாத போக்குகளை எதிர்க்கவும் உணர்வுப்பூர்வமான ஒற்றுமையை வலுப்படுத்தவும் 'மற்றும் ஒருமைப்பாடு' சேர்க்கப்பட்டது.",
    "Incorrect. Unrelated to judicial review abolition.", "தவறு. நீதிப் புனராய்வு ஒழிப்புடன் தொடர்பில்லாதது.",
    "Incorrect. India is an indestructible Union of destructible states (Art 1).", "தவறு. இந்தியா பிரிக்க முடியாத மாநிலங்களின் ஒன்றியமாகும் (உறுப்பு 1).",
    "42nd Amendment 1976 added 'and Integrity' to Fraternity to counter secessionism and strengthen territorial/emotional unity.",
    "42வது திருத்தம் 1976 பிரிவினைவாதத்தை எதிர்க்கவும் நிலப்பரப்பு/உணர்வுப்பூர்வ ஒற்றுமையை வலுப்படுத்தவும் சகோதரத்துவத்தில் 'மற்றும் ஒருமைப்பாடு' என்ற வார்த்தையைச் சேர்த்தது.",
    "K.M. Munshi described fraternity as ensuring both the dignity of the individual and the unity/integrity of the nation.",
    "கே.எம். முன்ஷி சகோதரத்துவத்தை தனிமனிதக் கண்ணியம் மற்றும் நாட்டின் ஒற்றுமை/ஒருமைப்பாடு இரண்டையும் உறுதி செய்வதாக விவரித்தார்.",
    ["Preamble", "42nd Amendment 1976", "Integrity", "Fraternity", "Secessionism"]
))

questions.append(make_q(
    "PRE_H_039", "Amendment + Basic Structure",
    "Can Parliament use its amending power under Article 368 to completely repeal or abrogate the Preamble of the Constitution?",
    "அரசியலமைப்பின் முகவுரையை முற்றிலும் ரத்து செய்ய அல்லது நீக்க பாராளுமன்றம் உறுப்பு 368 இன் கீழ் தனது திருத்தும் அதிகாரத்தைப் பயன்படுத்த முடியுமா?",
    "Yes, Parliament has absolute power under Article 368 to delete any part of the Constitution including the Preamble.",
    "ஆம், முகவுரை உட்பட அரசியலமைப்பின் எந்தப் பகுதியையும் நீக்க உறுப்பு 368 இன் கீழ் பாராளுமன்றத்திற்கு முழுமையான அதிகாரம் உள்ளது.",
    "Yes, provided the repeal is approved by a simple majority in Lok Sabha.",
    "ஆம், மக்களவையில் எளிய பெரும்பான்மையால் ரத்து ஒப்புதல் அளிக்கப்பட்டால் சரி.",
    "NO. Parliament cannot repeal or abrogate the Preamble because the Preamble contains the identity, philosophy, and Basic Structure of the Constitution; abrogating it would destroy constitutional identity.",
    "இல்லை. பாராளுமன்றம் முகவுரையை ரத்து செய்யவோ அல்லது நீக்கவோ முடியாது, ஏனெனில் முகவுரையில் அரசியலமைப்பின் அடையாளம், தத்துவம் மற்றும் அடிப்படை கட்டமைப்பு உள்ளது; அதை நீக்குவது அரசியலமைப்பு அடையாளத்தையே அழித்துவிடும்.",
    "NO, because the Preamble can only be repealed by an Act of the British Parliament.",
    "இல்லை, ஏனெனில் முகவுரையை பிரிட்டிஷ் பாராளுமன்றச் சட்டத்தால் மட்டுமே ரத்து செய்ய முடியும்.",
    "C",
    "Under the Basic Structure Doctrine established in Kesavananda Bharati (1973), Parliament's amending power under Article 368 is not a power to destroy or rewrite the Constitution. Since the Preamble embodies the basic features and identity of the Constitution (Sovereignty, Democracy, Secularism, Justice, Liberty, Equality), abrogating the Preamble would violate the Basic Structure and is unconstitutional.",
    "கேசவாநந்த பாரதி (1973) வழக்கின் அடிப்படை கட்டமைப்பு கோட்பாட்டின் கீழ், உறுப்பு 368 இன் கீழ் பாராளுமன்றத்தின் திருத்தும் அதிகாரம் அரசியலமைப்பை அழிக்கும் அதிகாரம் அல்ல.",
    "Incorrect. Amending power is bounded by Basic Structure Doctrine.", "தவறு. திருத்தும் அதிகாரம் அடிப்படை கட்டமைப்பு கோட்பாட்டால் வரம்பிற்குட்படுத்தப்பட்டுள்ளது.",
    "Incorrect. Article 368 requires special majority, and cannot destroy Basic Structure.", "தவறு. உறுப்பு 368 சிறப்பு பெரும்பான்மையைக் கோருகிறது, மேலும் அடிப்படை கட்டமைப்பை அழிக்க முடியாது.",
    "Correct. Parliament CANNOT repeal Preamble as it contains the Basic Structure & identity of the Constitution.", "சரி. முகவுரையில் அரசியலமைப்பின் அடிப்படை கட்டமைப்பு & அடையாளம் உள்ளதால் பாராளுமன்றம் அதை ரத்து செய்ய முடியாது.",
    "Incorrect. British Parliament has no authority over independent India.", "தவறு. சுதந்திர இந்தியாவின் மீது பிரிட்டிஷ் பாராளுமன்றத்திற்கு எந்த அதிகாரமும் இல்லை.",
    "Preamble CANNOT be repealed under Art 368 because it reflects the Basic Structure and Constitutional Identity.",
    "அடிப்படை கட்டமைப்பு மற்றும் அரசியலமைப்பு அடையாளத்தைப் பிரதிபலிப்பதால் உறுப்பு 368 இன் கீழ் முகவுரையை ரத்து செய்ய முடியாது.",
    "Minerva Mills (1980) affirmed that limited amending power under Art 368 is itself a Basic Feature.",
    "மினெர்வா மில்ஸ் (1980) உறுப்பு 368 இன் கீழ் வரம்பிற்குட்பட்ட திருத்தும் அதிகாரமே ஒரு அடிப்படை அம்சம் என்பதை உறுதிப்படுத்தியது.",
    ["Preamble", "Article 368", "Basic Structure", "Repeal Prohibition"]
))

questions.append(make_q(
    "PRE_H_040", "Amendment + Basic Structure",
    "Which of the following combinations correctly identifies principles in the Preamble that have been declared by the Supreme Court as part of the 'Basic Structure' of the Constitution?",
    "முகவுரையில் உள்ள எந்தக் கொள்கை சேர்க்கைகளை உச்ச நீதிமன்றம் அரசியலமைப்பின் 'அடிப்படை கட்டமைப்பின்' பகுதியாக அறிவித்துள்ளது என்பதைப் பின்வருவனவற்றில் எது சரியாக அடையாளம் காட்டுகிறது?",
    "Sovereignty, Secularism, Democracy, Republican character, and Justice", "இறையாண்மை, மதச்சார்பின்மை, ஜனநாயகம், குடியரசுத் தன்மை மற்றும் நீதி",
    "Hereditary Monarchy, Capitalism, State Religion, and Autocracy", "பரம்பரை முடியாட்சி, முதலாளித்துவம், அரசு மதம் மற்றும் தன்னிச்சையாட்சி",
    "Parliamentary Supremacy, Totalitarianism, and Unitary State Monopoly", "பாராளுமன்ற மேலாதிக்கம், சர்வாதிகாரம் மற்றும் ஒற்றையாட்சி அரசு ஏகபோகம்",
    "Executive Supremacy, Judicial Subordination, and Class Privilege", "நிர்வாக மேலாதிக்கம், நீதித்துறை கீழமைவு மற்றும் வர்க்க சலுகை",
    "A",
    "Through various landmark decisions (Kesavananda Bharati, Indira Gandhi, Minerva Mills, S.R. Bommai), the Supreme Court has recognized core principles embodied in the Preamble—Sovereignty, Secularism, Democracy, Republican nature, Liberty, Equality, Justice, and Unity/Integrity of the Nation—as pillars of the Basic Structure.",
    "பல்வேறு வரலாற்றுச் சிறப்புமிக்க தீர்ப்புகள் மூலம், முகவுரையில் பொதிந்துள்ள முக்கியக் கொள்கைகளை - இறையாண்மை, மதச்சார்பின்மை, ஜனநாயகம், குடியரசுத் தன்மை, சுதந்திரம், சமத்துவம், நீதி - உச்ச நீதிமன்றம் அடிப்படை கட்டமைப்பின் தூண்களாக அங்கீகரித்துள்ளது.",
    "Correct. Sovereignty, Secularism, Democracy, Republic, and Justice are established Basic Structure elements.", "சரி. இறையாண்மை, மதச்சார்பின்மை, ஜனநாயகம், குடியரசு மற்றும் நீதி ஆகியவை நிறுவப்பட்ட அடிப்படை கட்டமைப்பு கூறுகளாகும்.",
    "Incorrect. Hereditary monarchy and state religion contradict Preamble.", "தவறு. பரம்பரை முடியாட்சி மற்றும் அரசு மதம் முகவுரைக்கு முரண்படுகின்றன.",
    "Incorrect. Totalitarianism contradicts democratic preamble values.", "தவறு. சர்வாதிகாரம் ஜனநாயக முகவுரை மதிப்புகளுக்கு முரண்படுகிறது.",
    "Incorrect. Class privilege contradicts Republic and Equality.", "தவறு. வர்க்க சலுகை குடியரசு மற்றும் சமத்துவத்திற்கு முரண்படுகிறது.",
    "Basic Structure elements in Preamble: Sovereign, Socialist (Democratic), Secular, Democratic, Republic, Justice, Liberty, Equality, Unity & Integrity.",
    "முகவுரையில் உள்ள அடிப்படை கட்டமைப்பு கூறுகள்: இறையாண்மை, சமதர்ம, மதச்சார்பற்ற, ஜனநாயக, குடியரசு, நீதி, சுதந்திரம், சமத்துவம், ஒருமைப்பாடு.",
    "The Basic Structure Doctrine was formulated in Kesavananda Bharati v. State of Kerala (1973).",
    "அடிப்படை கட்டமைப்பு கோட்பாடு கேசவாநந்த பாரதி v. கேரள அரசு (1973) வழக்கில் உருவாக்கப்பட்டது.",
    ["Preamble", "Basic Structure Doctrine", "Secularism", "Democracy", "Sovereignty"]
))

with open("data/questions/polity/preamble_hard.json", "w", encoding="utf-8") as f:
    json.dump(questions, f, ensure_ascii=False, indent=2)

print("Saved Q1-Q40.")
