import json
from pathlib import Path

target_path = Path(r"c:\Users\Home\Desktop\tnpsc_ai\data\questions\polity\historical_background_medium.json")

def make_q(q_id, q_type, q_en, q_ta, opt_a_en, opt_a_ta, opt_b_en, opt_b_ta, opt_c_en, opt_c_ta, opt_d_en, opt_d_ta,
           correct_ans, exp_en, exp_ta, wno_a_en, wno_a_ta, wno_b_en, wno_b_ta, wno_c_en, wno_c_ta, wno_d_en, wno_d_ta,
           tip_en, tip_ta, rev_en, rev_ta, bloom, est_time, tags):
    opts = [
        {"id": "A", "en": opt_a_en, "ta": opt_a_ta},
        {"id": "B", "en": opt_b_en, "ta": opt_b_ta},
        {"id": "C", "en": opt_c_en, "ta": opt_c_ta},
        {"id": "D", "en": opt_d_en, "ta": opt_d_ta}
    ]
    opts_en = [opt_a_en, opt_b_en, opt_c_en, opt_d_en]
    opts_ta = [opt_a_ta, opt_b_ta, opt_c_ta, opt_d_ta]
    
    return {
        "id": q_id,
        "subject": "Polity",
        "topic": "Historical Background",
        "difficulty": "Medium",
        "question_type": q_type,
        "question": {"en": q_en, "ta": q_ta},
        "options": opts,
        "correct_answer": correct_ans,
        "explanation": {"en": exp_en, "ta": exp_ta},
        "why_not_others": {
            "A": {"en": wno_a_en, "ta": wno_a_ta},
            "B": {"en": wno_b_en, "ta": wno_b_ta},
            "C": {"en": wno_c_en, "ta": wno_c_ta},
            "D": {"en": wno_d_en, "ta": wno_d_ta}
        },
        "tnpsc_tip": {"en": tip_en, "ta": tip_ta},
        "revision_fact": {"en": rev_en, "ta": rev_ta},
        "source_reference": ["M. Laxmikanth - Indian Polity", "NCERT", "Samacheer Kalvi"],
        "bloom_level": bloom,
        "estimated_time_sec": est_time,
        "pyq_similarity": "High",
        "tags": tags,
        "question_en": q_en,
        "question_ta": q_ta,
        "options_en": opts_en,
        "options_ta": opts_ta,
        "answer": correct_ans.lower(),
        "explanation_en": exp_en,
        "explanation_ta": exp_ta
    }

questions = []

# ---------------------------------------------------------
# 15 CONCEPTUAL QUESTIONS (HB_M_001 to HB_M_015)
# ---------------------------------------------------------

questions.append(make_q(
    "HB_M_001", "Conceptual",
    "Which of the following was the primary constitutional significance of establishing the Supreme Court of Judicature at Fort William in Calcutta under the Regulating Act of 1773?",
    "1773 ஆம் ஆண்டின் ஒழுங்குமுறைச் சட்டத்தின் கீழ் கொல்கத்தா ஃபோர்ட் வில்லியமில் உச்சநீதிமன்றம் அமைக்கப்பட்டதன் முதன்மை அரசியலமைப்பு முக்கியத்துவம் யாது?",
    "It established a supreme judicial body having jurisdiction over all native rulers in India.",
    "இது இந்தியாவில் உள்ள அனைத்து சுதேசி ஆட்சியாளர்கள் மீதும் அதிகார வரம்பு கொண்ட உச்ச நீதி அமைப்பை நிறுவியது.",
    "It created an independent judicial authority to restrain the arbitrary actions of Company officials and enforce British law.",
    "இது கம்பெனி அதிகாரிகளின் தன்னிச்சையான நடவடிக்கைகளைக் கட்டுப்படுத்தவும் பிரிட்டிஷ் சட்டத்தைச் செயல்படுத்தவும் ஒரு சுயாதீன நீதித்துறை அமைப்பை உருவாக்கியது.",
    "It replaced the Mayor's Courts in Bombay and Madras completely.",
    "இது பம்பாய் மற்றும் மதராஸில் உள்ள மேயர் நீதிமன்றங்களை முழுமையாக மாற்றீடு செய்தது.",
    "It established appellate jurisdiction over the House of Lords in London.",
    "இது லண்டனில் உள்ள பிரபுக்கள் சபையின் மேல்முறையீட்டு அதிகார வரம்பை நிறுவியது.",
    "B",
    "The Regulating Act of 1773 established a Supreme Court at Calcutta (1774) with a Chief Justice (Sir Elijah Impey) and 3 other judges to control and regulate Company officials who were engaging in private trade and corruption.",
    "1773 ஒழுங்குமுறைச் சட்டம் 1774 இல் கொல்கத்தாவில் ஒரு தலைமை நீதிபதி (சர் எலிஜா இம்பே) மற்றும் 3 நீதிபதிகளுடன் உச்ச நீதிமன்றத்தை நிறுவி, தனிப்பட்ட வர்த்தகம் மற்றும் ஊழலில் ஈடுபட்ட கம்பெனி அதிகாரிகளைக் கட்டுப்படுத்தியது.",
    "Incorrect. It had no jurisdiction over native Indian rulers outside British possessions unless by mutual agreement.",
    "தவறு. பரஸ்பர ஒப்பந்தம் இன்றி பிரிட்டிஷ் ஆட்சிக்குட்பட்ட பகுதிகளுக்கு வெளியே உள்ள சுதேசி ஆட்சியாளர்கள் மீது அதிகார வரம்பு இல்லை.",
    "Correct. The Supreme Court was created to provide a legal check over East India Company servants.",
    "சரி. கிழக்கிந்தியக் கம்பெனி ஊழியர்கள் மீது சட்டப் பூர்வக் கட்டுப்பாட்டை ஏற்படுத்த உச்ச நீதிமன்றம் உருவாக்கப்பட்டது.",
    "Incorrect. Mayor's Courts in Bombay and Madras continued until Courts of Recorder were introduced in 1797.",
    "தவறு. பம்பாய் மற்றும் மதராஸில் மேயர் நீதிமன்றங்கள் 1797 வரை தொடர்ந்தன.",
    "Incorrect. Appeals from this Supreme Court actually lay to the Privy Council in London, not House of Lords.",
    "தவறு. இந்த உச்ச நீதிமன்றத்தின் மேல்முறையீடுகள் லண்டனில் உள்ள பிரிவி கவுன்சிலுக்கு சென்றன, பிரபுக்கள் சபைக்கு அல்ல.",
    "Distinguish Supreme Court jurisdiction (1774) vs Provincial Courts. Appeals from Calcutta SC went to the Privy Council.",
    "கொல்கத்தா உச்ச நீதிமன்ற அதிகார வரம்பையும் மாகாண நீதிமன்றங்களையும் வேறுபடுத்திப் பார்க்கவும். மேல்முறையீடு பிரிவி கவுன்சிலுக்குச் சென்றது.",
    "Supreme Court at Calcutta was established in 1774 with Sir Elijah Impey as the first Chief Justice.",
    "1774 இல் கொல்கத்தா உச்ச நீதிமன்றத்தின் முதல் தலைமை நீதிபதியாக சர் எலிஜா இம்பே நியமிக்கப்பட்டார்.",
    "Understand", 60, ["Polity", "Historical Background", "Regulating Act 1773", "Supreme Court"]
))

questions.append(make_q(
    "HB_M_002", "Conceptual",
    "What was the main purpose of enacting the Amending Act of 1781 (also known as the Act of Settlement)?",
    "1781 ஆம் ஆண்டின் திருத்தச் சட்டம் (சமரசச் சட்டம்) இயற்றப்பட்டதன் முதன்மை நோக்கம் யாது?",
    "To abolish the Board of Control created by the British Cabinet.",
    "பிரிட்டிஷ் அமைச்சரவையால் உருவாக்கப்பட்ட கட்டுப்பாட்டு வாரியத்தைக் கலைப்பது.",
    "To demarcate boundaries between the Supreme Court and the Governor-General in Council and exempt revenue collectors from SC jurisdiction.",
    "உச்ச நீதிமன்றத்திற்கும் கவர்னர் ஜெனரல் கவுன்சிலுக்கும் இடையிலான எல்லைகளை வரையறுத்து, வருவாய் வசூலிப்பாளர்களை உச்சநீதிமன்ற அதிகார வரம்பிலிருந்து விலக்குவது.",
    "To introduce Macaulay's penal code across Company territories.",
    "கம்பெனி பகுதிகள் முழுவதும் மெக்காலேயின் தண்டனைச் சட்டத்தை அறிமுகப்படுத்துவது.",
    "To grant financial autonomy to Madras and Bombay Presidencies.",
    "மதராஸ் மற்றும் பம்பாய் மாகாணங்களுக்கு நிதி தன்னாட்சி வழங்குவது.",
    "B",
    "The Amending Act of 1781 was passed to remedy defects of the 1773 Act by exempting the Governor-General, his council, and revenue officials from Supreme Court jurisdiction for acts performed in official capacity.",
    "1781 திருத்தச் சட்டம், 1773 சட்டத்தின் குறைபாடுகளை நீக்க இயற்றப்பட்டது. இது கவர்னர் ஜெனரல், அவரது கவுன்சில் மற்றும் வருவாய் அதிகாரிகளை அவர்களின் அதிகாரப்பூர்வ பணிகளுக்காக உச்சநீதிமன்ற அதிகார வரம்பிலிருந்து விலக்கியது.",
    "Incorrect. The Board of Control was created later by Pitt's India Act 1784.",
    "தவறு. கட்டுப்பாட்டு வாரியம் 1784 பிட் இந்தியச் சட்டத்தின் மூலமே உருவாக்கப்பட்டது.",
    "Correct. It defined revenue jurisdiction and protected official actions of Governor-General in Council.",
    "சரி. இது வருவாய் அதிகார வரம்பை வரையறுத்து கவர்னர் ஜெனரல் கவுன்சிலின் அதிகாரப்பூர்வ நடவடிக்கைகளைப் பாதுகாத்தது.",
    "Incorrect. Law Commission and Macaulay came under Charter Act of 1833.",
    "தவறு. சட்ட ஆணையமும் மெக்காலேயும் 1833 சாசனச் சட்டத்தின் கீழ் வந்தனர்.",
    "Incorrect. Financial autonomy was gradually granted much later under 1861, 1870, and 1919 developments.",
    "தவறு. நிதி தன்னாட்சி பிற்கால 1861, 1870 மற்றும் 1919 மாற்றங்களிலேயே வழங்கப்பட்டது.",
    "1781 Act is called 'Act of Settlement' because it settled disputes between Executive (GG-in-Council) and Judiciary (SC).",
    "1781 சட்டம் 'சமரசச் சட்டம்' எனப்படுகிறது, ஏனெனில் இது நிர்வாகத்திற்கும் (GG-கவுன்சில்) நீதித்துறைக்கும் (SC) இடையிலான மோதல்களைத் தீர்த்தது.",
    "1781 Act excluded revenue matters and official actions from Supreme Court jurisdiction.",
    "1781 ஆம் ஆண்டு சட்டம் வருவாய் விவகாரங்களையும் அதிகாரப்பூர்வ பணிகளையும் உச்ச நீதிமன்ற அதிகார வரம்பிலிருந்து விலக்கியது.",
    "Understand", 60, ["Polity", "Historical Background", "Amending Act 1781", "Act of Settlement"]
))

questions.append(make_q(
    "HB_M_003", "Conceptual",
    "How did Pitt's India Act of 1784 establish a system of 'Double Government' in British administration of India?",
    "1784 ஆம் ஆண்டின் பிட் இந்தியச் சட்டம் பிரிட்டிஷ் இந்திய நிர்வாகத்தில் எவ்வாறு 'இரட்டை ஆட்சி' முறையை நிறுவியது?",
    "By establishing separate executive and legislative councils in Bengal.",
    "வங்காளத்தில் தனித்தனி நிர்வாக மற்றும் சட்டமன்ற கவுன்சில்களை நிறுவியதன் மூலம்.",
    "By separating commercial functions (Court of Directors) and political functions (Board of Control) of the East India Company.",
    "கிழக்கிந்தியக் கம்பெனியின் வர்த்தகப் பணிகளையும் (இயக்குநர்கள் அவை) அரசியல் பணிகளையும் (கட்டுப்பாட்டு வாரியம்) பிரித்ததன் மூலம்.",
    "By dividing powers between the British Crown and Indian Princely States.",
    "பிரிட்டிஷ் முடிஅரசு மற்றும் இந்திய சுதேச சமஸ்தானங்களுக்கு இடையே அதிகாரங்களைப் பகிர்ந்ததன் மூலம்.",
    "By introducing Dyarchy with reserved and transferred subjects in provinces.",
    "மாகாணங்களில் ஒதுக்கப்பட்ட மற்றும் மாற்றப்பட்ட துறைகளுடன் இரட்டை ஆட்சியை அறிமுகப்படுத்தியதன் மூலம்.",
    "B",
    "Pitt's India Act 1784 created a Board of Control (6 Privy Councillors) to manage political affairs while leaving commercial operations to Court of Directors, establishing System of Double Government.",
    "1784 பிட் இந்தியச் சட்டம் அரசியல் விவகாரங்களை நிர்வகிக்க கட்டுப்பாட்டு வாரியத்தை (6 உறுப்பினர்கள்) உருவாக்கியது, வர்த்தகப் பணிகளை இயக்குநர்கள் அவையிடம் விட்டது. இதுவே இரட்டை ஆட்சி முறை எனப்பட்டது.",
    "Incorrect. Executive/Legislative separation in councils happened under Charter Act 1853.",
    "தவறு. நிர்வாக மற்றும் சட்டமன்றப் பிரிவு 1853 சாசனச் சட்டத்தில்தான் நடந்தது.",
    "Correct. It separated commercial (Court of Directors) and political (Board of Control) administration.",
    "சரி. இது வர்த்தக மற்றும் அரசியல் நிர்வாகத்தைப் பிரித்தது.",
    "Incorrect. Division with princely states was part of later federal schemes (1935).",
    "தவறு. சுதேச சமஸ்தானப் பங்களிப்பு 1935 கூட்டாட்சி திட்டத்தின் பகுதி.",
    "Incorrect. Dyarchy with reserved/transferred subjects was introduced by GOI Act 1919.",
    "தவறு. ஒதுக்கப்பட்ட/மாற்றப்பட்ட துறைகளுடன் கூடிய இரட்டை ஆட்சி 1919 சட்டத்தால் வந்தது.",
    "Do not confuse Double Government of 1784 (Board of Control vs Court of Directors) with Dyarchy of 1919 (Provincial Subjects).",
    "1784 இன் இரட்டை நிர்வாகத்தையும் (Board of Control vs Court of Directors) 1919 இன் மாகாண இரட்டை ஆட்சியையும் குழப்பிக் கொள்ளக் கூடாது.",
    "Pitt's India Act 1784 used the term 'British possessions in India' for the first time.",
    "1784 பிட் இந்தியச் சட்டம் முதன்முறையாக 'இந்தியாவில் உள்ள பிரிட்டிஷ் உடமைகள்' என்ற சொல்லைப் பயன்படுத்தியது.",
    "Understand", 60, ["Polity", "Historical Background", "Pitt's India Act 1784", "Double Government"]
))

questions.append(make_q(
    "HB_M_004", "Conceptual",
    "Which Charter Act mandated that the salaries and expenses of the Board of Control and their staff should be charged upon the revenues of India?",
    "கட்டுப்பாட்டு வாரியம் மற்றும் அதன் ஊழியர்களின் ஊதியம் மற்றும் செலவுகள் இந்திய வருவாயிலிருந்தே வழங்கப்பட வேண்டும் என்று கட்டாயப்படுத்திய சாசனச் சட்டம் எது?",
    "Charter Act of 1793", "1793 ஆம் ஆண்டின் சாசனச் சட்டம்",
    "Charter Act of 1813", "1813 ஆம் ஆண்டின் சாசனச் சட்டம்",
    "Charter Act of 1833", "1833 ஆம் ஆண்டின் சாசனச் சட்டம்",
    "Charter Act of 1853", "1853 ஆம் ஆண்டின் சாசனச் சட்டம்",
    "A",
    "The Charter Act of 1793 mandated that the Board of Control members and staff were henceforth to be paid out of Indian revenues. This practice continued until the Government of India Act 1919.",
    "1793 ஆம் ஆண்டின் சாசனச் சட்டம் கட்டுப்பாட்டு வாரிய உறுப்பினர்கள் மற்றும் ஊழியர்களின் சம்பளம் இனி இந்திய வருவாயிலிருந்தே வழங்கப்பட வேண்டும் என்று கூறியது. இது 1919 வரை தொடர்ந்தது.",
    "Correct. Charter Act 1793 started paying Board of Control salaries out of Indian revenues.",
    "சரி. 1793 சாசனச் சட்டம் கட்டுப்பாட்டு வாரியத்தின் சம்பளத்தை இந்திய வருவாயிலிருந்து வழங்கத் தொடங்கியது.",
    "Incorrect. Charter Act 1813 ended Company trade monopoly except tea and trade with China.",
    "தவறு. 1813 சாசனச் சட்டம் தேயிலை மற்றும் சீனா வர்த்தகம் தவிர கம்பெனியின் வர்த்தக ஏகபோகத்தை முடிவுக்கு கொண்டு வந்தது.",
    "Incorrect. Charter Act 1833 made Governor-General of Bengal into Governor-General of India.",
    "தவறு. 1833 சாசனச் சட்டம் வங்காள கவர்னர் ஜெனரலை இந்திய கவர்னர் ஜெனரலாக மாற்றியது.",
    "Incorrect. Charter Act 1853 created the Indian Legislative Council.",
    "தவறு. 1853 சாசனச் சட்டம் இந்திய சட்டமன்ற கவுன்சிலை உருவாக்கியது.",
    "Paying British officials out of Indian revenues laid the economic root of Dadabhai Naoroji's 'Drain of Wealth' theory.",
    "இந்திய வருவாயில் பிரிட்டிஷ் அதிகாரிகளுக்கு சம்பளம் வழங்கியது தாதாபாய் நௌரோஜியின் 'செல்வச் சுரண்டல்' கோட்பாட்டிற்கு அடித்தளமிட்டது.",
    "1793 Act extended Company trade monopoly for another 20 years and required Board of Control salaries from Indian revenue.",
    "1793 சட்டம் கம்பெனியின் வர்த்தக ஏகபோகத்தை மேலும் 20 ஆண்டுகளுக்கு நீட்டித்ததுடன் இந்திய வருவாயிலிருந்து சம்பளம் வழங்க உத்தரவிட்டது.",
    "Remember", 60, ["Polity", "Historical Background", "Charter Act 1793", "Drain of Wealth"]
))

questions.append(make_q(
    "HB_M_005", "Conceptual",
    "What was a landmark feature introduced by the Charter Act of 1813 regarding social and educational evolution in British India?",
    "பிரிட்டிஷ் இந்தியாவின் சமூக மற்றும் கல்வி வளர்ச்சியில் 1813 ஆம் ஆண்டின் சாசனச் சட்டம் அறிமுகப்படுத்திய ஒரு மைல்கல் அம்சம் யாது?",
    "It established compulsory primary education across all presidencies.",
    "இது அனைத்து மாகாணங்களிலும் கட்டாயத் தொடக்கக் கல்வியை நிறுவியது.",
    "It set aside a sum of Rupees One Lakh annually for promotion of literature, learning, and science among Indians, and permitted Christian missionaries to operate.",
    "இந்தியர்களிடையே இலக்கியம், கல்வி மற்றும் அறிவியலை மேம்படுத்த ஆண்டிற்கு ரூ. 1 லட்சம் ஒதுக்கியதுடன், கிறிஸ்தவ மிஷனரிகள் செயல்பட அனுமதித்தது.",
    "It created the first Indian University in Calcutta.",
    "இது கொல்கத்தாவில் முதல் இந்தியப் பல்கலைக்கழகத்தை உருவாக்கியது.",
    "It abolished English as the official language of courts.",
    "இது நீதிமன்றங்களின் அதிகாரப்பூர்வ மொழியாக ஆங்கிலத்தை நீக்கியது.",
    "B",
    "Charter Act 1813 ended EIC's trade monopoly in India (except tea and China trade), asserted Crown sovereignty over Company territories, allocated Rs 1 Lakh for education, and allowed Christian missionaries to preach.",
    "1813 சாசனச் சட்டம் கம்பெனியின் வர்த்தக ஏகபோகத்தை (தேயிலை மற்றும் சீனா வர்த்தகம் தவிர) ரத்து செய்தது, கல்விக்காக ரூ. 1 லட்சம் ஒதுக்கியது, மற்றும் கிறிஸ்தவ மிஷனரிகளுக்கு அனுமதி அளித்தது.",
    "Incorrect. Primary education was not made compulsory by this Act.",
    "தவறு. இந்த சட்டத்தின் மூலம் தொடக்கக் கல்வி கட்டாயமாக்கப்படவில்லை.",
    "Correct. Allocated Rs 1 Lakh for education and allowed Christian missionaries.",
    "சரி. கல்விக்கு ரூ. 1 லட்சம் ஒதுக்கியதுடன் மிஷனரிகளையும் அனுமதித்தது.",
    "Incorrect. Universities of Calcutta, Bombay, Madras were set up in 1857 following Wood's Despatch (1854).",
    "தவறு. கொல்கத்தா, பம்பாய், மதராஸ் பல்கலைக்கழகங்கள் 1857 இல் அமைக்கப்பட்டன.",
    "Incorrect. English became official language of higher courts later in 1835/1837.",
    "தவறு. ஆங்கிலம் நீதிமன்ற மொழியானது 1835/1837 காலக்கட்டத்திலாகும்.",
    "1813 Act stripped commercial monopoly EXCEPT Tea trade and Trade with China (which were abolished in 1833).",
    "1813 சட்டம் தேயிலை மற்றும் சீனா வர்த்தகம் தவிர மற்ற ஏகபோகத்தை முடித்தது (அவை 1833 இல் முடிந்தன).",
    "Charter Act 1813 allocated Rs 1 Lakh annually for education in India.",
    "1813 சாசனச் சட்டம் இந்தியாவில் கல்விக்காக ஆண்டிற்கு ரூ. 1 லட்சம் ஒதுக்கியது.",
    "Understand", 60, ["Polity", "Historical Background", "Charter Act 1813", "Education"]
))

questions.append(make_q(
    "HB_M_006", "Conceptual",
    "The Charter Act of 1833 is considered the climax of administrative centralization in British India. Which of the following structural changes directly brought about this centralization?",
    "1833 ஆம் ஆண்டின் சாசனச் சட்டம் பிரிட்டிஷ் இந்தியாவில் நிர்வாக மத்தியமயமாக்கலின் உச்சகட்டமாகக் கருதப்படுகிறது. பின்வரும் எந்த கட்டமைப்பு மாற்றம் இந்த மத்தியமயமாக்கலை நேரடியாகக் கொண்டு வந்தது?",
    "It designated the Governor-General of Bengal as the Governor-General of India and deprived Governors of Bombay and Madras of their legislative powers.",
    "இது வங்காள கவர்னர் ஜெனரலை இந்திய கவர்னர் ஜெனரலாக மாற்றி, பம்பாய் மற்றும் மதராஸ் கவர்னர்களின் சட்டமியற்றும் அதிகாரங்களைப் பறித்தது.",
    "It created separate Provincial Legislative Assemblies for Bombay, Madras, and Bengal.",
    "இது பம்பாய், மதராஸ் மற்றும் வங்காளத்திற்கு தனித்தனியாக மாகாண சட்டமன்றங்களை உருவாக்கியது.",
    "It created a Supreme Court in every presidency capital.",
    "இது ஒவ்வொரு மாகாணத் தலைநகரிலும் ஒரு உச்ச நீதிமன்றத்தை உருவாக்கியது.",
    "It transferred the administration of India directly to the British Parliament.",
    "இது இந்தியாவின் நிர்வாகத்தை நேரடியாக பிரிட்டிஷ் பாராளுமன்றத்திற்கு மாற்றியது.",
    "A",
    "The Charter Act of 1833 redesignated the Governor-General of Bengal as Governor-General of India (Lord William Bentinck was first) and vested all civil and military powers in him, centralizing lawmaking exclusively at the Centre.",
    "1833 சாசனச் சட்டம் வங்காள கவர்னர் ஜெனரலை இந்திய கவர்னர் ஜெனரலாக (முதல் நபர்: வில்லியம் பென்டிங்க் பிரபு) மாற்றியதுடன், அனைத்து சிவில் மற்றும் இராணுவ அதிகாரங்களையும் அவரிடம் வழங்கி, சட்டமியற்றும் அதிகாரத்தை மையப்படுத்தியது.",
    "Correct. Made GG of Bengal as GG of India and concentrated all legislative powers in his council.",
    "சரி. வங்காள GG-ஐ இந்திய GG-ஆக மாற்றி சட்டமியற்றும் அதிகாரத்தை மையத்தில் குவித்து பம்பாய்/மதராஸ் அதிகாரத்தைப் பறித்தது.",
    "Incorrect. Provincial legislative powers were deprived by this Act, not created.",
    "தவறு. மாகாண சட்டமியற்றும் அதிகாரங்கள் இந்த சட்டத்தால் பறிக்கப்பட்டன.",
    "Incorrect. Supreme Courts were not created in every presidency capital by 1833.",
    "தவறு. 1833 இல் அனைத்து மாகாணத் தலைநகரங்களிலும் உச்ச நீதிமன்றங்கள் உருவாக்கப்படவில்லை.",
    "Incorrect. Direct transfer to British Crown/Parliament took place under Government of India Act 1858.",
    "தவறு. பிரிட்டிஷ் முடிஅரசுக்கு நேரடி நிர்வாக மாற்றம் 1858 ஆம் ஆண்டு சட்டத்தில் நடந்தது.",
    "1833 Act created 'Governor-General of India' and laws made under it were called 'Acts' (earlier called 'Regulations').",
    "1833 சட்டத்திற்கு முன் இயற்றப்பட்ட விதிகள் 'ஒழுங்குமுறைகள்' (Regulations) எனப்பட்டன, இதன் பின் இயற்றப்பட்டவை 'சட்டங்கள்' (Acts) எனப்பட்டன.",
    "Lord William Bentinck became the first Governor-General of India under Charter Act 1833.",
    "1833 சாசனச் சட்டத்தின் கீழ் வில்லியம் பென்டிங்க் பிரபு இந்தியாவின் முதல் கவர்னர் ஜெனரலானார்.",
    "Understand", 60, ["Polity", "Historical Background", "Charter Act 1833", "Centralization"]
))

questions.append(make_q(
    "HB_M_007", "Conceptual",
    "Which Charter Act introduced for the first time a distinction between executive and legislative functions of the Governor-General's Council and created a 6-member Indian (Central) Legislative Council?",
    "கவர்னர் ஜெனரல் கவுன்சிலின் நிர்வாக மற்றும் சட்டமன்றப் பணிகளுக்கு இடையே முதன்முறையாக வேறுபாட்டை அறிமுகப்படுத்தி 6 உறுப்பினர்களைக் கொண்ட இந்திய (மத்திய) சட்டமன்ற கவுன்சிலை உருவாக்கிய சாசனச் சட்டம் எது?",
    "Charter Act of 1813", "1813 ஆம் ஆண்டின் சாசனச் சட்டம்",
    "Charter Act of 1833", "1833 ஆம் ஆண்டின் சாசனச் சட்டம்",
    "Charter Act of 1853", "1853 ஆம் ஆண்டின் சாசனச் சட்டம்",
    "Government of India Act 1858", "1858 ஆம் ஆண்டின் இந்திய அரசுச் சட்டம்",
    "C",
    "Charter Act of 1853 added 6 new legislative members (called Legislative Councillors) to the Governor-General's Council, functioning as a 'Mini-Parliament' adopting British parliamentary procedure, and introduced open competition for Civil Services (Macaulay Committee 1854).",
    "1853 சாசனச் சட்டம் கவர்னர் ஜெனரல் கவுன்சிலில் 6 புதிய சட்டமன்ற உறுப்பினர்களைச் சேர்த்தது ('மினி பாராளுமன்றம்'). மேலும் இது குடிமைப் பணிகளுக்கான திறந்தவெளிப் போட்டித் தேர்வை அறிமுகப்படுத்தியது (மெக்காலே குழு 1854).",
    "Incorrect. Charter Act 1813 dealt with trade monopoly and education.",
    "தவறு. 1813 சாசனச் சட்டம் வர்த்தக ஏகபோகம் மற்றும் கல்வியைப் பற்றியது.",
    "Incorrect. Charter Act 1833 added Law Member (Macaulay) to executive council without separate legislative body.",
    "தவறு. 1833 சாசனச் சட்டம் சட்ட உறுப்பினரை (மெக்காலே) சேர்த்தது ஆனால் தனி சட்டமன்ற உடலை உருவாக்கவில்லை.",
    "Correct. Charter Act 1853 created Central Legislative Council and separated legislative/executive functions.",
    "சரி. 1853 சாசனச் சட்டம் மத்திய சட்டமன்ற கவுன்சிலை உருவாக்கி சட்டமன்ற/நிர்வாகப் பணிகளைப் பிரித்தது.",
    "Incorrect. GOI Act 1858 transferred power to Crown.",
    "தவறு. 1858 இந்திய அரசுச் சட்டம் அதிகாரத்தை பிரிட்டிஷ் அரசிற்கு மாற்றியது.",
    "Charter Act 1853 introduced local representation in Central Legislative Council: 4 out of 6 new members were appointed by local governments of Madras, Bombay, Bengal, and Agra.",
    "1853 சாசனச் சட்டம் மத்திய சட்டமன்ற கவுன்சிலில் உள்ளூர் பிரதிநிதித்துவத்தை அறிமுகப்படுத்தியது (மதராஸ், பம்பாய், வங்காளம், ஆக்ரா).",
    "Charter Act 1853 was the last of the series of Charter Acts passed between 1793 and 1853.",
    "1793 மற்றும் 1853 க்கு இடையில் இயற்றப்பட்ட சாசனச் சட்டங்களின் வரிசையில் 1853 சாசனச் சட்டமே கடைசியானதாகும்.",
    "Understand", 60, ["Polity", "Historical Background", "Charter Act 1853", "Legislative Council"]
))

questions.append(make_q(
    "HB_M_008", "Conceptual",
    "The Government of India Act 1858 (Act for the Good Government of India) substituted Company rule with Crown rule. Which of the following offices was created by this Act to exercise direct control over Indian administration from London?",
    "1858 ஆம் ஆண்டின் இந்திய அரசுச் சட்டம் கம்பெனி ஆட்சியை முடிஆட்சிக்கு மாற்றியது. லண்டனிலிருந்து இந்திய நிர்வாகத்தின் மீது நேரடி அதிகாரத்தைச் செலுத்த இந்தச் சட்டத்தால் உருவாக்கப்பட்ட அலுவலகம் எது?",
    "High Commissioner for India", "இந்திய உயர் ஆணையர்",
    "Secretary of State for India", "இந்திய அரசுச் செயலாளர் (செயலர்)",
    "Viceroy and Governor-General of India", "இந்திய வைஸ்ராய் மற்றும் கவர்னர் ஜெனரல்",
    "President of the Board of Control", "கட்டுப்பாட்டு வாரியத்தின் தலைவர்",
    "B",
    "The GOI Act 1858 created the office of 'Secretary of State for India', a cabinet minister of British Parliament, assisted by a 15-member advisory Council of India. Lord Stanley was the first Secretary of State for India.",
    "1858 இந்திய அரசுச் சட்டம் பிரிட்டிஷ் அமைச்சரவை உறுப்பினரான 'இந்திய அரசுச் செயலாளர்' அலுவலகத்தை உருவாக்கியது. இவருக்கு உதவ 15 உறுப்பினர்களைக் கொண்ட 'இந்திய கவுன்சில்' அமைக்கப்பட்டது.",
    "Incorrect. High Commissioner for India was created later under Government of India Act 1919.",
    "தவறு. இந்திய உயர் ஆணையர் பதவி பிற்காலத்தில் 1919 ஆம் ஆண்டு சட்டத்தின் கீழ் உருவாக்கப்பட்டது.",
    "Correct. Created Secretary of State for India residing in London with ultimate control.",
    "சரி. லண்டனில் தங்கி முழு நிர்வாகக் கட்டுப்பாட்டைக் கொண்ட இந்திய அரசுச் செயலாளர் பதவி உருவாக்கப்பட்டது.",
    "Incorrect. Viceroy was the direct representative of the Crown in India, but Secretary of State exercised ultimate authority from London.",
    "தவறு. வைஸ்ராய் இந்தியாவில் பிரிட்டிஷ் அரசியின் பிரதிநிதி, ஆனால் லண்டனிலிருந்து முழு அதிகாரம் செலுத்தியவர் அரசுச் செயலாளரே.",
    "Incorrect. Board of Control was abolished by the 1858 Act.",
    "தவறு. கட்டுப்பாட்டு வாரியம் 1858 சட்டத்தின் மூலம் கலைக்கப்பட்டது.",
    "Distinguish roles: Secretary of State was based in London (Cabinet Minister); Viceroy was based in Calcutta/Delhi as Crown representative.",
    "வேறுபாட்டை உணர்க: அரசுச் செயலாளர் லண்டனில் இருந்தார்; வைஸ்ராய் இந்தியாவில் பிரிட்டிஷ் மகாராணியின் பிரதிநிதியாக இருந்தார்.",
    "Lord Canning became the first Viceroy of India under GOI Act 1858.",
    "1858 ஆம் ஆண்டு சட்டத்தின் கீழ் லார்ட் கேனிங் இந்தியாவின் முதல் வைஸ்ராயானார்.",
    "Understand", 60, ["Polity", "Historical Background", "Government of India Act 1858", "Secretary of State"]
))

questions.append(make_q(
    "HB_M_009", "Conceptual",
    "The Indian Councils Act of 1861 initiated the process of associating Indians with the law-making process. Which Indians were nominated by Lord Canning to the expansion of his Central Legislative Council in 1862?",
    "1861 ஆம் ஆண்டின் இந்தியக் கவுன்சில்கள் சட்டம் இந்தியர்களைச் சட்டமியற்றும் பணியில் இணைக்கும் செயல்முறையைத் தொடங்கியது. 1862 இல் லார்ட் கேனிங்கால் மத்திய சட்டமன்ற கவுன்சிலில் நியமிக்கப்பட்ட இந்தியர்கள் யாவர்?",
    "Raja of Benares, Maharaja of Patiala, and Sir Dinkar Rao",
    "காசி (பனாரஸ்) ராஜா, பாட்டியாலா மகாராஜா, மற்றும் சர் தினகர் ராவ்",
    "Dadabhai Naoroji, Gopal Krishna Gokhale, and Pherozeshah Mehta",
    "தாதாபாய் நௌரோஜி, கோபால கிருஷ்ண கோகலே, மற்றும் பிரோஸ்ஷா மேத்தா",
    "Satyendra Prasad Sinha, Motilal Nehru, and Tej Bahadur Sapru",
    "சத்யேந்திர பிரசாத் சின்ஹா, மோதிலால் நேரு, மற்றும் தேஜ் பகதூர் சப்ரு",
    "Swami Vivekananda, Bal Gangadhar Tilak, and Lala Lajpat Rai",
    "சுவாமி விவேகானந்தர், பால கங்காதர திலகர், மற்றும் லாலா லஜபதி ராய்",
    "A",
    "In 1862, Lord Canning nominated three non-official Indian members to his expanded legislative council under Indian Councils Act 1861: Raja of Benares, Maharaja of Patiala, and Sir Dinkar Rao.",
    "1861 இந்தியக் கவுன்சில்கள் சட்டத்தின் கீழ் 1862 இல் லார்ட் கேனிங் மூன்று இந்திய உறுப்பினர்களைத் தனது விரிவாக்கப்பட்ட சட்டமன்றக் குழுவில் நியமித்தார்: காசி ராஜா, பாட்டியாலா மகாராஜா, மற்றும் சர் தினகர் ராவ்.",
    "Correct. Raja of Benares, Maharaja of Patiala, and Sir Dinkar Rao were nominated in 1862.",
    "சரி. காசி ராஜா, பாட்டியாலா மகாராஜா மற்றும் சர் தினகர் ராவ் ஆகிய 3 நபர்கள் 1862 இல் நியமிக்கப்பட்டனர்.",
    "Incorrect. Moderates like Naoroji and Gokhale came much later into legislative prominence.",
    "தவறு. நௌரோஜி, கோகலே போன்றோர் பிற்கால அரசியல் தலைவர்கள்.",
    "Incorrect. S.P. Sinha was the first Indian appointed to Viceroy's Executive Council under 1909 Act.",
    "தவறு. எஸ்.பி. சின்ஹா 1909 சட்டத்தின் கீழ் வைஸ்ராயின் நிர்வாக கவுன்சிலில் சேர்ந்த முதல் இந்தியர்.",
    "Incorrect. Extremist leaders like Tilak were not nominated to Viceroy's council.",
    "தவறு. திலகர் போன்ற தீவிர தேசிய தலைவர்கள் வைஸ்ராய் கவுன்சிலுக்கு நியமிக்கப்படவில்லை.",
    "Indian Councils Act 1861 also legalized the Portfolio System (introduced by Canning in 1859) and restored legislative powers to Bombay and Madras.",
    "1861 சட்டம் போர்ட்ஃபோலியோ (துறை ஒதுக்கீடு) முறையை அங்கீகரித்ததுடன் பம்பாய், மதராஸின் சட்ட அதிகாரங்களை மீண்டும் வழங்கியது.",
    "Indian Councils Act 1861 empowered the Viceroy to issue Ordinances during emergencies with a validity of 6 months.",
    "1861 சட்டம் வைஸ்ராய்க்கு 6 மாத கால அவகாசம் கொண்ட அவசரச் சட்டங்களை (Ordinances) பிறப்பிக்கும் அதிகாரத்தை வழங்கியது.",
    "Remember", 60, ["Polity", "Historical Background", "Indian Councils Act 1861", "Nominations"]
))

questions.append(make_q(
    "HB_M_010", "Conceptual",
    "What was the significant advance made by the Indian Councils Act of 1892 regarding the financial powers of the Legislative Councils?",
    "சட்டமன்ற கவுன்சில்களின் நிதி அதிகாரங்கள் தொடர்பாக 1892 ஆம் ஆண்டின் இந்திய கவுன்சில்கள் சட்டம் செய்த குறிப்பிடத்தக்க முன்னேற்றம் யாது?",
    "Members were granted the power to vote on demands for grants and veto the budget.",
    "உறுப்பினர்களுக்கு மானியக் கோரிக்கைகள் மீது வாக்களிக்கும் மற்றும் வரவு செலவுத் திட்டத்தை நிராகரிக்கும் அதிகாரம் வழங்கப்பட்டது.",
    "Members were given the power of discussing the annual financial statement (budget) and addressing questions to the executive.",
    "உறுப்பினர்களுக்கு வருடாந்திர நிதிநிலை அறிக்கையை (பட்ஜெட்) விவாதிக்கவும், நிர்வாகத்திடம் கேள்விகள் கேட்கவும் அதிகாரம் வழங்கப்பட்டது.",
    "Members were allowed to move resolutions on the budget and ask supplementary questions.",
    "உறுப்பினர்களுக்கு பட்ஜெட் மீது தீர்மானம் கொண்டு வரவும் கூடுதல் கேள்விகள் (துணைக் கேள்விகள்) கேட்கவும் அனுமதிக்கப்பட்டது.",
    "Financial powers were completely transferred to elected Indian provincial representatives.",
    "நிதி அதிகாரங்கள் தேர்ந்தெடுக்கப்பட்ட இந்திய மாகாணப் பிரதிநிதிகளுக்கு முழுமையாக மாற்றப்பட்டன.",
    "B",
    "The 1892 Act allowed council members to discuss the budget and address questions to the executive (with 6 days prior notice). However, members could NOT vote on the budget or ask supplementary questions (that came in 1909).",
    "1892 ஆம் ஆண்டு சட்டம் கவுன்சில் உறுப்பினர்களுக்கு பட்ஜெட் பற்றி விவாதிக்கவும், கேள்விகள் கேட்கவும் உரிமை அளித்தது (6 நாட்கள் முன் அறிவிப்புடன்). ஆனால் வாக்களிக்கும் உரிமையோ துணைக் கேள்விகள் கேட்கும் உரிமையோ வழங்கப்படவில்லை (அவை 1909 இல் வந்தன).",
    "Incorrect. Voting on demands for grants was introduced later by GOI Act 1919.",
    "தவறு. மானியக் கோரிக்கைகள் மீது வாக்களிக்கும் அதிகாரம் 1919 சட்டத்தில்தான் வந்தது.",
    "Correct. Allowed discussion of budget and asking questions to executive without voting or supplementary questions.",
    "சரி. பட்ஜெட் விவாதம் மற்றும் கேள்விகள் கேட்க அனுமதித்தது; வாக்களிக்கவோ துணைக் கேள்விகள் கேட்கவோ அனுமதியில்லை.",
    "Incorrect. Moving resolutions on budget and supplementary questions were allowed by Morley-Minto Reforms 1909.",
    "தவறு. தீர்மானங்கள் கொண்டுவருவதும் துணைக் கேள்விகள் கேட்பதும் 1909 மோர்லே-மிண்டோ சீர்திருத்தங்களால் அனுமதிக்கப்பட்டன.",
    "Incorrect. Financial powers were not transferred to elected Indians in 1892.",
    "தவறு. 1892 இல் நிதி அதிகாரங்கள் இந்தியர்களுக்கு மாற்றப்படவில்லை.",
    "1892 Act introduced an element of 'indirect election' through recommendations by local bodies, though the word 'election' was not explicitly used in the Act.",
    "1892 சட்டம் உள்ளாட்சி அமைப்புகளின் பரிந்துரைகள் மூலம் 'மறைமுக தேர்தல்' என்ற கூறைக் கொண்டு வந்தது ('தேர்தல்' என்ற சொல் பயன்படுத்தப்படவில்லை).",
    "Indian Councils Act 1892 increased non-official members in both Central and Provincial Legislative Councils.",
    "1892 சட்டம் மத்திய மற்றும் மாகாண சட்டமன்ற கவுன்சில்களில் அரசுசாரா உறுப்பினர்களின் எண்ணிக்கையை உயர்த்தியது.",
    "Understand", 60, ["Polity", "Historical Background", "Indian Councils Act 1892", "Budget Discussion"]
))

questions.append(make_q(
    "HB_M_011", "Conceptual",
    "The Indian Councils Act of 1909 (Morley-Minto Reforms) introduced communal representation for Muslims. Who was the first Indian appointed to the Viceroy's Executive Council under this Act?",
    "1909 ஆம் ஆண்டின் இந்திய கவுன்சில்கள் சட்டம் (மோர்லே-மிண்டோ சீர்திருத்தங்கள்) முஸ்லிம்களுக்கான வகுப்புவாத பிரதிநிதித்துவத்தை அறிமுகப்படுத்தியது. இச்சட்டத்தின் கீழ் வைஸ்ராயின் நிர்வாகக் குழுவில் நியமிக்கப்பட்ட முதல் இந்தியர் யார்?",
    "Satyendra Prasad Sinha", "சத்யேந்திர பிரசாத் சின்ஹா",
    "Syed Ali Imam", "சையத் அலி இமாம்",
    "Bichitra Narayan Das", "பிசித்ர நாராயண் தாஸ்",
    "Sachchidananda Sinha", "சச்சிதானந்த சின்ஹா",
    "A",
    "Satyendra Prasad Sinha (later Lord Sinha) became the first Indian to join the Viceroy's Executive Council. He was appointed as the Law Member under the Morley-Minto Reforms of 1909.",
    "1909 மோர்லே-மிண்டோ சீர்திருத்தங்களின் கீழ் வைஸ்ராயின் நிர்வாக கவுன்சிலில் சேர்ந்த முதல் இந்தியர் சத்யேந்திர பிரசாத் சின்ஹா (சட்ட உறுப்பினர்) ஆவார்.",
    "Correct. Satyendra Prasad Sinha was appointed as the Law Member in Viceroy's Executive Council.",
    "சரி. சத்யேந்திர பிரசாத் சின்ஹா வைஸ்ராய் நிர்வாக கவுன்சிலின் சட்ட உறுப்பினராக நியமிக்கப்பட்டார்.",
    "Incorrect. Syed Ali Imam succeeded S.P. Sinha later.",
    "தவறு. சையத் அலி இமாம் பின்னர் எஸ்.பி. சின்ஹாவிற்குப் பிறகு வந்தவர்.",
    "Incorrect. Bichitra Narayan Das was not part of the Executive Council.",
    "தவறு. பிசித்ர நாராயண் தாஸ் நிர்வாக கவுன்சில் உறுப்பினர் அல்ல.",
    "Incorrect. Sachchidananda Sinha was the interim President of Constituent Assembly in 1946.",
    "தவறு. சச்சிதானந்த சின்ஹா 1946 அரசியலமைப்பு சபையின் இடைக்காலத் தலைவர்.",
    "Lord Minto came to be known as the 'Father of Communal Electorate' because he legalized communalism by granting separate electorates to Muslims.",
    "முஸ்லிம்களுக்கு தனித் தொகுதி வழங்கி வகுப்புவாதத்தை சட்டப்பூர்வமாக்கியதால் லார்ட் மிண்டோ 'வகுப்புவாதத் தொகுதிகளின் தந்தை' என அழைக்கப்பட்டார்.",
    "Morley-Minto Reforms 1909 allowed members to ask supplementary questions and move resolutions on the budget.",
    "1909 மோர்லே-மிண்டோ சீர்திருத்தங்கள் உறுப்பினர்கள் துணைக் கேள்விகள் கேட்கவும் பட்ஜெட் மீது தீர்மானம் கொண்டு வரவும் அனுமதித்தன.",
    "Understand", 60, ["Polity", "Historical Background", "Indian Councils Act 1909", "Executive Council"]
))

questions.append(make_q(
    "HB_M_012", "Conceptual",
    "Under the Government of India Act 1919 (Montagu-Chelmsford Reforms), what was the fundamental mechanism of 'Dyarchy' introduced at the provincial level?",
    "1919 ஆம் ஆண்டின் இந்திய அரசுச் சட்டத்தின் (மாண்டேகு-செம்ஸ்ஃபோர்டு சீர்திருத்தங்கள்) கீழ், மாகாண மட்டத்தில் அறிமுகப்படுத்தப்பட்ட 'இரட்டை ஆட்சி'யின் (Dyarchy) அடிப்படை நுட்பம் யாது?",
    "Division of central legislature into Council of State and Legislative Assembly.",
    "மத்திய சட்டமன்றத்தை மாநிலங்கள் அவை மற்றும் சட்டமன்றப் பேரவை என இரண்டாகப் பிரிப்பது.",
    "Division of provincial subjects into Reserved subjects (governed by Governor with Executive Council) and Transferred subjects (governed by Governor with Ministers responsible to legislature).",
    "மாகாணத் துறைகளை ஒதுக்கப்பட்ட துறைகள் (கவர்னர் மற்றும் நிர்வாகக் குழு) மற்றும் மாற்றப்பட்ட துறைகள் (சட்டமன்றத்திற்குப் பொறுப்பான அமைச்சர்கள்) என பிரிப்பது.",
    "Division of administrative control between Viceroy and Secretary of State.",
    "வைஸ்ராய் மற்றும் அரசுச் செயலாளருக்கு இடையே நிர்வாகக் கட்டுப்பாட்டைப் பிரிப்பது.",
    "Division of revenue sources between British Indian Provinces and Princely States.",
    "பிரிட்டிஷ் இந்திய மாகாணங்களுக்கும் சுதேச சமஸ்தானங்களுக்கும் இடையே வருவாய் ஆதாரங்களைப் பிரிப்பது.",
    "B",
    "The 1919 Act introduced Dyarchy in 8 provinces. Provincial subjects were divided into Reserved (Law & order, Finance, Land Revenue) under Governor & non-responsible Executive Council, and Transferred (Education, Health, Local Self-Govt) under responsible Ministers.",
    "1919 சட்டம் மாகாணங்களில் இரட்டை ஆட்சியை அறிமுகப்படுத்தியது. மாகாணத் துறைகள் ஒதுக்கப்பட்டவை (சட்டம்-ஒழுங்கு, நிதி - கவர்னர்/நிர்வாகக் குழு) மற்றும் மாற்றப்பட்டவை (கல்வி, சுகாதாரம் - சட்டமன்றத்திற்குப் பொறுப்பான அமைச்சர்கள்) எனப் பிரிக்கப்பட்டன.",
    "Incorrect. Bicameralism at Centre (Council of State and Legislative Assembly) was another feature of 1919 Act, not Dyarchy.",
    "தவறு. மத்திய சட்டமன்றத்தை ஈரவையாக்கியது 1919 சட்டத்தின் மற்றொரு அம்சம், அது இரட்டை ஆட்சி அல்ல.",
    "Correct. Dyarchy meant dividing provincial subjects into Reserved and Transferred lists.",
    "சரி. இரட்டை ஆட்சி என்பது மாகாணத் துறைகளை ஒதுக்கப்பட்ட மற்றும் மாற்றப்பட்ட பட்டியல்களாகப் பிரிப்பதாகும்.",
    "Incorrect. Division between Viceroy and Secretary of State was administrative hierarchy, not Dyarchy.",
    "தவறு. வைஸ்ராய் மற்றும் அரசுச் செயலாளர் பிரிவு நிர்வாக படிநிலையாகும்.",
    "Incorrect. Division of revenues between provinces and princely states was part of 1935 federation.",
    "தவறு. மாகாணங்களுக்கும் சுதேச மாநிலங்களுக்கும் நிதிப் பிரிவு 1935 திட்டத்தின் பகுதி.",
    "The GOI Act 1919 led to the creation of the Central Public Service Commission in 1926 (recommended by Lee Commission 1923).",
    "1919 இந்திய அரசுச் சட்டம் 1926 இல் மத்திய பொதுச் சேவை ஆணையம் அமைய வழிவகுத்தது (லீ ஆணையப் பரிந்துரை 1923).",
    "GOI Act 1919 separated Provincial Budgets from the Central Budget for the first time.",
    "1919 இந்திய அரசுச் சட்டம் முதன்முறையாக மாகாண வரவு செலவுத் திட்டங்களை மத்திய வரவு செலவுத் திட்டத்திலிருந்து பிரித்தது.",
    "Understand", 60, ["Polity", "Historical Background", "Government of India Act 1919", "Dyarchy"]
))

questions.append(make_q(
    "HB_M_013", "Conceptual",
    "The Government of India Act 1935 provided for an All-India Federation consisting of Provinces and Princely States. Why did this proposed Federation never actually come into existence?",
    "1935 ஆம் ஆண்டின் இந்திய அரசுச் சட்டம் மாகாணங்கள் மற்றும் சுதேச சமஸ்தானங்களைக் கொண்ட அகில இந்திய கூட்டாட்சிக்கு வழிவகுத்தது. இந்த உத்தேசிக்கப்பட்ட கூட்டாட்சி ஏன் நடைமுறைக்கு வரவில்லை?",
    "The British Parliament repealed the Act before it could be implemented.",
    "பிரிட்டிஷ் பாராளுமன்றம் இச்சட்டம் அமலுக்கு வரும் முன்பே அதை ரத்து செய்தது.",
    "The Princely States did not join the federation as required threshold of accessions was not met.",
    "தேவையான எண்ணிக்கையிலான சுதேச சமஸ்தானங்கள் இணைப்புக் சாசனத்தில் கையெழுத்திடாததால் கூட்டாட்சியில் இணையவில்லை.",
    "The Federal Court declared the federal scheme unconstitutional.",
    "கூட்டாட்சி நீதிமன்றம் இக்கூட்டாட்சித் திட்டத்தை அரசியலமைப்பிற்கு எதிரானது என அறிவித்தது.",
    "The Congress and Muslim League created a separate Joint Assembly.",
    "காங்கிரஸும் முஸ்லிம் லீக்கும் தனி கூட்டுச் சபையை உருவாக்கின.",
    "B",
    "The All-India Federation under the 1935 Act was contingent upon Princely States voluntarily signing Instruments of Accession. Since the rulers of Princely States chose not to join, the proposed federation never materialized.",
    "1935 சட்டத்தின் கீழ் அகில இந்திய கூட்டாட்சி சுதேச சமஸ்தானங்கள் விருப்பத்தின் பேரில் இணைவதைப் பொறுத்து இருந்தது. மன்னர்கள் இணைய மறுத்ததால் கூட்டாட்சி அமையவே இல்லை.",
    "Incorrect. British Parliament did not repeal the 1935 Act; it remained the governing framework until 1947.",
    "தவறு. பிரிட்டிஷ் பாராளுமன்றம் 1935 சட்டத்தை ரத்து செய்யவில்லை; 1947 வரை இதுவே நிர்வாக சட்டமாக இருந்தது.",
    "Correct. Princely States refused to join, so the federation never came into force.",
    "சரி. சுதேச சமஸ்தானங்கள் இணைய மறுத்ததால் கூட்டாட்சி நடைமுறைக்கு வரவில்லை.",
    "Incorrect. The Federal Court (set up in 1937) had no power to strike down British Parliamentary Acts.",
    "தவறு. கூட்டாட்சி நீதிமன்றத்திற்கு பிரிட்டிஷ் பாராளுமன்ற சட்டங்களை ரத்து செய்யும் அதிகாரம் இல்லை.",
    "Incorrect. Congress and Muslim League did not create any separate Joint Assembly.",
    "தவறு. காங்கிரஸும் முஸ்லிம் லீக்கும் தனி கூட்டுச் சபையை உருவாக்கவில்லை.",
    "GOI Act 1935 divided powers into Federal List (59 items), Provincial List (54 items), and Concurrent List (36 items), while Residuary powers were given to the Viceroy.",
    "1935 சட்டம் அதிகாரங்களை கூட்டாட்சிப் பட்டியல் (59), மாகாணப் பட்டியல் (54), இணைப்புப் பட்டியல் (36) எனப் பிரித்தது; எஞ்சிய அதிகாரங்கள் வைஸ்ராயிடம் வழங்கப்பட்டன.",
    "Government of India Act 1935 established Federal Court in 1937 and Reserve Bank of India in 1935.",
    "1935 இந்திய அரசுச் சட்டம் 1937 இல் கூட்டாட்சி நீதிமன்றத்தையும் 1835 இல் ரிசர்வ் வங்கியையும் நிறுவியது.",
    "Understand", 60, ["Polity", "Historical Background", "Government of India Act 1935", "All India Federation"]
))

questions.append(make_q(
    "HB_M_014", "Conceptual",
    "Which of the following was a major constitutional transformation brought about by the Indian Independence Act of 1947 regarding the Constituent Assembly of India?",
    "இந்திய அரசியலமைப்பு சபையைப் பொறுத்தவரை 1947 ஆம் ஆண்டின் இந்திய சுதந்திரச் சட்டத்தால் கொண்டுவரப்பட்ட முக்கிய அரசியலமைப்பு மாற்றம் யாது?",
    "It restricted the Assembly to drafting a Constitution under supervision of the British Crown.",
    "இது அரசியலமைப்பு சபையை பிரிட்டிஷ் அரசியின் மேற்பார்வையின் கீழ் மட்டுமே வரைவு செய்யக் கட்டுப்படுத்தியது.",
    "It declared the Constituent Assembly a fully sovereign body empowered to frame any Constitution and repeal any Act of British Parliament including the Independence Act itself.",
    "இது அரசியலமைப்பு சபையை முழுமையான சுயாட்சி கொண்ட அமைப்பாக அறிவித்து, சுதந்திரச் சட்டம் உட்பட எந்தவொரு பிரிட்டிஷ் சட்டத்தையும் ரத்து செய்யும் அதிகாரத்தை வழங்கியது.",
    "It merged the Constituent Assembly with the British Privy Council.",
    "இது அரசியலமைப்பு சபையை பிரிட்டிஷ் பிரிவி கவுன்சிலுடன் இணைத்தது.",
    "It dissolved the Assembly and called for direct universal adult suffrage elections.",
    "இது சபையைக் கலைத்து நேரடி வயதுவந்தோர் வாக்குரிமை தேர்தலுக்கு அழைப்பு விடுத்தது.",
    "B",
    "The Indian Independence Act 1947 made the Constituent Assembly a fully sovereign body that could alter or repeal any British law applying to India. It also performed dual functions: Constituent (making Constitution) and Legislative (ordinary law-making).",
    "1947 இந்திய சுதந்திரச் சட்டம் அரசியலமைப்பு சபையை முழு இறையாண்மை கொண்ட அமைப்பாக மாற்றியது. இது பிரிட்டிஷ் சட்டங்களை ரத்து செய்ய அதிகாரமளித்ததுடன், அரசியலமைப்பு உருவாக்கம் மற்றும் சாதாரண சட்டமியற்றல் ஆகிய இரட்டைப் பணிகளைச் செய்தது.",
    "Incorrect. British supervision ended completely on August 15, 1947.",
    "தவறு. பிரிட்டிஷ் மேற்பார்வை ஆகஸ்ட் 15, 1947 இல் முற்றிலும் முடிவுக்கு வந்தது.",
    "Correct. Constituent Assembly became fully sovereign with power to repeal British Acts.",
    "சரி. அரசியலமைப்பு சபை பிரிட்டிஷ் சட்டங்களை ரத்து செய்யும் அதிகாரம் கொண்ட முழு இறையாண்மை பெற்ற அமைப்பானது.",
    "Incorrect. Privy Council jurisdiction over Indian appeals was abolished by Indian Assembly in 1949.",
    "தவறு. பிரிவி கவுன்சில் மேல்முறையீட்டு அதிகாரம் 1949 இல் இந்திய சபையால் ரத்து செய்யப்பட்டது.",
    "Incorrect. Assembly was not dissolved; it framed the Constitution and functioned as interim Parliament until 1952.",
    "தவறு. சபை கலைக்கப்படவில்லை; இது 1952 வரை இடைக்கால பாராளுமன்றமாகச் செயல்பட்டது.",
    "Under 1947 Act, when Assembly met as Constituent body it was chaired by Dr. Rajendra Prasad; when it met as Legislative body it was chaired by G.V. Mavlankar.",
    "1947 சட்டப்படி சபை அரசியலமைப்பு அமைப்பாகக் கூடியபோது டாக்டர் ராஜேந்திர பிரசாத்தும், சட்டமன்ற அமைப்பாகக் கூடியபோது ஜி.வி. மாவ்லங்கரும் தலைமை தாங்கினர்.",
    "The Indian Independence Act 1947 abolished the office of Secretary of State for India and transferred functions to Secretary of State for Commonwealth Affairs.",
    "1947 சுதந்திரச் சட்டம் இந்திய அரசுச் செயலாளர் பதவியை ரத்து செய்து, அப்பணிகளை காமன்வெல்த் விவகாரங்களுக்கான செயலாளருக்கு மாற்றியது.",
    "Understand", 60, ["Polity", "Historical Background", "Indian Independence Act 1947", "Sovereignty"]
))

questions.append(make_q(
    "HB_M_015", "Conceptual",
    "What was the structural composition and origin scheme of the Constituent Assembly of India formed in November 1946?",
    "நவம்பர் 1946 இல் அமைக்கப்பட்ட இந்திய அரசியலமைப்பு சபையின் கட்டமைப்பு மற்றும் உருவாக்கத் திட்டம் யாது?",
    "Formed under August Offer 1940, with members directly elected by universal adult franchise.",
    "1940 ஆகஸ்ட் சலுகையின் கீழ் அமைக்கப்பட்டு, உறுப்பினர்கள் நேரடி வயதுவந்தோர் வாக்குரிமை மூலம் தேர்ந்தெடுக்கப்பட்டனர்.",
    "Formed under Cabinet Mission Plan 1946, with total strength of 389 (296 British India, 93 Princely States), partly elected indirectly by provincial assemblies and partly nominated by princely rulers.",
    "1946 கேபினட் மிஷன் திட்டத்தின் கீழ் 389 மொத்த உறுப்பினர்களுடன் (296 பிரிட்டிஷ் இந்தியா, 93 சுதேச மாநிலங்கள்) அமைக்கப்பட்டு, மாகாண சபைகளால் மறைமுகமாகத் தேர்ந்தெடுக்கப்பட்டும் மன்னர்களால் நியமிக்கப்பட்டும் உருவாக்கப்பட்டது.",
    "Formed under Cripps Proposals 1942, consisting exclusively of British Parliamentary representatives.",
    "1942 கிரிப்ஸ் தூதுக்குழுவின் கீழ் அமைக்கப்பட்டு பிரிட்டிஷ் பாராளுமன்றப் பிரதிநிதிகளை மட்டுமே கொண்டிருந்தது.",
    "Formed under Mountbatten Plan 1947, with equal representation for all religious communities.",
    "1947 மவுண்ட்பேட்டன் திட்டத்தின் கீழ் அமைக்கப்பட்டு அனைத்து சமயப் பிரிவினருக்கும் சமமான பிரதிநிதித்துவம் வழங்கப்பட்டது.",
    "B",
    "The Constituent Assembly was constituted in Nov 1946 under Cabinet Mission Plan. Total strength was 389 (296 British India, 93 Princely States). Seats were allocated proportional to population (1 seat per million). It was partly elected (indirect) and partly nominated.",
    "1946 நவம்பரில் கேபினட் மிஷன் திட்டத்தின் கீழ் அரசியலமைப்பு சபை அமைக்கப்பட்டது. மொத்த இடங்கள் 389 (296 பிரிட்டிஷ் இந்தியா, 93 சுதேச சமஸ்தானங்கள்). இது பகுதி மறைமுகத் தேர்தல் மற்றும் பகுதி நியமன அமைப்பாகும்.",
    "Incorrect. August Offer 1940 accepted demand in principle, but Assembly was formed under Cabinet Mission Plan.",
    "தவறு. 1840 ஆகஸ்ட் சலுகை கொள்கையளவில் ஏற்றுக்கொண்டது, ஆனால் சபை அமைந்தது கேபினட் மிஷன் திட்டத்தில்தான்.",
    "Correct. Constituted under Cabinet Mission Plan 1946 with 389 total members.",
    "சரி. 1946 கேபினட் மிஷன் திட்டத்தின் கீழ் 389 உறுப்பினர்களுடன் அமைந்தது.",
    "Incorrect. Cripps proposals (1942) were rejected by Muslim League and Congress.",
    "தவறு. கிரிப்ஸ் தூதுக்குழு திட்டத்தை காங்கிரஸும் முஸ்லிம் லீக்கும் நிராகரித்தன.",
    "Incorrect. Mountbatten Plan (June 3, 1947) was the partition plan, not the origin plan of the Constituent Assembly.",
    "தவறு. மவுண்ட்பேட்டன் திட்டம் பிரிவினைத் திட்டம், சபை உருவாக்கத் திட்டம் அல்ல.",
    "M.N. Roy was the first to put forward the idea of a Constituent Assembly for India in 1934; official demand was made by INC in 1935.",
    "1934 இல் எம்.என். ராய் முதன்முதலில் அரசியலமைப்பு சபை யோசனையை முன்வைத்தார்; காங்கிரஸ் 1935 இல் அதிகாரப்பூர்வ கோரிக்கை விடுத்தது.",
    "The first meeting of Constituent Assembly took place on December 9, 1946; Dr. Sachchidananda Sinha was elected temporary President.",
    "அரசியலமைப்பு சபையின் முதல் கூட்டம் டிசம்பர் 9, 1946 இல் நடந்தது; டாக்டர் சச்சிதானந்த சின்ஹா இடைக்காலத் தலைவராகத் தேர்ந்தெடுக்கப்பட்டார்.",
    "Understand", 60, ["Polity", "Historical Background", "Constituent Assembly", "Cabinet Mission Plan"]
))

# ---------------------------------------------------------
# 10 STATEMENT BASED QUESTIONS (HB_M_016 to HB_M_025)
# ---------------------------------------------------------

questions.append(make_q(
    "HB_M_016", "Statement Based",
    "Consider the following statements regarding the Regulating Act of 1773:\n1. It elevated the Governor of Bengal to 'Governor-General of Bengal' and subordinated the Governors of Bombay and Madras to him in matters of war and peace.\n2. It abolished the Court of Directors of the East India Company completely.\n3. It strictly prohibited the servants of the Company from engaging in any private trade or accepting presents/bribes from natives.\nWhich of the statements given above is/are correct?",
    "1773 ஆம் ஆண்டின் ஒழுங்குமுறைச் சட்டம் தொடர்பான பின்வரும் கூற்றுகளைக் கவனியுங்கள்:\n1. இது வங்காள கவர்னரை 'வங்காள கவர்னர் ஜெனரல்' ஆக உயர்த்தியதுடன், போர் மற்றும் அமைதி விவகாரங்களில் பம்பாய் மற்றும் மதராஸ் கவர்னர்களை அவருக்குக் கீழ் கொண்டு வந்தது.\n2. இது கிழக்கிந்தியக் கம்பெனியின் இயக்குநர்கள் அவையை முற்றிலும் கலைத்தது.\n3. இது கம்பெனி ஊழியர்கள் எந்தவொரு தனிப்பட்ட வர்த்தகத்திலும் ஈடுபடுவதையோ அல்லது உள்நாட்டவர்களிடமிருந்து பரிசுகள்/லஞ்சங்களைப் பெறுவதையோ கண்டிப்புடன் தடை செய்தது.\nமேற்கூறிய கூற்றுகளில் எது/எவை சரி?",
    "1 only", "1 மட்டும்",
    "1 and 3 only", "1 மற்றும் 3 மட்டும்",
    "2 and 3 only", "2 மற்றும் 3 மட்டும்",
    "1, 2 and 3", "1, 2 மற்றும் 3",
    "B",
    "Statement 1 is correct (Warren Hastings became first GG of Bengal; Bombay/Madras subordinated). Statement 2 is incorrect (Court of Directors was NOT abolished; its reporting to British Treasury/Secretary was mandated). Statement 3 is correct (private trade and bribes banned).",
    "கூற்று 1 சரி (வாரன் ஹேஸ்டிங்ஸ் முதல் GG ஆனார்; பம்பாய்/மதராஸ் கீழ் நிலைப்படுத்தப்பட்டன). கூற்று 2 தவறு (இயக்குநர்கள் அவை கலைக்கப்படவில்லை, அறிக்கை சமர்ப்பிக்க உத்தரவிடப்பட்டது). கூற்று 3 சரி (தனிப்பட்ட வர்த்தகம் மற்றும் லஞ்சம் தடை செய்யப்பட்டது).",
    "Incorrect. Statement 3 is also correct.",
    "தவறு. கூற்று 3-ம் சரியானது.",
    "Correct. Statements 1 and 3 are correct, while Statement 2 is false.",
    "சரி. கூற்றுகள் 1 மற்றும் 3 சரி, கூற்று 2 தவறானது.",
    "Incorrect. Statement 2 is false as Court of Directors was abolished much later in 1858.",
    "தவறு. இயக்குநர்கள் அவை 1858-லேயே கலைக்கப்பட்டது.",
    "Incorrect. Statement 2 is false.",
    "தவறு. கூற்று 2 தவறானது.",
    "Pay close attention to absolute words like 'abolished completely'. Court of Directors was retained in 1773 and abolished only in 1858.",
    "'முற்றிலும் கலைக்கப்பட்டது' போன்ற சொற்களைக் கவனிக்கவும். இயக்குநர்கள் அவை 1858 இல் மட்டுமே கலைக்கப்பட்டது.",
    "Regulating Act 1773 established an Executive Council of 4 members to assist the Governor-General of Bengal.",
    "1773 ஒழுங்குமுறைச் சட்டம் வங்காள கவர்னர் ஜெனரலுக்கு உதவ 4 உறுப்பினர்களைக் கொண்ட நிர்வாகக் குழுவை அமைத்தது.",
    "Analyze", 75, ["Polity", "Historical Background", "Regulating Act 1773", "Statement Based"]
))

questions.append(make_q(
    "HB_M_017", "Statement Based",
    "Consider the following statements regarding the Charter Act of 1833:\n1. It added a Law Member (Lord Macaulay) as the fourth member to the Governor-General's Executive Council.\n2. It stripped the East India Company of all commercial activities, transforming it into a purely administrative body.\n3. It successfully introduced an open competition system for selection of civil servants despite opposition from Court of Directors.\nWhich of the statements given above are correct?",
    "1833 ஆம் ஆண்டின் சாசனச் சட்டம் பற்றிய பின்வரும் கூற்றுகளைக் கவனியுங்கள்:\n1. இது கவர்னர் ஜெனரலின் நிர்வாகக் குழுவில் நான்காவது உறுப்பினராக ஒரு சட்ட உறுப்பினரை (லார்ட் மெக்காலே) சேர்த்தது.\n2. இது கிழக்கிந்தியக் கம்பெனியின் அனைத்து வர்த்தக நடவடிக்கைகளையும் நீக்கி, அதை ஒரு தூய நிர்வாக அமைப்பாக மாற்றியது.\n3. இது இயக்குநர்கள் அவையின் எதிர்ப்பையும் மீறி குடிமைப் பணித் தேர்வுக்கு திறந்தவெளிப் போட்டி முறையை வெற்றி கரமாக அறிமுகப்படுத்தியது.\nஎது சரி?",
    "1 and 2 only", "1 மற்றும் 2 மட்டும்",
    "2 and 3 only", "2 மற்றும் 3 மட்டும்",
    "1 and 3 only", "1 மற்றும் 3 மட்டும்",
    "1, 2 and 3", "1, 2 மற்றும் 3",
    "A",
    "Statement 1 is correct (Macaulay added as 4th Law Member, though non-voting initially). Statement 2 is correct (Company commercial function ended completely). Statement 3 is INCORRECT because the 1833 Act attempted open competition, but the provision was negated due to opposition from Court of Directors; open competition succeeded only in 1853.",
    "கூற்று 1 சரி (மெக்காலே 4வது சட்ட உறுப்பினராகச் சேர்க்கப்பட்டார்). கூற்று 2 சரி (கம்பெனி வர்த்தகப் பணி முற்றிலும் முடிந்தது). கூற்று 3 தவறு, ஏனெனில் 1833 இல் திறந்தவெளிப் போட்டி முயற்சி இயக்குநர்கள் அவையின் எதிர்ப்பால் கைவிடப்பட்டது; அது 1853 இல் மட்டுமே வெற்றிகரமாக வந்தது.",
    "Correct. Statements 1 and 2 are true, Statement 3 is false.",
    "சரி. கூற்றுகள் 1 மற்றும் 2 சரி, கூற்று 3 தவறு.",
    "Incorrect. Statement 3 is false.",
    "தவறு. கூற்று 3 தவறானது.",
    "Incorrect. Statement 3 is false.",
    "தவறு. கூற்று 3 தவறானது.",
    "Incorrect. Statement 3 is false.",
    "தவறு. கூற்று 3 தவறானது.",
    "TNPSC Trap: Open competition for civil service was ATTEMPTED in 1833 (failed due to Directors' opposition) but INTRODUCED in 1853.",
    "TNPSC பொறி: குடிமைப் பணி திறந்தவெளிப் போட்டி 1833 இல் முயற்சி செய்யப்பட்டது (தோல்வி), 1853 இல் அறிமுகப்படுத்தப்பட்டது.",
    "Law Member Macaulay chaired the First Law Commission appointed under Charter Act 1833.",
    "1833 சாசனச் சட்டத்தின் கீழ் அமைக்கப்பட்ட முதல் சட்ட ஆணையத்திற்கு சட்ட உறுப்பினர் மெக்காலே தலைமை தாங்கினார்.",
    "Analyze", 75, ["Polity", "Historical Background", "Charter Act 1833", "Civil Services"]
))

questions.append(make_q(
    "HB_M_018", "Statement Based",
    "Consider the following statements regarding the Indian (Central) Legislative Council established under the Charter Act of 1853:\n1. It introduced local representation in the Central Legislative Council for the first time.\n2. Out of the six new legislative members, four were appointed by the local (provincial) governments of Madras, Bombay, Bengal, and Agra.\n3. The non-official Indian members held a majority over official British members in this council.\nWhich of the statements given above is/are correct?",
    "1853 ஆம் ஆண்டின் சாசனச் சட்டத்தின் கீழ் அமைக்கப்பட்ட இந்திய (மத்திய) சட்டமன்ற கவுன்சில் பற்றிய பின்வரும் கூற்றுகளைக் கவனியுங்கள்:\n1. இது முதன்முறையாக மத்திய சட்டமன்ற கவுன்சிலில் உள்ளூர் பிரதிநிதித்துவத்தை அறிமுகப்படுத்தியது.\n2. ஆறு புதிய சட்டமன்ற உறுப்பினர்களில், நான்கு பேர் மதராஸ், பம்பாய், வங்காளம் மற்றும் ஆக்ரா ஆகிய உள்ளூர் (மாகாண) அரசாங்கங்களால் நியமிக்கப்பட்டனர்.\n3. இந்த கவுன்சிலில் அரசுசாரா இந்திய உறுப்பினர்கள் பிரிட்டிஷ் அரசு உறுப்பினர்களை விட பெரும்பான்மையாக இருந்தனர்.\nஎது சரி?",
    "1 and 2 only", "1 மற்றும் 2 மட்டும்",
    "2 and 3 only", "2 மற்றும் 3 மட்டும்",
    "1 only", "1 மட்டும்",
    "1, 2 and 3", "1, 2 மற்றும் 3",
    "A",
    "Statement 1 is correct (local representation introduced). Statement 2 is correct (4 members appointed from Madras, Bombay, Bengal, Agra local governments). Statement 3 is INCORRECT (all 6 new members were official civil servants of the British Company; Indians were not in this council).",
    "கூற்று 1 சரி (உள்ளூர் பிரதிநிதித்துவம் அறிமுகமானது). கூற்று 2 சரி (4 பேர் மதராஸ், பம்பாய், வங்காளம், ஆக்ரா உள்ளூர் அரசுகளால் நியமிக்கப்பட்டனர்). கூற்று 3 தவறு, ஏனெனில் இந்நியமனங்கள் பிரிட்டிஷ் அதிகாரிகளையே சார்ந்திருந்தன; இந்திய உறுப்பினர்கள் இல்லை.",
    "Correct. Statements 1 and 2 are correct.",
    "சரி. கூற்றுகள் 1 மற்றும் 2 சரியானவை.",
    "Incorrect. Statement 3 is false.",
    "தவறு. கூற்று 3 தவறானது.",
    "Incorrect. Statement 2 is also correct.",
    "தவறு. கூற்று 2-ம் சரியானது.",
    "Incorrect. Statement 3 is false.",
    "தவறு. கூற்று 3 தவறானது.",
    "Local representation in 1853 meant representation from provincial governments (Madras, Bombay, Bengal, Agra), NOT elected Indian representatives.",
    "1853 இல் உள்ளூர் பிரதிநிதித்துவம் என்பது மாகாண அரசு அதிகாரிகளின் பிரதிநிதித்துவத்தைக் குறித்தது, இந்திய மக்கள் பிரதிநிதிகளை அல்ல.",
    "The 1853 Act separated legislative and executive functions of the Governor-General's Council.",
    "1853 சட்டம் கவர்னர் ஜெனரல் கவுன்சிலின் சட்டமன்ற மற்றும் நிர்வாகப் பணிகளைப் பிரித்தது.",
    "Analyze", 75, ["Polity", "Historical Background", "Charter Act 1853", "Local Representation"]
))

questions.append(make_q(
    "HB_M_019", "Statement Based",
    "Consider the following statements regarding the Government of India Act 1858:\n1. It abolished both the Board of Control and the Court of Directors, ending the system of Double Government.\n2. The Council of India created by the Act was a 15-member advisory body chaired by the Secretary of State for India.\n3. The Act drastically altered the administrative system prevailing inside India at the local presidency level.\nWhich of the statements given above is/are correct?",
    "1858 ஆம் ஆண்டின் இந்திய அரசுச் சட்டம் பற்றிய பின்வரும் கூற்றுகளைக் கவனியுங்கள்:\n1. இது கட்டுப்பாட்டு வாரியம் மற்றும் இயக்குநர்கள் அவை இரண்டையும் கலைத்து இரட்டை ஆட்சி முறையை முடிவுக்குக் கொண்டு வந்தது.\n2. இச்சட்டத்தால் உருவாக்கப்பட்ட இந்திய கவுன்சில் என்பது இந்திய அரசுச் செயலாளரைத் தலைவராகக் கொண்ட 15 உறுப்பினர்களைக் கொண்ட ஒரு ஆலோசனைக் குழுவாகும்.\n3. இச்சட்டம் உள்ளூர் மாகாண மட்டத்தில் இந்தியாவில் நிலவி வந்த நிர்வாக முறையை வியத்தகு முறையில் மாற்றியமைத்தது.\nஎது சரி?",
    "1 and 2 only", "1 மற்றும் 2 மட்டும்",
    "2 and 3 only", "2 மற்றும் 3 மட்டும்",
    "1 and 3 only", "1 மற்றும் 3 மட்டும்",
    "1, 2 and 3", "1, 2 மற்றும் 3",
    "A",
    "Statement 1 is correct (abolished Board of Control & Court of Directors). Statement 2 is correct (15-member advisory Council of India under Secretary of State). Statement 3 is INCORRECT because the 1858 Act primarily altered governance structure in London (Crown takeover); it did NOT drastically alter the administrative machinery operating within India.",
    "கூற்று 1 சரி (இரட்டை நிர்வாக அமைப்புகளைக் கலைத்தது). கூற்று 2 சரி (அரசுச் செயலாளர் தலைமையில் 15 உறுப்பினர்கள் கொண்ட ஆலோசனைக் குழு). கூற்று 3 தவறு, ஏனெனில் 1858 சட்டம் லண்டன் மட்டத்திலான அதிகார மாற்றத்தையே செய்தது; இந்தியாவில் உள்ளூர் நிர்வாக அமைப்பை மாற்றவில்லை.",
    "Correct. Statements 1 and 2 are correct.",
    "சரி. கூற்றுகள் 1 மற்றும் 2 சரியானவை.",
    "Incorrect. Statement 3 is false.",
    "தவறு. கூற்று 3 தவறானது.",
    "Incorrect. Statement 3 is false.",
    "தவறு. கூற்று 3 தவறானது.",
    "Incorrect. Statement 3 is false.",
    "தவறு. கூற்று 3 தவறானது.",
    "GOI Act 1858 is framed as an administrative overhaul in Britain ('Act for Good Government of India'), while internal administrative machinery in India remained largely unchanged.",
    "1858 சட்டம் பிரிட்டனில் உள்ள மேல் நிர்வாக அமைப்பையே மாற்றியது, இந்தியாவில் உள் நிர்வாக அமைப்பை மாற்றவில்லை.",
    "The 15-member Council of India established in 1858 was purely an advisory body.",
    "1858 இல் அமைக்கப்பட்ட 15 உறுப்பினர்களைக் கொண்ட இந்திய கவுன்சில் ஒரு ஆலோசனைக் குழு மட்டுமே.",
    "Analyze", 75, ["Polity", "Historical Background", "Government of India Act 1858", "Crown Rule"]
))

questions.append(make_q(
    "HB_M_020", "Statement Based",
    "Consider the following statements regarding the Indian Councils Act of 1861:\n1. It initiated legislative decentralization by restoring law-making powers to Bombay and Madras Presidencies.\n2. It gave statutory recognition to the 'Portfolio System' introduced by Lord Canning in 1859.\n3. It empowered the Governor-General to issue ordinances without council concurrence during emergencies, valid for 1 year.\nWhich of the statements given above are correct?",
    "1861 ஆம் ஆண்டின் இந்தியக் கவுன்சில்கள் சட்டம் பற்றிய பின்வரும் கூற்றுகளைக் கவனியுங்கள்:\n1. இது பம்பாய் மற்றும் மதராஸ் மாகாணங்களுக்கு மீண்டும் சட்டமியற்றும் அதிகாரங்களை வழங்கி சட்டமன்ற பரவலாக்கலைத் தொடங்கியது.\n2. இது 1859 இல் லார்ட் கேனிங்கால் அறிமுகப்படுத்தப்பட்ட 'போர்ட்ஃபோலியோ (துறை) முறைமைக்கு' சட்டப்பூர்வ அங்கீகாரம் அளித்தது.\n3. இது அவசரநிலைகளின் போது கவுன்சிலின் ஒப்புதல் இன்றி 1 ஆண்டு செல்லுபடியாகும் அவசரச் சட்டங்களை பிறப்பிக்க கவர்னர் ஜெனரலுக்கு அதிகாரமளித்தது.\nஎது சரி?",
    "1 and 2 only", "1 மற்றும் 2 மட்டும்",
    "2 and 3 only", "2 மற்றும் 3 மட்டும்",
    "1 and 3 only", "1 மற்றும் 3 மட்டும்",
    "1, 2 and 3", "1, 2 மற்றும் 3",
    "A",
    "Statement 1 is correct (restored legislative powers to Bombay & Madras, reversing 1833 centralization). Statement 2 is correct (statutory recognition to Canning's Portfolio system). Statement 3 is INCORRECT because the validity of ordinances issued by the Viceroy was 6 MONTHS, not 1 year.",
    "கூற்று 1 சரி (பம்பாய்/மதராஸ் சட்ட அதிகாரம் மீட்கப்பட்டு பரவலாக்கல் தொடங்கியது). கூற்று 2 சரி (போர்ட்ஃபோலியோ முறைக்கு சட்ட அங்கீகாரம்). கூற்று 3 தவறு, ஏனெனில் வைஸ்ராய் அவசரச் சட்டத்தின் செல்லுபடியாகும் காலம் 6 மாதங்கள், 1 ஆண்டு அல்ல.",
    "Correct. Statements 1 and 2 are true; Statement 3 is false (ordinance validity was 6 months).",
    "சரி. கூற்றுகள் 1 மற்றும் 2 சரி; கூற்று 3 தவறு (அவசரச் சட்டக் காலம் 6 மாதங்கள்).",
    "Incorrect. Statement 3 is false.",
    "தவறு. கூற்று 3 தவறானது.",
    "Incorrect. Statement 3 is false.",
    "தவறு. கூற்று 3 தவறானது.",
    "Incorrect. Statement 3 is false.",
    "தவறு. கூற்று 3 தவறானது.",
    "Pay close attention to duration numbers in TNPSC statements: Ordinance validity under 1861 Act was 6 months (same as modern Article 123/213 maximum duration per session gap).",
    "TNPSC வினாக்களில் கால அளவைக் கவனிக்கவும்: 1861 சட்டத்தின்படி அவசரச் சட்டக் காலம் 6 மாதங்கள் ஆகும்.",
    "Indian Councils Act 1861 also provided for establishment of new legislative councils for Bengal, NWFP, and Punjab.",
    "1861 சட்டம் வங்காளம், வடமேற்கு எல்லைப்புற மாகாணம், பஞ்சாப் ஆகியவற்றிற்கு புதிய சட்டமன்ற கவுன்சில்களை அமைக்க வழிவகுத்தது.",
    "Analyze", 75, ["Polity", "Historical Background", "Indian Councils Act 1861", "Ordinance Power"]
))

# Checkpoint save
with open(target_path, "w", encoding="utf-8") as f:
    json.dump(questions, f, ensure_ascii=False, indent=2)

print(f"Added {len(questions)} questions.")
